{
  "hash": "db59f56e7d80255f5249412f7d0d5015",
  "result": {
    "engine": "knitr",
    "markdown": "\n::: {.cell}\n\n:::\n\n\n# Continuous probability distributions, sampling and precision\n\n## Learning objectives {.unnumbered}\n\nBy the end of this module you will be able to:\n\n-   Describe the characteristics of a Normal distribution\n-   Compute probabilities from a Normal distribution using statistical software\n-   Briefly outline other types of distributions\n-   Explain the purpose of sampling, different sampling methods and their implications for data analysis\n-   Distinguish between standard deviation of a sample and standard error of a mean\n-   Calculate and interpret confidence intervals for a mean\n\n## Optional readings {.unnumbered}\n\n@kirkwood_sterne01; Chapters 4, 5 and 6. [\\[UNSW Library Link\\]](http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728)\n\n@bland15; Sections 3.3 and 3.4, Chapter 7, Sections 8.1 to 8.3. [\\[UNSW Library Link\\]](http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730)\n\n## Introduction\n\nIn this module, we will continue our introduction to probability by considering probability distributions for continuous data. We will introduce one of the most important distributions in statistics: the Normal distribution.\n\nTo describe the characteristics of a population we can gather data about the entire population (as is undertaken in a national census) or we can gather data from a sample of the population. When undertaking a research study, taking a sample from a population is far more cost-effective and less time consuming than collecting information from the entire population. When a sample of a population is selected, summary statistics that describe the sample are used to make inferences about the total population from which the sample was drawn. These are referred to as inferential statistics.\n\nHowever, for the inferences about the population to be valid, a random sample of the population must be obtained. The goal of using random sampling methods is to obtain a sample that is representative of the target population. In other words, apart from random error, the information derived from the sample is expected to be much the same as the information collected from a complete population census as long as the sample is large enough.\n\n## Probability for continuous variables\n\nCalculating the probability for a categorical random variable is relatively straightforward, as there are only a finite number of possible events. However, there are an infinite number of possible values for a continuous variable, and we calculate the probability that the continuous variable lies in a range of values.\n\n## Normal distribution\n\nThe frequency plot for many biological and clinical measurements (for example blood pressure and height) follow a bell shape where the curve is symmetrical about the mean value and has tails at either end. @fig-2-1 [^03-precision-1] and @fig-2-2 [^03-precision-2] demonstrate this type of distribution.\n\n[^03-precision-1]: Source: https://www.aihw.gov.au/reports/risk-factors/high-blood-pressure/contents/high-blood-pressure (accessed March 2021)\n\n[^03-precision-2]: Source: https://ourworldindata.org/human-height (accessed March 2021)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of diastolic blood pressure, 2017–18 Australian Bureau of Statistics National Health Survey](img/mod02/dbp.png){#fig-2-1 width=66%}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of male and female heights](img/mod02/heights.png){#fig-2-2 width=66%}\n:::\n:::\n\n\nThe Normal distribution, also called the Gaussian distribution (named after Johann Carl Friedrich Gauss, 1777–1855), has been shown to fit the frequency distribution of many naturally occurring variables. It is characterised by its bell-shaped, symmetric curve and its tails that approach zero on either side.\n\nThere are two reasons for the importance of the Normal distribution in biostatistics (Kirkwood and Sterne, 2003). The first is that many variables can be modelled reasonably well using the Normal distribution. Even if the observed data were not Normally distributed, it can often be made reasonably Normal after applying some transformation of the data. The second (and possible most important) reason, is based on the central limit theorem and will be discussed later in this module.\n\nThe Normal distribution is characterised by two parameters: the mean ($\\mu$) and the standard deviation ($\\sigma$). The mean defines where the middle of the Normal distribution is located, and the standard deviation defines how wide the tails of the distribution are.\n\nFor a Normal distribution, about 68% of the observations lie between $- \\sigma$ and $\\sigma$ of the mean; 95% of the observations lie between $−1.96 \\times \\sigma$ and $1.96 \\times \\sigma$ from the mean; and almost all the observations (99.7%) lie between $-3 \\times \\sigma$ and $3 \\times \\sigma$ (@fig-2-3). Also note that the mean is the same as the median, as the curve is symmetric about its mean.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Characteristics of a Normal distribution](img/mod02/normal-curve.png){#fig-2-3 width=66%}\n:::\n:::\n\n\n## The Standard Normal distribution\n\nAs each Normal distribution is defined by its mean and standard deviation, there are an infinite number of possible Normal distributions. However, every Normal distribution can be transformed to what we call the Standard Normal distribution, which has a mean of zero ($\\mu = 0$) and a standard deviation of one ($\\sigma = 1$). The Standard Normal distribution is so important that it has been assigned its own symbol: Z.\n\nEvery observation from a Normal distribution $X$ with a mean $\\mu$ and a standard deviation $\\sigma$ can be transformed to a z-score (also called a Standard Normal deviate) by the formula:\n\n$$ z = \\frac{x - \\mu}{\\sigma} $$\n\nThe z-score is simply how far an observation lies from the population mean value, scaled by the population standard deviation.\n\nWe can use z-scores to estimate probabilities, as shown in Worked Example 2.2.\n\n#### Worked Example {.unnumbered}\n\nThis example extends the example of diastolic blood pressure shown in @fig-2-1. Assume that the mean diastolic blood pressure for men is 77.9 mmHg, with a standard deviation of 11. What is the probability that a man selected at random will have high blood pressure (i.e. diastolic blood pressure ≥ 90)?\n\nTo estimate the probability that diastolic blood pressure ≥ 90 (i.e. the upper tail probability), we first need to calculate the z-score that corresponds to 90 mmHg.\n\nUsing the z-score formula, with x=90, $\\mu$=77.9 and $\\sigma$=11:\n\n$$ z = \\frac{90 - 77.9}{11} = 1.1 $$ Thus, a blood pressure of 90 mmHg corresponds to a z-score of 1.1, or a value 1.1 $\\times \\sigma$ above the mean weight of the population.\n\n@fig-2-5 shows the probability of a diastolic blood pressure of 90 mmHg or more in the population for a z-score of greater than 1.1 on a Standard Normal distribution.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Area under the Standard Normal curve (as probability) for Z > 1.1](img/mod02/z-dist-shaded.png){#fig-2-5 width=66%}\n:::\n:::\n\n\nUsing software, we find the probability that a person has a diastolic blood pressure of 90 mmHg or more as P(Z ≥ 1.1) = 0.136.\n\nApart from calculating probabilities, z-scores are most useful for comparing measurements taken from a sample to a known population distribution. It allows measurements to be compared to one another despite being on different scales or having different predicted values.\n\nFor example, if we take a sample of children and measure their weights, it is useful to describe those weights as z-scores from the population weight distribution for each age and gender. Such distributions from large population samples are widely available. This allows us to describe a child’s weight in terms of how much it is above or below the population average. For example, if mean weights were compared, children aged 5 years would be on average heavier than the children aged 3 years simply because they are older and therefore larger. To make a valid comparison, we could use the Z-scores to say that children aged 3 years tend to be more overweight than children aged 5 years because they have a higher mean z-score for weight.\n\n## Assessing Normality\n\nThere are several ways to assess whether a continuous variable is Normally distributed. The best way to assess whether a variable is Normally distributed is to plot its distribution, using a density plot for example. If the density plot looks appoximately bell-shaped and approximately symmetrical, assuming Normality would be reasonable.\n\nIt may be useful to examine a boxplot of a variable in conjunction with a density plot. However a boxplot in isolation is not as useful as a density plot, as a boxplot only indicates whether a variable is distributed symmetrically (indicated by equal \"whiskers\"). A boxplot cannot give an indication of whether the distribution is bell-shaped, or flat.\n\n> For your information: There are formal tests that test for Normality. These tests are beyond the scope of this course and are not recommended.\n\nWe can construct a density plot for `age` in the `pbc` data introduced in Module 1. We can see that the density plot is approximately approximately bell-shaped and roughly symmetrical. The mean (50.7 years) and median (51 years) are similar, as would be expected for a Normal distribution. Thus, it would be reasonable to assume that age is Normally distributed in this set of data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of participant age from PBC study data](03-precision_files/figure-pdf/fig-age-pbc-1.pdf){#fig-age-pbc width=50%}\n:::\n:::\n\n\n## Non-Normally distributed measurements\n\nNot all measurements are Normally distributed, and the symmetry of the bell shape may be distorted by the presence of some very small or very large values. Non-Normal distributions such as this are called skewed distributions.\n\nWhen there are some very large values, the distribution is said to be positively skewed.This often occurs when measuring variables related to time, such as days of hospital stay, where most patients have short stays (say 1 - 5 days) but a few patients with serious medical conditions have very long lengths of hospital stay (say 20 - 100 days).\n\nIn practice, most parametric summary statistics are quite robust to minor deviations from Normality and non-parametric statistical methods are only required when the sample size is small and/or the data are obviously skewed with some influential outliers.\n\nWhen the data are markedly skewed, density plots are not all bell-shaped. For example, serum bilirubin measured from participants in the PBC study are presented in @fig-bili-pbc.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of serum bilirubin from PBC study data](03-precision_files/figure-pdf/fig-bili-pbc-1.pdf){#fig-bili-pbc width=50%}\n:::\n:::\n\n\nIn the plot of c, there is a tail of values to the right, so we would conclude that the distribution is skewed to the right. The mean (3.2 mg/dL) is much larger than the median (1.4 mg/dL), as expected from a skewed distribution.\n\n## Parametric and non-parametric statistical methods\n\nMany statistical methods are based on assumptions about the distribution of the variable – these methods are known as parametric statistical methods. Many methods of statistical inferences based on theoretical sampling properties that are derived from a Normal distribution with the characteristics described above. Thus, it is important that measurements approximate to a Normal distribution before these parametric methods are used. The methods are called ‘parametric’ because they are based on the parameters – the mean and standard deviation - that underlie a Normal distribution. Statistics which do not assume a particular distribution are called distribution-free statistics, or ‘non-parametric statistics’.\n\nIn this course, you will learn about both parametric and non-parametric statistical methods. Parametric summary statistical methods include those based on the mean, standard deviation and range (Module 1), and standard error and 95% confidence interval (Module 3). Parametric statistical tests also include t-tests which will be covered in Modules 4 and 5, and correlation and regression described in Module 8.\n\nNon-parametric summary statistical methods are often based on ranks, and may use such statistics as the median, mode and inter-quartile range (Module 1). Non-parametric statistical tests that use ranking are described in Module 9.\n\n## Other types of probability distributions\n\nIn this module we have considered a Normal probability distribution and how to use it to measure the precision of continuously distributed measurements. Data also follow other types of distributions which are briefly described below. In other modules in this course, we will be looking at a range of methods to analyse health data and will refer back to these different distributions.\n\nNormal approximation of binomial: When the sample size becomes large, it becomes cumbersome to calculate the exact probability of an event using the binomial distribution. Conveniently, with large sample sizes, the binomial distribution approximates a Normal distribution. The mean and SD of a binomial distribution can be used to calculate the probability of the event as though it was from a Normal distribution.\n\nPoisson distribution: is another distribution which is often used in health research for modelling count data. The Poisson distribution is followed when a number of events happen in a fixed time interval. This distribution is useful for describing data such as deaths in the population in a time period. For example, the number of deaths from breast cancer in one year in women over 50 years old will be an observation from a Poisson distribution. We can also use this to make comparisons of mortality rates between populations.\n\nMany other probability distributions can be derived for functions which arise in statistical analyses but the chi-squared, t and F distributions are the three distributions that are most widely used. These have many applications, some of which are described in later modules.\n\nThe chi-squared distribution is a skewed distribution which allows us to determine the probability of a deviation between a count that we observe and a count that we expect for categorical data. One use of this is in conducting statistical tests for categorical data. See Module 7.\n\nA t-distribution is used when the population standard deviation is not known. The t-distribution is appropriate for small samples (\\<30) and its distribution is bell shaped similar to a Normal distribution but slightly flatter. The t-distribution is useful for comparing mean values. See Module 4 and Module 5.\n\n## Sampling methods\n\nMethods have been designed to select participants from a population such that each person in the target population has an equal probability of being chosen. Methods that use this approach are called random sampling methods. Examples include simple random sampling and stratified random sampling.\n\nIn simple random sampling, every person in the population from which the sample is drawn has the same random chance of being selected into the sample. To implement this method, every person in the population is allocated an ID number and then a random sample of the ID numbers is selected. Software packages can be used to generate a list of random numbers to select the random sample.\n\nIn stratified sampling, the population is divided into distinct non-overlapping subgroups (strata) according to an important characteristic (e.g. age or sex) and then a random sample is selected from each of the strata. This method is used to ensure that sufficient numbers of people are sampled from each stratum and therefore each subgroup of interest is adequately represented in the sample.\n\nThe purpose of using random sampling is to minimise selection bias to ensure that the sample enrolled in a study is representative of the population being studied. This is important because the summary statistics that are obtained can then be regarded as valid in that they can be applied (generalised) back to the population.\n\nA non-representative sample might occur when random sampling is used, simply by chance. However, non-random sampling methods, such as using a study population that does not represent the whole population, will often result in a non-representative sample being selected so that the summary statistics from the sample cannot be generalised back to the population from which the participants were drawn. The effects of non-random error are much more serious than the effects of random error. Concepts such as non-random error (i.e. systematic bias), selection bias, validity and generalisability are discussed in more detail in PHCM9794: Foundations of Epidemiology.\n\n## Standard error and precision\n\nModule 1 introduced the mean, variance and standard deviation as measures of central tendency and spread for continuous measurements from a sample or a population. As described in Module 1, we rarely have data on the entire population but we *infer* information *about* the population from a *sample*. For example, we use the sample mean $\\bar x$ as an *estimate* of the true population mean $\\mu$.\n\nHowever, a sample taken from a population is usually a small proportion of the total population. If we were to take multiple samples of data and calculate the sample mean for each sample, we would not expect them to be identical. If our samples were very small, we would not be surprised if our estimated sample means were somewhat different from each other. However, if our samples were large, we would expect the sample means to be less variable, i.e. the estimated sample means would be more close to each other, and hopefully, to the true population mean.\n\n### The standard error of the mean {#sec-semean}\n\nA point estimate is a single best guess of the true value in the population - taken from our sample of data. Different samples will provide slightly different point estimates. The standard error is a measure of variability of the point estimate.\n\nIn particular, the *standard error of the mean* measures the extent to which we expect the means from different samples to vary because of chance due to the sampling process. This statistic is directly proportional to the standard deviation of the variable, and inversely proportional to the size of the sample. The standard error of the mean for a continuously distributed measurement for which the SD is an accurate measure of spread is computed as follows:\n\n$$ \\text{SE}(\\bar{x}) = \\frac{\\text{SD}}{\\sqrt{n}} $$\n\n### Worked Example 3.1: blood pressure of Pima women\n\nThe diastolic blood pressure of 733 female Pima indigenous Americans was measured, and a density plot produced (@fig-dbp-pima). These data are saved as `mod03_blood_pressure.csv`.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Density plot of diastolic blood pressure from 733 Pima indigenous American women](03-precision_files/figure-pdf/fig-dbp-pima-1.pdf){#fig-dbp-pima width=50%}\n:::\n:::\n\n\nThe density plot shows that diastolic blood pressure is approximately normally distributed. The mean diastolic blood pressure in the sample was 72.4 mmHg with a standard deviation of 12.38 mmHg.\n\nHence, the standard error of the mean is estimated as:\n\n$$ \\text{SE}(\\bar{x}) = \\frac{12.38}{\\sqrt{733}} = 0.457 $$\n\nBecause the calculation uses the sample size (n) (i.e. the number of study participants) in the denominator, the SE will become smaller when the sample size becomes larger. A smaller SE indicates that the estimated mean value is more precise.\n\nThe standard error is an important statistic that is related to sampling variation. When a random sample of a population is selected, it is likely to differ in some characteristic compared with another random sample selected from the same population. Also, when a sample of a population is taken, the true population mean is an unknown value.\n\nJust as the standard deviation measures the spread of the data around the population mean, the standard error of the mean measures the spread of the sample means. Note that we do not have different samples, only one. It is a theoretical concept which enables us to conduct various other statistical analyses.\n\n## Data sovereignty: can data be owned?\n\nData sovereignty proclaims the right of peoples to govern the collection, ownership and application of their own data. Data sovereignty recognises data not only as information, but as a cultural and economic asset that holds value for the communities it represents.\n\nThe principle of data sovereignty advocates strongly for data rights and interests, emphasising that data must be used in ways that support and enhance the collective well-being of the communities from which it collected. A critical aspect of this framework is the avoidance of exploitative research practices, ensuring that research is conducted *by* or *with* communities rather than simply *on* them. This participatory approach recognises communities as active members in the research process rather than passive subjects of study.\n\n### The Pima Indian Diabetes Dataset\n\nThe importance of data sovereignty principles is highlighted by the Pima Indian Diabetes Dataset (PIDD). The Pima people, living in Arizona USA, are known for high rates of diabetes and obesity. In 1965, the United States National Institutes of Health began an observational study of the Pima community, viewing their reservation as a \"natural laboratory\" for diabetes research. Originally planned to last ten years, this study continued for approximately forty years, collecting highly personal information including blood pressure, body mass index, and number of pregnancies of Pima Americans.\n\nThe data collected during this study became known as the Pima Indian Diabetes Dataset and was subsequently included in the University of California, Irvine (UCI) Machine Learning Repository.[@universityofcaliforniairvine] This repository, established in 1987, is a collection of datasets and tools used to test and train machine learning models. Although the PIDD appears to have been removed from the UCI repository, it now appears in major machine learning repositories such as Kaggle. Significantly, this dataset has been used to refine algorithms intended for \"knowledge discoveries\" that have nothing to do with diabetes, including the prediction of manhole fires.\n\nThis case raises profound questions about what might be termed \"eternal consent.\" The Pima participants who provided their medical data in 1965 could not have realistically been informed of all potential uses for their medical data forty years into the future. The transformation of intimate health data, collected for a specific diabetes research purpose, into a widely distributed dataset for training machine learning algorithms represents a fundamental breach of the principles of data sovereignty. The Pima community had no control over the secondary uses of their data, no ongoing governance role, and no ability to determine whether these uses aligned with their collective well-being or cultural values. This example demonstrates the critical need for robust data sovereignty frameworks that protect Indigenous peoples' rights to control not only the initial collection of their data but also its subsequent use, storage, and dissemination.\n\n## Central limit theorem\n\nEven though we now have an estimate of the mean and its standard error, we might like to know what the mean from a different random sample of the same size might be. To do this, we need to know how sample means are distributed. In determining the form of the probability distribution of the sample mean ($\\bar{x}$), we consider two cases:\n\n### When the population distribution is unknown:\n\nThe central limit theorem for this situation states:\n\n> In selecting random samples of size $n$ from a population with mean $\\mu$ and standard deviation $\\sigma$, the sampling distribution of the sample mean $\\bar{x}$ approaches a normal distribution with mean $\\mu$ and standard deviation $\\tfrac{\\sigma}{\\sqrt{n}}$ as the sample size becomes large.\n\nThe sample size n = 30 and above is a rule of thumb for the central limit theorem to be used. However, larger sample sizes may be needed if the distribution is highly skewed.\n\n### When the population is assumed to be normal:\n\n> In this case the sampling distribution of $\\bar{x}$ is normal for any sample size.\n\n## 95% confidence interval of the mean\n\nEarlier, we showed that the characteristics of a Standard Normal Distribution are that 95% of the data lie within 1.96 standard deviations from the mean (@fig-2-2). Because the central limit theorem states that the sampling distribution of the mean is approximately Normal in large enough samples, we expect that 95% of the sample mean values would fall within 1.96 × SE units above and below the true mean population value.\n\nFor example, if we took 100 different random samples from the population of Pima women and calculated the mean diastolic blood pressure for each of the 100 samples, approximately 95% of these sample means would fall within 1.96 × SE of the population mean weight.\n\nThis interpretation of the SE is translated into the concept of precision as a 95% confidence interval. A 95% confidence interval is a range of values within which we have 95% confidence that the true population mean lies. If repeated samples were taken a very large number of times, and a 95% confidence interval was calculated for each sample, 95% of the confidence intervals would contain the true population mean.\n\nThe calculation of the 95% confidence interval for a mean is as follows:\n\n$$  \\bar{x} \\pm 1.96 \\times \\text{SE}( \\bar{x} ) $$ This is the generic formula for calculating 95% CI for any summary statistic. In general, the mean value can be replaced by the point estimate of a rate or a proportion and the same formula applies for computing 95% CIs, i.e.\n\n$$ 95\\% \\text{ CI} = \\text{point estimate} \\pm 1.96 \\times \\text{SE}(\\text{point estimate)} $$\n\nThe main difference in the methods used to calculate the 95% CI for different point estimates is the way the SE is calculated. The methods for calculating 95% CI around proportions and other ratio measures will be discussed in Module 6.\n\nThe use of 1.96 as a general critical value to compute the 95% CI is determined by sampling theory. For the confidence interval of the mean, the critical value (1.96) is based on normal distribution (true when the population SD is known). However, in practice, statistical packages will provide slightly different confidence intervals because they use a critical value obtained from the t-distribution. The t-distribution approaches a normal distribution when the sample size approaches infinity, and is close to a normal distribution when the sample size is ≥30.The critical values obtained from the t-distribution are always larger than the corresponding critical value from the normal distribution. The difference gets smaller as the sample size becomes larger. For example, when the sample size n=10, the critical value from the t-distribution is 2.26 (rather than 1.96); when n= 30, the value is 2.05; when n=100, the value is 1.98; and when n=1000, the critical value is 1.96.\n\nThe critical value multiplied by SE (for normal distribution, 1.96 × SE) is called the maximum likely error for 95% confidence.\n\n### The t-distribution and when should I use it?\n\nThe population standard deviation ($\\sigma$) is required for calculation of the standard error. Usually, $\\sigma$ is not known and the sample standard deviation ($s$) is used to estimate it. It is known, however, that the sample standard deviation of a normally distributed variable underestimates the true value of $\\sigma$, particularly when the sample size is small.\n\nSomeone by the pseudonym of Student came up with the Student’s t distribution with ($n-1$) degrees of freedom to account for this underestimation. It looks very much like the standardised normal distribution, only that it has fatter tails (@fig-mod03-z-t-dist). As the degrees of freedom increase (i.e. as $n$ increases), the t-distribution gradually approaches the standard normal distribution. With a sufficiently large sample size, the Student’s t-distribution closely approximates the standardised normal distribution.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The normal (Z) and the student’s t-distribution with 2, 5 and 30 degrees of freedom](img/mod03/mod03-z-t-dist.png){#fig-mod03-z-t-dist width=50%}\n:::\n:::\n\n\nIf a variable $X$ is normally distributed and the population standard deviation $\\sigma$ is known, using the normal distribution is appropriate. However, if $\\sigma$ is not known then one should use the student t-distribution with ($n – 1$) degrees of freedom.\n\n### Worked Example 3.2: blood pressure of Pima women\n\nUsing our example of diastolic blood pressure measured from 733 female Pima indigenous Americans, we can use software to calculate the mean, its standard error, and the 95% confidence interval of the mean:\n\n| n | Mean | Standard deviation | Standard error of the mean | 95% confidence interval of the mean |\n|-------------|-------------|-------------|-------------|--------------------|\n| 733 | 72.4 | 12.38 | 0.46 | 71.5 to 73.3 |\n\n: Summary of blood pressure from female Pima indigenous Americans {#tbl-mean-ci}\n\nWe can interpret this confidence interval as: we are 95% confident that the true mean diastolic blood pressure of female Pima indigenous Americans lies between 71.5 and 73.3 mmHg.\n\n### Worked Example 3.2: 95% CI of a mean using summarised data\n\nThe publication of a study using a sample of 242 participants reported a sample mean systolic blood pressure of 128.4 mmHg and a sample standard deviation of 19.56 mmHg. Find the 95% confidence interval for the mean systolic blood pressure.\n\nUsing jamovi or R, we obtain a 95% confidence interval from 125.9232 to 130.8768.\n\nWe are 95% confident that the true mean systolic blood pressure of the population from which the sample was drawn lies between 125.9 kg and 130.9 mmHg.\n\n{{< pagebreak >}}\n\n# Jamovi notes {.unnumbered}\n\n## Generating new variables\n\nWe commonly need to create new variables based on existing variables in our data. For example, body size is often summarised using the **Body Mass Index (BMI)**. BMI is calculated as: $\\frac{\\text{weight (kg)}}{\\text{height (m)}^2}$.\n\nIn this demonstration, we will import a selection of records from a large health survey, stored in the file `mod03_health_survey.xlsx`. The health survey data contains 1140 records, comprising:\n \n- sex: 1 = respondent identifies as male; 2 = respondent identifies as female\n- height: height in meters\n- weight: weight in kilograms\n\nTo generate a new variable, we use **Data > Compute**:\n\n1. click **Data** to open the spreadsheet, and click into an empty column\n2. click **Setup** then **NEW COMPUTED VARIABLE**\n3. enter the name of the new variable, here `BMI`\n4. in the formula (*f~x~) box enter: `weight / height^2` (note: ^2 represents \"to the power of 2\", or \"squared\")\n\nYou should check the construction of any new variable buy examining a density plot and/or a boxplot:\n\n::: {layout-ncol=2}\n![](img/mod03/jamovi/mod03-newvar-dens.png)\n\n![](img/mod03/jamovi/mod03-newvar-boxp.png)\n\n:::\n\nIn the general population, BMI ranges between about 15 to 30. It appears that BMI has been correctly generated in this example, perhaps with some unsual values that might require investigation.\n\n## Summarising data by another variable\n\nWe will often want to calculate the same summary statistics by another variable. For example, we might want to calculate summary statistics for BMI for males and females separately. We can do this in jamovi by defining sex as a *by-variable*.\n\nThis can be done easily in jamovi by defining a **Split by** variable. For example, to summarise BMI for males and females separately, we use `sex` as the Split by variable:\n\n![](img/mod03/jamovi/mod03-splitby.png)\n\n::: {layout-ncol=2}\n![](img/mod03/jamovi/mod03_splitby_dens.png)\n\n![](img/mod03/jamovi/mod03_splitby_boxp.png)\n\n:::\n\n\n## Computing probabilities from a Normal distribution {#sec-normal-jamovi}\n\njamovi does not have a point-and-click method for computing probabilities from a Normal distribution. Here, instructions are provided for using a third-party applet. This Normal Distribution Applet has been posted at [https://mabognar.github.io/apps/normal.html](https://mabognar.github.io/apps/normal.html){target=\"_blank\"}, and provides a simple and intuitive way to compute probabilities from a Normal distribution. The applet requires three pieces of information:\n\n- $\\mu$: the mean of the Normal distribution being considered\n- $\\sigma$: the standard deviation of the Normal distribution being considered\n- $x$: the value being considered\n\nWe also need to consider whether we are interested in the probability being greater than x, or less than x.\n\nFor example, to obtain the probability of obtaining 0.5 or greater from a standard normal (i.e. $/mu$=0, $/sigma$=1) distribution:\n\n![](img/mod03/jamovi/mod03-norm01.png)\n\nThe Normal curve of interest is shaded, and the probability is provided as 0.30854.\n\nTo calculate the worked example: Assume that the mean diastolic blood pressure for men is 77.9 mmHg, with a standard deviation of 11. What is the probability that a man selected at random will have high blood pressure (i.e. diastolic blood pressure greater than or equal to 90)?\n\n![](img/mod03/jamovi/mod03-norm02.png)\n\n## Calculating a 95% confidence interval of a mean: Individual data {#sec-cimean-jamovi-ind}\n\nTo demonstrate the computation of the 95% confidence interval of a mean, we can use the data from `mod03_blood_pressure.csv`. We can use **Exploration > Descriptives** to calculate the mean, its standard error and the 95% confidence interval for the mean. Choose **dbp** as the analysis variable, and select **Std. error of Mean** and **Confidence interval for Mean** in the **Statistics** section:\n\n![](img/mod03/jamovi/mod3-desc-ci1.png)\n\nThe descriptives output appears:\n\n![](img/mod03/jamovi/mod3-desc-ci2.png)\n\n## Calculating a 95% confidence interval of a mean: Summarised data {#sec-cimean-jamovi-summ}\n\nFor Worked Example 3.2 where we are given the sample mean, sample standard deviation and sample size, we need to install a new Jamovi module, called **esci**. To install a new module, click the large **+ Modules** button on the right-hand side of the Jamovi window, and then choose **jamovi library**:\n\n![](img/mod03/jamovi/mod3-inst-module1.png)\n\nTo install a new module:\n\n1. Ensure that the middle tab, **Available** is selected;\n2. Type **esci** in the search bar. The **esci** module will appear;\n3. Click **INSTALL** to install the module\n4. Click the up-arrow to exit from the Install Module window\n\n![](img/mod03/jamovi/mod3-inst-module2.png)\n\nTo calculate the 95% confidence interval, choose **esci > Means and Medians > Single Group**. Select the **Analyze summary data** tab, and enter the known information: here `128.4` as the **Mean**, `19.56` as the **Standard deviation** and `242` as the **Sample size**. Choose **Extra details** to obtain the Standard Error of the mean:\n\n![](img/mod03/jamovi/mod3-cii1.png)\n\nThe 95% confidence interval is listed as the lower limit (LL) and the upper limit (UL):\n\n![](img/mod03/jamovi/mod3-cii2.png)\n\n\n{{< pagebreak >}}\n\n# R notes {.unnumbered}\n\n## Importing Excel data into R\n\nA common type of file that data are stored in is a Microsoft Excel file (.xls or .xlsx). In this demonstration, we will import a selection of records from a large health survey, stored in the file `mod03_health_survey.xlsx`.\n\nThe health survey data contains 1140 records, comprising:\n\n-   sex: 1 = respondent identifies as male; 2 = respondent identifies as female\n-   height: height in meters\n-   weight: weight in kilograms\n\nTo import data from Microsoft Excel, we can use the `read_excel()` function in the `readxl` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install the package if required\n# install.packages(\"readxl\")\nlibrary(readxl)\n\nsurvey <- read_excel(\"data/examples/mod03_health_survey.xlsx\")\nsummary(survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      sex           height          weight      \n Min.   :1.00   Min.   :1.220   Min.   : 22.70  \n 1st Qu.:1.00   1st Qu.:1.630   1st Qu.: 68.00  \n Median :2.00   Median :1.700   Median : 79.40  \n Mean   :1.55   Mean   :1.698   Mean   : 81.19  \n 3rd Qu.:2.00   3rd Qu.:1.780   3rd Qu.: 90.70  \n Max.   :2.00   Max.   :2.010   Max.   :213.20  \n```\n\n\n:::\n:::\n\n\nWe can see that sex has been entered as a numeric variable. We should transform it into a factor so that we can assign labels to each category:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey$sex <- factor(survey$sex, levels=c(1,2), labels=c(\"Male\", \"Female\"))\n\nsummary(survey$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Male Female \n   513    627 \n```\n\n\n:::\n:::\n\n\nWe also note that height looks like it has been entered as meters, and weight as kilograms.\n\n## Generating new variables\n\nOur health survey data contains information on height and weight. We often summarise body size using BMI: body mass index which is calculated as: $\\frac{\\text{weight (kg)}}{(\\text{height (m)})^2}$\n\nWe can create a new column in our data frame in many ways, such as using the following approach:\n\n`dataframe$new_column <- <formula>`\n\nFor example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey$bmi <- survey$weight / (survey$height^2)\n```\n:::\n\n\nWe should check the construction of the new variable by examining some records. The `head()` and `tail()` functions list the first and last 6 records in any dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 4\n  sex    height weight   bmi\n  <fct>   <dbl>  <dbl> <dbl>\n1 Male     1.63   81.7  30.8\n2 Male     1.63   68    25.6\n3 Male     1.85   97.1  28.4\n4 Male     1.78   89.8  28.3\n5 Male     1.73   70.3  23.5\n6 Female   1.57   85.7  34.8\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 4\n  sex    height weight   bmi\n  <fct>   <dbl>  <dbl> <dbl>\n1 Female   1.65   95.7  35.2\n2 Male     1.8    79.4  24.5\n3 Female   1.73   83    27.7\n4 Female   1.57   61.2  24.8\n5 Male     1.7    73    25.3\n6 Female   1.55   91.2  38.0\n```\n\n\n:::\n:::\n\n\nWe should also check the construction of any new variable buy examining a density plot and/or a boxplot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(data=survey, mapping=aes(x=bmi)) +\n  geom_density() +\n  theme_classic() +\n  labs(x=\"BMI (kg/m2)\")\n\n\nggplot(data=survey, mapping=aes(y=bmi)) +\n  geom_boxplot() +\n  theme_classic() +\n  labs(y=\"BMI (kg/m2)\") +\n  theme(\n    axis.title.x = element_blank(),\n    axis.text.x = element_blank(),\n    axis.ticks.x = element_blank())\n```\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-precision_files/figure-pdf/unnamed-chunk-7-1.pdf)\n:::\n:::\n\n\n\nIn the general population, BMI ranges between about 15 to 30. It appears that BMI has been correctly generated in this example. We should investigate the very low and some of the very high values of BMI, but this will be left for another time.\n\n## Introducing the `dplyr` package\n\n`dplyr` is a package that provides a set of functions to manipulate data. We have previously created new columns of data, or changed existing columns using `<-`. In `dplyr`, we can use the `mutate()` function to create new variables or to change existing variables. The advantage of `mutate()` is that we can create multiple new variables in the one function, using code that is easy to read.\n\nFor example, in this module we have used `<-` to:\n\n1. define `sex` as a **factor**, and\n2. create BMI.\n\nWe could do these manipulations using `mutate()` as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\nsurvey <- mutate(survey, sex = factor(sex, levels=c(1,2), labels=c(\"Male\", \"Female\")),\n                         bmi = weight / height^2)\n```\n:::\n\n\nNote that the results of `<-` and `mutate()` are identical. Some authors, however, see the `mutate()` approach easier to read.\n\n## Summarising data by another variable\n\nWe will often want to calculate the same summary statistics by another variable. For example, we might want to calculate summary statistics for BMI for males and females separately. We can do this in in the `descriptives` function by defining sex as a `splitBy` variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jmv)\ndescriptives(data=survey, vars=bmi, splitBy = sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n DESCRIPTIVES\n\n Descriptives                                 \n ──────────────────────────────────────────── \n                         sex       bmi        \n ──────────────────────────────────────────── \n   N                     Male           513   \n                         Female         627   \n   Missing               Male             0   \n                         Female           0   \n   Mean                  Male      28.29561   \n                         Female    27.81434   \n   Median                Male      27.39592   \n                         Female    26.66667   \n   Standard deviation    Male      5.204975   \n                         Female    6.380523   \n   Minimum               Male      16.47519   \n                         Female    9.209299   \n   Maximum               Male      57.23644   \n                         Female    52.59516   \n ──────────────────────────────────────────── \n```\n\n\n:::\n:::\n\n\n## Using `ggplot2` to plot density plots by another variable\n\nWe can define a grouping variable as a `facet_wrap` to create a grid of graphs separately for each value of the grouping variable. For example, to create a density plot for each sex, we would use `facet_wrap(vars(sex))` as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=survey, mapping=aes(x=bmi)) +\n  geom_density() +\n  facet_wrap(vars(sex)) +\n  theme_classic() +\n  labs(x=\"BMI (kg/m2)\")\n```\n\n::: {.cell-output-display}\n![](03-precision_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n## Using `ggplot2` to plot boxplots plots by another variable\n\nAs for density plots, we can use a `facet_wrap` for boxplots. Alternatively (and possibly easier), we can define `sex` as an `x` variable in our `mapping` statement:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=survey, mapping=aes(y=bmi, x=sex)) +\n  geom_boxplot() +\n  theme_classic() +\n  labs(y=\"BMI (kg/m2)\")\n```\n\n::: {.cell-output-display}\n![](03-precision_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n## Summarising a single column of data\n\nIn Module 1, we started with a very simple analysis: reading in six ages, and them using `summary()` to calculate descriptive statistics. We then went on to use the `decriptives()` function in the `jmv` package as more flexible way of calculating descriptive statistics. Let's revisit this analysis:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Author: Timothy Dobbins\n# Date: 5 April 2022\n# Purpose: My first R script\nlibrary(jmv)\n\nage <- c(20, 25, 23, 29, 21, 27)\n\n# Use \"summary\" to obtain descriptive statistics\nsummary(age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  20.00   21.50   24.00   24.17   26.50   29.00 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Use the \"descriptives\" function from jmv to obtain descriptive statistics\ndescriptives(age)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError:\n! Argument 'data' must be a data frame\n```\n\n\n:::\n:::\n\n\nThe `summary()` function has worked correctly, but the `descriptives()` function has given an error: `Error: Argument 'data' must be a data frame`. What on earth is going on here?\n\nThe error gives us a clue here - the `descriptives()` function requires a data frame for analysis. We have provided the object `age`: a **vector**. As we saw in @sec-data-structures, a vector is a single column of data, while a data frame is a collection of columns.\n\nIn order to summarise a vector using the `descriptives()` function, we must first convert the vector into a data frame using `as.data.frame()`. For example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Author: Timothy Dobbins\n# Date: 5 April 2024\n# Purpose: My first R script\nlibrary(jmv)\n\nage <- c(20, 25, 23, 29, 21, 27)\n\n# Use \"summary\" to obtain descriptive statistics\nsummary(age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  20.00   21.50   24.00   24.17   26.50   29.00 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Create a new data frame from the vector age:\n\nage_df <- as.data.frame(age)\n\n# Use \"descriptives\" to obtain descriptive statistics for age_df\ndescriptives(age_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n DESCRIPTIVES\n\n Descriptives                       \n ────────────────────────────────── \n                         age        \n ────────────────────────────────── \n   N                            6   \n   Missing                      0   \n   Mean                  24.16667   \n   Median                24.00000   \n   Standard deviation    3.488075   \n   Minimum               20.00000   \n   Maximum               29.00000   \n ────────────────────────────────── \n```\n\n\n:::\n:::\n\n\n## Computing probabilities from a Normal distribution {#sec-normal-r}\n\nThe Normal Distribution Applet posted at [https://mabognar.github.io/apps/normal.html](https://mabognar.github.io/apps/normal.html){target=\"_blank\"}, provides a simple and intuitive way to compute probabilities from a binomial distribution. Refer to the jamovi instructions for details.\n\nWe can use the `pnorm` function to calculate probabilities from a Normal distribution:\n\n-   `pnorm(q, mean, sd)` calculates the probability of observing a value of `q` or less, from a Normal distribution with a mean of `mean` and a standard deviation of `sd`. Note that if `mean` and `sd` are not entered, they are assumed to be 0 and 1 respectively (i.e. a standard normal distribution.)\n-   `pnorm(q, mean, sd, lower.tail=FALSE)` calculates the probability of observing a value of more than `q`, from a Normal distribution with a mean of `mean` and a standard deviation of `sd`.\n\nTo obtain the probability of obtaining 0.5 or greater from a standard normal distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(0.5, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3085375\n```\n\n\n:::\n:::\n\n\nTo calculate the worked example: Assume that the mean diastolic blood pressure for men is 77.9 mmHg, with a standard deviation of 11. What is the probability that a man selected at random will have high blood pressure (i.e. diastolic blood pressure greater than or equal to 90)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(90, mean = 77.9, sd = 11, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1356661\n```\n\n\n:::\n:::\n\n\n\n## Calculating a 95% confidence interval of a mean: individual data {#sec-cimean-r-ind}\n\nTo demonstrate the computation of the 95% confidence interval of a mean, we can use the data from `mod03_blood_pressure.csv`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npima <- read.csv(\"data/examples/mod03_blood_pressure.csv\")\n```\n:::\n\n\nWe can examine the data set using the `summary` command:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pima)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      dbp        \n Min.   : 24.00  \n 1st Qu.: 64.00  \n Median : 72.00  \n Mean   : 72.41  \n 3rd Qu.: 80.00  \n Max.   :122.00  \n```\n\n\n:::\n:::\n\n\nThe mean and its 95% confidence interval can be obtained many ways in R. We will use the `descriptives()` function within the `jmv` package to calculate the standard error of the mean, and a confidence interval, by including `se = TRUE` and `ci = TRUE`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(jmv)\ndescriptives(data=pima, vars=dbp, se=TRUE, ci=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n DESCRIPTIVES\n\n Descriptives                             \n ──────────────────────────────────────── \n                              dbp         \n ──────────────────────────────────────── \n   N                                733   \n   Missing                            0   \n   Mean                        72.40518   \n   Std. error mean            0.4573454   \n   95% CI mean lower bound     71.50732   \n   95% CI mean upper bound     73.30305   \n   Median                            72   \n   Standard deviation          12.38216   \n   Minimum                           24   \n   Maximum                          122   \n ──────────────────────────────────────── \n   Note. The CI of the mean assumes\n   sample means follow a\n   t-distribution with N - 1 degrees\n   of freedom\n```\n\n\n:::\n:::\n\n\n## Calculating a 95% confidence interval of a mean: summarised data {#sec-cimean-r-summ}\n\nFor Worked Example 3.2 where we are given the sample mean, sample standard deviation and sample size. R does not have a built-in function to calculate a confidence interval from summarised data, but we can write our own.\n\n**Note: writing your own functions is beyond the scope of this course. You should copy and paste the code provided to do this.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Copy this section\nci_mean <- function(n, mean, sd, width=0.95, digits=3){\n  lcl <- mean - qt(p=(1 - (1-width)/2), df=n-1) * sd/sqrt(n)\n  ucl <- mean + qt(p=(1 - (1-width)/2), df=n-1) * sd/sqrt(n)\n  \n  print(paste0(width*100, \"%\", \" CI: \", format(round(lcl, digits=digits), nsmall = digits),\n               \" to \", format(round(ucl, digits=digits), nsmall = digits) ))\n\n}\n### End of copy\n\nci_mean(n=242, mean=128.4, sd=19.56, width=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"95% CI: 125.923 to 130.877\"\n```\n\n\n:::\n\n```{.r .cell-code}\nci_mean(n=242, mean=128.4, sd=19.56, width=0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"99% CI: 125.135 to 131.665\"\n```\n\n\n:::\n:::\n\n\n\n{{< pagebreak >}}\n\n# Activities {.unnumbered}\n\n### Activity 3.1 {-}\n\nAn investigator wishes to survey people living with agoraphobia (a type of anxiety disorder). People with agoraphobia find it difficult to leave environments they know and consider to be safe for fear of having anxiety or a panic attack.\n\nThe investigator buys an ad on Facebook asking for volunteer participants to complete an in-person interview. A total of 950 replies are received of which the investigator randomly selects 50. However, only 15 volunteers turn up for their interview.\n\n1.\tWhich of the following statements is true?\n\na)\tThe final 15 participants are likely to be a representative sample of the population available to the investigator\nb)\tThe final 15 participants are likely to be a representative sample of the population of people living with agoraphobia\nc)\tThe randomly selected 50 participants are likely to be a representative sample of people with agoraphobia who replied to the Facebook ad\nd)\tNone of the above\n\n2.\tThe basic problem confronted by the investigator is that:\n\na)\tThe accessible population might be different from the target population\nb)\tThe sample has been chosen using an unethical method\nc)\tThe sample size was too small\nd)\tIt is difficult to obtain a sample of people living with agoraphobia in a scientific way\n\n3. Think about how you might design a study to recruit people living with agoraphobia.\n\n### Activity 3.2 {-}\n\nA dental epidemiologist wants to estimate the mean weekly consumption of dietary sugar among preschool children in Kensington, NSW. She takes four samples from different preschools in the area. The estimated daily intake of total sugar consumption (in grams) are saved in `Activity_3.2.rds`.\n\na) Obtain the sample size, the mean and standard deviation for total sugar consumption for each preschool. Plot the distribution of total sugar consumption by preschool. What do you notice about the variability of total sugar consumption by preschool?\nb) Obtain the standard error of the mean total sugar consumption by preschool. What happens to the standard error as the sample size increases?\nc) Obtain the 95% confidence interval of the mean total sugar consumption by preschool, and comment.\nd) What can you say about the precision of the sample mean as the sample size increases?\ne) Interpret the 95% confidence interval of the mean total sugar consumption for one preschool. What population are we making inferences about? Is this valid?\n\n### Activity 3.3 {-}\n\nThe dataset for this activity is the same as the one used in Activity 1.3 in Module 1: a study was conducted to investigate the general health of undergraduate students at Australian universities. A random selection of 218 UNSW undergradute students from UNSW were enrolled, and their diastolic blood pressures were recorded. The file is `Activity_1.3.csv`.\n\na) Plot diastolic blood pressure and describe the distribution.\nb) Use jamovi or R to obtain an estimate of the mean, standard error of the mean and the 95% confidence interval for the mean diastolic blood pressure.\nc) Interpret the 95% confidence interval for the mean diastolic blood pressure.\n\n### Activity 3.4 {-}\n\nUsing the health survey data (`Activity_3.4.xlsx`) described in the computing notes of this module, create a new variable, BMI, which is equal to a person's weight (in kg) divided by their height (in metres) squared (i.e. $\\text{BMI} = \\frac{\\text{weight (kg)}}{\\text{[height (m)]}^2}$. Categorise BMI using the categories:\n\n-   Underweight: BMI \\< 18.5\n-   Normal weight: 18.5 $\\le$ BMI \\< 25\n-   Overweight: 25 $\\le$ BMI \\< 30\n-   Obese: BMI $\\ge$ 30\n\nNote: BMI does not necessarily reflect body fat distribution or describe the same degree of fatness in different individuals. However, at a population level, BMI is a practical and useful measure for identifying overweight or obesity. [^BMI]\n\n[^BMI]: https://www.aihw.gov.au/reports/overweight-obesity/overweight-and-obesity/contents/measuring-overweight-and-obesity\n\nCreate a two-way table to display the distribution of BMI categories by sex (sex: 1 = respondent identifies as male; 2 = respondent identifies as female). Does there appear to be a difference in categorised BMI between males and females?\n\n### Activity 3.5 {-}\nThe data set of hospital stay data for 1323 hypothetical patients is available in csv format (`Activity_3.5.csv`). Import this dataset into jamovi or R. There are two variables in this dataset:\n\n- female: female=1; male=0\n- los: length of stay in days\n\na)\tUse jamovi or R to examine the distribution of length of stay: overall; and separately for females and males. Comment on the distributions.\nb)\tUse jamovi or R to calculate measures of central tendency for hospital stay to obtain information about the average duration of hospital stay. Which summary statistics should you report and why? Report the appropriate statistics of the spread and measure of central tendency chosen.\nc)\tCalculate the measures of central tendency for hospital duration separately for males and females. What can you conclude from comparing these measures for males and females? \n\n### Activity 3.6 {-}\n\nIf weights of men are Normally distributed with a population mean $\\mu$ = 87, and a population standard deviation, $\\sigma$ = 8 kg:\n\na)\tWhat is the probability that a man will weigh 95 kg or more?  Draw a Normal curve of the area represented by this probability in the population (i.e. with $\\mu$ = 87 kg and $\\sigma$ = 8 kg).\nb)\tWhat is the probability that a man will weigh more than 75 kg but less than 95 kg?  Draw the area represented by this probability on a Normal curve.\n\n",
    "supporting": [
      "03-precision_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}