### Activity 4.1 {-}

It has been suggested that the average Australian consumes around 8700 kJ per day. A study was conducted to estimate the average dietary consumption of Australian males, aged between 30 and 50. The mean dietary intake was estimated as 9461 kJ, with a 95% confidence interval from 8879 to 10043 kJ. What can you conclude about the dietary consumption of Australian males from this study?

### Activity 4.2 {-}

Women attending a GP clinic were asked to complete a health survey. Data from 154 responses are saved in `Activity_4.2.csv`. The file contains the following variables:

- id: participant ID number
- age: age in years
- height: height in cm
- weight: weight in kg
- waist: waist circumference in cm

Australia’s National Health Survey has estimated the Australian female population has a mean waist circumference of 87.9cm. Analyse the health survey data to compare women attending a GP clinic to the Australian population.

### Activity 4.3 {-}

Setting the significance level at P < 0.10 instead of the more usual P < 0.05 increases the likelihood of:

a) a Type I error
b) a Type II error
c) rejecting the null hypothesis
d) not rejecting the null hypothesis 

### Activity 4.4 {-}
For a fixed sample size setting the significance level at a very extreme cutoff such as P < 0.001 increases the chances of:

a) obtaining a significant result
b) rejecting the null hypothesis
c) a Type I error
d) a Type II error

