### Activity 7.1 {-}

This activity continues from Activity 6.2, where a survey was conducted of a random sample of 514 upper primary school children to measure the prevalence of asthma. Use the dataset `Activity_6.2.rds` to investigate whether there is a gender difference in the prevalence of asthma.

### Activity 7.2 {-}
This activity continues from Activity 6.5, a study to determine the cause of mortality where 89 people were followed up for 5 years. The file `Activity_7.2.rds` summarise 5-year mortality (the outcome) for 89 people who did or did not have a heart attack (the exposure). The data are entered as:

- heart_attack: Heart attack status: 1=No, 2=Yes
- mortality: 5-year mortality; 1=No, 2=Yes

Analyse these data to assess whether 5-year mortality differs between those who have a heart attack and those who do not.

### Activity 7.3 {-}
Hand hygiene is crucial for retail food workers to prevent the spread of germs and pathogens from their hands to food, which can cause foodborne illnesses. By properly washing their hands, workers can protect customers from contamination and maintain a safe food environment.

A study was conducted by the Sunrise public health unit to assess whether a health promotion campaign could increase the rate of adequate hand hygiene. 107 retail food workers, working in Sunrise, were enrolled in the study, and their hand-washing techniques were observed before and after the health promotion campaign. Handwashing was classified as either inadequate or adequate.

The file `Activity_7.3.csv` contains the following variables:

-	age
-	sex
-	handwash_baseline: handwashing technique before the campaign:
  - 0=inadequate technique, 1=adequate technique 
-	handwash_followup: handwashing technique after the campaign:
  - 0=inadequate technique, 1=adequate technique

Analyse these data to assess the impact of the health promotion campaign.

### Activity 7.4 {-}
A study was conducted to assess whether the rate of premature births differed by region. We examined a survey of 200 live births in an urban region in which 2 babies were born prematurely. We also surveyed 80 live births in a rural region and found that 5 babies were born prematurely.

Analyse these data to answer the research question. Write a brief report summarising your results and state your conclusion.

### Supplementary Activity 7.5 {-}
The betel nut, the seed of the areca palm, is grown in the tropical Pacific and Asia and is a commonly use psycho-active substance. Betel nut is often chewed, wrapped inside betel leaves or in combination with tobacco. Chewing betel nut has been linked with a range of health issues.

A case-control study was conducted to assess the association between chewing betel nut and obstructive coronary artery disease. 293 men with obstructive coronary artery disease were recruited, and 88 reported having chewed betel nut. Of the 720 healthy control men recruited, 57 reported having chewed betel nut.

Analyse these data to answer the research question. Write a brief report summarising your results and state your conclusion.