### Activity 10.1 {-}

We are planning a study to measure the prevalence of a relatively rare condition (say approximately 5%) in children age 0-5 years in a remote community.

a) What type of study would need to be conducted?
b) Use the correct sample size table included in your notes to determine how many children would need to be enrolled for the confidence interval to be
    i. 2%
    i. 4% around the prevalence?
    
What would the resulting prevalence estimates and 95% CIs be?

### Activity 10.2 {-}

We are planning an experimental study to test the use of a new drug to alleviate the symptoms of the common cold compared to the use of Vitamin C. Participants will be randomised to receive the new experimental drug or to receive Vitamin C. How many participants will be required in each group (power = 80%, level of significance = 5%).

a) If the resolution of symptoms is 10% in the control group and 40% in the new treatment group?
b) How large will the sample size need to be if we decide to recruit two control participants to every intervention group participant?
c) If we decide to retain a 1:1 ratio of participants in the intervention and controls groups but the resolution of symptoms is 20% in the control group and 40% in the new treatment group?
d) How many participants would we need to recruit (calculated in c) if a pilot study shows that 15% of people find the new treatment unpalatable and therefore do not take it?

### Activity 10.3 {-}

Myalgic encephalomyelitis/chronic fatigue syndrome (ME/CFS) is a disease featuring extreme fatigue, disrupted sleep, pain and other symptoms that worsen after physical or mental effort. There is a hypothesis that repeated infection with SARS-CoV-2 (the virus that causes COVID-19) may increase the risk of ME/CFS.
A case-control study, to be conducted in NSW, is being designed to test the association between repeated infection with SARS-CoV-2 (three infections or more) and ME/CFS. We expect 40% of the population to have been infected with SARS-CoV-2 three or more times.

a)	How many participants should be enrolled to detect an odds ratio of 2.0 as statistically significant with 90% power and a two-sided 5% level of significance, assuming an equal number of cases and controls?
b)	Your colleague suggests that your estimate of the proportion of people who have been infected with SARS-CoV-2 three or more times is out of date, and the up-to-date proportion is 60%. How many participants should be enrolled under this scenario, retaining 90% power and a two-sided 5% level of significance?
d)	Similar studies on ME/CFS have found that only 80% of cases and 60% of controls complete research studies they enrol in. How many participants should be enrolled to achieve the sample size that you estimated in Part (a)?
e)	Colleagues suggest that it may be difficult to recruit enough cases, and perhaps more controls than cases should be enrolled. How many participants should be enrolled if three controls per case are recruited, keeping the odds ratio, power, and level of significance the same as in Part (a)? You do not need to account for drop-outs in this part.


### Activity 10.4 {-}

The six-minute walk test is designed to assess people’s aerobic capacity and endurance. A person who undertakes the test is asked to walk as far as they possibly can on a hard, flat surface in six minutes. The distance the person walks is called the six-minute walk distance (6MWD). Previous studies have estimated that the 6MWD in people with chronic obstructive pulmonary disease (COPD) has an average of around 360 metres, with a standard deviation of 100 metres.

A researcher is interested in comparing the 6MWD in a group of people with a respiratory disease who undertake an exercise program compared with those who do not undertake the exercise program.

a)	The researcher wishes to undertake a randomised controlled trial to study the effect of the intervention. The researcher believes the minimum clinically important difference is 35 metres. The desired power of the study is 90% and alpha = 0.05. What sample size would you recommend that she use? Include your Stata output in your answer.
b)	A colleague suggests that a minimum clinically important difference should be set to 25 metres. Without performing any calculations, explain what will happen to the required sample size and why.
c)	Research in this area has suggested that around 20% of invited participants fail to attend their scheduled 6MWD. How many participants should the researchers enrol to meet the requirements of part (a)?
d)	The researchers decide on scenario (a). After completing recruitment, the researchers found that 35% of the invited participants (calculated in part (a)) failed to attend. Calculate the revised power to detect a 35 metre difference in 6MWD.	

### Supplementary Activity 10.5 {-}
Your colleague, Clancy, wants to test an intervention consisting of behavioural techniques to reduce the amount of time that primary school children spend on small-screen recreation (i.e., use of television, computers, and tablets). Clancy would like to use a randomised controlled trial to assess the impact of the intervention compared to providing an information pamphlet, and will use the relative risk to summarise the intervention effect.

Clancy’s study will use the categorisation of 2 or more hours per day of screen time as the primary outcome. Evidence suggests that 53% of children in primary school spend 2 or more hours per day on small-screen recreation.

a) How many participants should be recruited to detect a relative risk of 0.5, with 90% power and a 2-sided significance level of 0.05?
b) Clancy’s colleague suggests Clancy should instead aim to detect a relative risk of 0.75 (keeping the power and 2-sided significance level as in part (a)). How many children should be recruited for this new effect size? What has happened to the sample size and why?
c) In talking with parents, you find out that they would be more likely to enrol their child in the study if their child had a greater chance of receiving the behavioural intervention than the pamphlet. Assuming Clancy wants to detect a relative risk of 0.75 (i.e., the scenario in part (b)), how many participants should Clancy recruit to have twice as many participants in the behavioural intervention arm compared to the pamphlet arm?
d) Clancy’s colleague suggests that approximately 25% of children drop out of trials in school-based studies, regardless of whether they receive the control or the intervention. How many participants should Clancy recruit to allow for this, based on scenario (c)?

