---
title: "Untitled"

format:
  pdf:
    mainfont: "Roboto"
    sansfont: "Roboto Bold"
---

Here is a simple table (@tbl-1).

```{r tbl-1}
#| echo: false
#| message: false
#| warning: false
#| tbl-pos: h

library(tinytable)

x <- mtcars[1:4, 1:5]
tt(x)
```

@tbl-2 sets decimal places. Seems to be working...

```{r tbl-2}
#| echo: false
#| message: false
#| warning: false
#| tbl-pos: h

tt(x) |>
  tt_format(j=c(1,3), num_fmt = "decimal", digits=1)
```

What if I include a % symbol in @tbl-1:

```{r tbl-1a}
#| echo: false
#| message: false
#| warning: false
#| tbl-pos: h

x <- mtcars[1:4, 1:5]
names(x)[1] <- "mpg %"
  
tt(x, escape=TRUE)
```

What if I include a % symbol in the body of @tbl-1:

```{r tbl-1b}
#| echo: false
#| message: false
#| warning: false
#| tbl-pos: h

x <- mtcars[1:4, 1:5]
x$mpg <- paste(as.character(x$mpg), "%")
  
tt(x, escape=TRUE)
```

Let's try some cross-tabs (@tbl-3).

```{r tbl-3}
#| echo: false
#| message: false
#| warning: false
#| tbl-pos: h

library(dplyr)
library(modelsummary)

pbc <- survival::pbc |>
  mutate(sex = factor(sex, levels=c("m", "f"), labels=c("Male", "Female")),
         stage = factor(stage, levels=c(1,2,3,4), labels=c("Stage 1", "Stage 2", "Stage 3", "Stage 4"))) |> 
  rename(Sex=sex, `Stage of disease`=stage)

datasummary_crosstab(Sex ~ `Stage of disease`, data=pbc)
```

Now a cross-tab with percents.

```{r}
ds <- datasummary_crosstab(Sex ~ `Stage of disease`, data=pbc,
                     statistic = 1 ~ N + Percent("col"),
                     output = "data.frame")

colnames(ds)[2] <- "Stat"

ds <- ds |> 
  mutate(Stat = replace_when(Stat,
                             Stat == "N" ~ "Count",
                             Stat == "% col" ~ "Column percent"))
str(ds)

ft <- tt(ds, notes = c('* Stage of disease was missing for 6 participants'))

names(ft)[2] <- " "
ft
```

