{
  "hash": "49cd971efeb2acb94cb1e2fad4725291",
  "result": {
    "engine": "knitr",
    "markdown": "\n::: {.cell}\n\n:::\n\n\n# An introduction to hypothesis testing\n\n## Learning objectives {.unnumbered}\n\nBy the end of this module you will be able to:\n\n- Formulate a research question and present it as a null and alternative hypothesis;\n- Understand the role of confidence intervals in assessing research questions;\n- Explain the general framework of hypothesis testing;\n- Interpret P-values as measures of evidence;\n- Distinguish between statistical significance and practical importance;\n- Perform and interpret a one-sample t-test;\n- Explain the concepts of one-tailed and two-tailed statistical tests, and determine when each is appropriate;\n- Report the results of hypothesis tests clearly, accurately, and in plain language.\n\n## Optional readings {.unnumbered}\n\n@kirkwood_sterne01; Chapter 8. [\\[UNSW Library Link\\]](http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728)\n\n@bland15; Sections 9.1 to 9.7; Sections 10.1 and 10.2. [\\[UNSW Library Link\\]](http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730)\n\n## Introduction\n\nIn earlier modules, we examined sampling and how summary statistics can be used to make inferences about a population parameter. For example, we can use the sample mean $\\bar{x}$ to make inferences about $\\mu$, the true mean of the population from which a sample is drawn. In this module, we introduce hypothesis testing as the basis of the statistical tests that are important for reporting results from research and surveillance studies, and that you will be learning in the remainder of this course.\n\nWe use hypothesis testing to answer questions such as whether two groups have different health outcomes or whether there is an association between a treatment and a health outcome. For example, we may want to know:\n\n- whether a safety program has been effective in reducing injuries in a factory, i.e. whether the frequency of injuries in the group who attended a safety program is lower than in the group who did not receive the safety program;\n- whether a new drug is more effective in reducing blood pressure than a conventional drug, i.e. whether the mean blood pressure in the group receiving the new drug is lower than the mean blood pressure in the group receiving the conventional medication;\n- whether an environmental exposure increases the risk of a disease, i.e. whether the frequency of disease is higher in the group who have been exposed to an environmental factor than in the non-exposed group.\n\nWe may also want to know something about a single group. For example, whether the mean blood pressure of a sample is the same as the general population.\n\nThese questions can be answered by setting up a null hypothesis and an alternative hypothesis, and performing a hypothesis test (also known as a significance test). In this module we focus on testing hypotheses about a single population mean, using confidence intervals and the one-sample t-test.\n\n### Worked example\n\nIn this module, we will revisit the Pima example from Module 3 (`mod03_blood_pressure.csv`). A sample of 733 female Pima indigenous Americans was taken, and their diastolic blood pressure was measured (among other measures). We saw in Module 3 that a density plot demonstrates that the data are approximately normally distributed, and the mean diastolic blood pressure was estimated as 72.4 mmHg with a 95% confidence interval from 71.5 to 73.3 mmHg.\n\n## Research questions\n\nA research question is an open, neutral question that states what we want to find out - often phrased using everyday language. Research questions guide study design and data collection, and do not presuppose an answer. Using our Pima example, a research question could be posed:\n\n- Do Pima women have the same mean diastolic blood pressure as the general US population?\n\nA useful way of structuring research questions in health research is the PECO framework:\n\n- Population: Who is being studied?\n- Exposure: What exposure, risk factor, or condition is of interest?\n- Comparator: What is the exposure being compared against?\n- Outcome: What outcome is being measured?\n\nIn the example above:\n\n- Population: Pima women\n- Comparator: General US population\n- Outcome: Diastolic blood pressure\n\nNote there as there is only one group here, there is no \"exposure\".\n\n## Using confidence intervals to assess research questions\n\nWe can use the 95% confidence interval to **informally** assess research questions. For example, we can use a 95% confidence interval for the mean to assess whether the population mean is consistent with a hypothesised value. A confidence interval gives a range of plausible values for the true population mean, based on the sample data, and we can compare the confidence interval with the hypothesised value.\n\nIf a hypothesised mean lies:\n\n- *outside* the confidence interval, there is *informal evidence* that the population mean differs from the hypothesised mean\n- *inside* the confidence interval, there is *no informal evidence* that the population mean differs from the hypothesised mean\n\nNote that a confidence interval does not provide a quantitative measure of evidence against a null hypothesis; it supports only an informal comparison. Formal hypothesis testing is required to quantify the level of evidence.\n\n## Hypothesis testing\n\nIn statistics, a hypothesis is a claim about a population parameter. Hypothesis testing is a formal procedure used to decide between two competing claims about a population parameter. These two claims are known as:\n\n- the **null hypothesis**\n- the **alternative hypothesis**\n\nHypothesis testing is a statistical technique that is used to quantify the evidence against a null hypothesis.\n\nThe **null hypothesis**, written H~0~, represents the hypothesis of no difference, no change, no effect. It is often described as the *boring* or *skeptical* hypothesis\n\nThe **alternative hypothesis**, written H~A~, represents the hypothesis of a difference, change or effect.\n\nNote that hypotheses always refer to a **population**, not a sample.\n\n### Example\n\nIn our example, our research question is: do Pima women have the same mean diastolic blood pressure as the general US population?\n\nTo test this research question, we will need a value for the mean diastolic blood pressure of the general US population. We will use the results from a large-scale population survey, and state that the US population has a mean diastolic blood pressure of 71mmHg.\n\nOur hypotheses then, could be written as:\n\n- H~0~: $\\mu = 71$\n- H~A~: $\\mu \\ne 71$\n\nwhere $\\mu$ is the true population mean diastolic blood pressure of Pima women.\n\nThese hypotheses are very formal, and it may be easier to think of them as:\n\n- H~0~: The mean diastolic blood pressure of Pima women is 71 mmHg.\n- H~A~: The mean diastolic blood pressure of Pima women is not 71 mmHg.\n\n## The hypothesis testing framework\n\nThe recommended steps in a hypothesis test are as follows:\n\n0.  Exploratory data analysis\n    - examine distributions, check for missing and/or unusual data\n    - understand the structure of the data (sample size, groups, variables)\n    - based on above, choose an appropriate statistical test\n    - check the assumptions required for the chosen test\n    - frame the research question using the PECO framework:\n      - Population, Exposure, Comparator, Outcome\n1.  Specify the Null and Alternative Hypotheses\n2.  Perform the statistical test, and obtain test statistic, degrees of freedom and P-value\n3.  Calculate descriptive statistics\n4.  Summarise the results including\n    - Summary statistics (overall or by group)\n    - A statement about the evidence\n    - Estimate of effect including:\n      - Direction\n      - Point estimate\n      - 95% confidence interval\n5.  Provide a clear and concise conclusion, written in plain English, that summarises the results of the study in terms of the wider population, not just the sample\n\n## The test statistic\n\nAfter setting up our null and alternative hypotheses, we use the data to generate a test statistic. The particular test statistic differs depending on the type of data being analysed (e.g. continuous or categorical), the study design (e.g. paired or independent) and the question being asked.\n\nThe test statistic is then compared to a known distribution to calculate the probability of observing a test statistic which is as large or larger than the observed test statistic, if the null hypothesis was true. The probability is known as the P-value.\n\n## The P-value\n\nFormally, the P-value is interpreted as the probability of observing data like ours, or more extreme, if the null hypothesis was true.\n\nIf the P-value is small, it is unlikely that we would observe data like ours or more extreme if the null hypothesis was true. In other words, our data are not consistent with the null hypothesis, and we conclude that we have evidence against the null hypothesis. If the P-value is not small, the probability of observing data like ours or more extreme is not unlikely. We therefore have little or no evidence against the null hypothesis. In hypothesis testing, the null hypothesis cannot be proven or accepted; we can only find evidence to refute the null hypothesis.\n\nTo summarise:\n\n- a small P-value gives us evidence against the null hypothesis;\n- a P-value that is not small provides little or no evidence against null hypothesis;\n- the smaller the P-value, the stronger the evidence against the null hypothesis.\n\nHistorically, a value of 0.05 has been used as a cut-point for finding evidence against the null hypothesis. A P-value less than 0.05 would be interpreted as \"statistically significant\", and would allow us to \"reject the null hypothesis\". A P-value greater than 0.05 would be interpreted as \"not significant\", and we would \"fail to reject the null hypothesis\". This arbitrary dichotomy is overly simplistic, and a more nuanced view is now recommended. Recommended interpretations for P-values are given in @tbl-4-1.\n\n\n::: {#tbl-4-1 .cell tbl-cap='Interpretation of P-values'}\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]},\nhline{2}={1-2}{solid, black, 0.05em},\nhline{1}={1-2}{solid, black, 0.08em},\nhline{7}={1-2}{solid, black, 0.08em},\n}                     %% tabularray inner close\nP-value & Strength of evidence \\\\\n<0.001 & Very strong evidence \\\\\n0.001 to <0.01 & Strong evidence \\\\\n0.01 to <0.05 & Evidence \\\\\n0.05 to <0.1 & Weak evidence \\\\\n≥0.1 & Little or no evidence \\\\\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\nP-values are most commonly generated using statistical software, however historically, statistical tables were used to determine the P-value from the test-statistic.\n\n## Effect size\n\nIn hypothesis testing, P-values convey only part of the information about the hypothesis and need to be accompanied by an estimation of the effect size. The effect size describes how different our sample is from the hypothesised population parameter. The effect size depends on the study design and the type of outcome variable being analysed, and should always be presented with a 95% confidence interval (where possible).\n\nIn our blood pressure example, the sample mean and its 95% confidence interval represent the effect size. Alternatively, the difference between the sample mean and the hypothesised mean (and the 95% confidence interval) could be presented.\n\nReporting the effect size enables others to judge whether a result that has evidence of a difference is also a practically important finding. The effect size provides information to help others decide whether the observed effect is large and important enough to warrant a change in current health care practice, is equivocal and suggests a need for further research, or is small and practically unimportant.\n\n## Statistical significance vs practical importance\n\nWhen applying statistical methods in health and medical research, we need to make an informed decision about whether the effect size that led to a statistically significant finding is also practically important (see @fig-practical-importance). The decision about whether a statistically significant result is also practically important depends on expert knowledge, and is best made by others with experience in the field.\n\n\n::: {.cell title='Statistical significance vs. clinical importance (adapted from Armitage P, Berry G, Matthews JNS. (2001))'}\n::: {.cell-output-display}\n![](04-hypothesis-testing_files/figure-pdf/fig-practical-importance-1.pdf){#fig-practical-importance fig-alt='Five vertical confidence interval plots illustrate the distinction between statistical significance and practical importance. A solid horizontal line at zero represents the null hypothesis, while a dashed horizontal line above zero marks the threshold for a clinically or practically important effect. Intervals (a) and (b) lie entirely above zero, indicating statistically significant results; however, only (a) is clearly practically important because the entire interval is above the importance threshold, while (b) includes values of uncertain practical importance. Interval (c) is statistically significant because it does not cross zero, but it lies below the practical importance threshold, indicating a statistically significant yet clinically unimportant effect. Interval (d) crosses zero and spans both harmful and beneficial values, representing a statistically non-significant and inconclusive result. Interval (e) also crosses zero but remains below the practical importance threshold, suggesting a true negative result with no clinically important effect.'}\n:::\n:::\n\n\nIt is possible when conducting significance tests, particularly in very large studies, that a small difference provides strong evidence of an effect due to increased precision from large sample sizes. For example, in a large study of over 1000 patients, a new medication may be found to lower blood pressure by an average of 1 mmHg more than a currently accepted drug, providing strong evidence of a difference (P \\< 0.01). However, such a small reduction in blood pressure would be unlikely to be practically important. The cost and potential side effects of the new medication would need to be weighed against this very small average benefit. In this situation, despite strong statistical evidence, the finding would not be practically important. This is the situation described in scenario (c) of @fig-practical-importance.\n\nConversely, it is possible to obtain a large, practically important difference between groups that provides little evidence of a difference.\n\nFor example, consider a small study to measure the rate of hospital admissions following presentation to the Emergency Department. We may find that 80% of children who present to the Emergency Department are admitted before the intervention, compared to only 65% of children after the intervention. However, the P value may be calculated as 0.38, providing no evidence of a difference. This may be because only a small number of participants were recruited in each period. Here, the reduction in the admission rate by 15% represents a practically important difference, but not statistically significant. This situation is represented in scenario (d) of @fig-practical-importance.\n\nThe important thing to remember is that statistical significance does not always correspond to practical importance. A statistically significant result may be practically unimportant, and a statistically non-significant results may be practically important.\n\n## Errors in significance testing\n\nThere are two conclusions we can draw when conducting a hypothesis test: if the P-value is small, there is strong evidence against the null hypothesis and we reject the null hypothesis. If the P-value is not small, there is little evidence against the null hypothesis and we fail to reject the null hypothesis. As discussed above, the “small” cut-point for the P-value is often taken as 0.05. We refer to this value as $\\alpha$ (alpha).\n\nWe can conduct a thought experiment and compare our hypothesis test conclusion to reality. In reality, either the null hypothesis is true, or it is false. Of course, if we knew what reality was, we would not need to conduct a hypothesis test. But we can compare our possible hypothesis test conclusions to the true (unobserved) reality.\n\nIf the null hypothesis was true in reality, our hypothesis test can fail to reject the null hypothesis – this would be a correct conclusion. However, the hypothesis test could lead us to rejecting the null hypothesis – this would be an incorrect conclusion. We call this scenario a Type I error, and it has a probability of $\\alpha$.\n\nThe other situation is where, in reality, the null hypothesis is false. A correct conclusion would be where our hypothesis test rejects the null hypothesis. However, if our hypothesis test fails to reject the null hypothesis, we have made a Type II error. The probability of making a Type II error is denoted $\\beta$ (beta). We will see in Module 10 that $\\beta$ is determined by the size of the study.\n\nThe error in falsely rejecting the null hypothesis when it is true (type I error), or in falsely accepting the null hypothesis when it is not true (type II error) is summarised in @tbl-mod4-alpha-beta. We will return to these concepts in Module 10, when discussing how to determine the appropriate sample size of a study.\n\n|   | **Effect in reality** | **No effect in reality** |\n|----------------------|:---------------------------:|:-------------------:|\n| **Evidence was found** | Correct: Power ($1 - \\beta$) | Error: $\\alpha$ |\n| **No evidence was found** | Error: $\\beta$ | Correct |\n\n: Comparison of study result with the truth {#tbl-mod4-alpha-beta}\n\n## One-sample t-test\n\nA one-sample t-test tests whether a sample mean is different to a hypothesised value. The t-distribution and its relation to normal distribution has been discussed in detailed in Module 3.\n\nIn a one-sample t-test, a t-value is computed as the sample mean divided by the standard error of the mean. The significance of the t-value is then computed using software, or can be obtained from a statistical table.\n\nThe principles of this test can be used for applications such as testing whether the mean of a sample is different from a known population mean, for example testing whether the IQ of a group of children is different from the population mean of 100 IQ points or testing whether the number of average hours worked in an adult sample is different from the population mean of 38 hours.\n\n### Worked Example\n\nThe mean diastolic blood pressure (BP) of the general US population is known to be 71 mm Hg. The diastolic blood pressure of 733 female Pima indigenous Americans was measured and a density plot showed that the data were approximately normally distributed. The mean diastolic blood pressure in the sample was 72.4 mm Hg with a standard deviation of 12.38 mm Hg.\n\nWe can use jamovi or R to conduct a one sample t-test using the data available (`mod04_blood_pressure.csv`). The results from this test are summarised below.\n\n| n | Mean | Standard deviation | Standard error | 95% confidence interval of the mean |\n|-------------|-------------|-------------|-------------|--------------------|\n| 733 | 72.4 | 12.38 | 0.46 | 71.5 to 73.3 |\n\n: Summary of blood pressure from female Pima indigenous Americans\n\nThe test statistic for the one-sample t-test is calculated as t~732~=3.07, with a P-value of 0.002.\n\nThe mean diastolic blood pressure of females from Pima is estimated as 72.4 mmHg (95% CI: 71.5 to 73.3 mmHg), which is higher than that of the general US population. Note that this interval does not contain the mean of the general US population (71 mm Hg), providing some indication that the mean diastolic blood pressure of female Pima people is higher than that of the general US population.\n\nThe result from the formal hypothesis test gives strong evidence that the mean diastolic BP of the female Pima people is higher than that of the general US population (t~732~=3.07, P=0.002).\n\n## One and two tailed tests\n\nMost statistical tests are two tailed tests, that is, we conduct a test that allows for the summary statistic in the group of interest to be either higher or lower than in the comparison group. For a t-test, this requires that we obtain a two-tailed P value which gives us the probability of the t-value being in either one of the two tails of the t-distribution as shown in @fig-two-tailed-test. The shaded regions show the t values that indicate a P value less than 0.05.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![P-value for a 2-tailed test](img/mod04/two-tailed-test.png){#fig-two-tailed-test fig-alt='A symmetric bell-shaped t-distribution centred at zero. Both tails are shaded beyond the critical values, illustrating the rejection regions for a two-tailed hypothesis test with alpha equal to 0.05.' width=66%}\n:::\n:::\n\n\nOccasionally, one tailed tests are conducted in which the summary statistic in the group of interest can only be higher or lower than the comparison group, i.e. a difference is specified to occur in one direction only. In most studies, two tailed tests of significance are used to allow for the possibility that the effect size could occur in either direction. In clinical trials, this would mean allowing for a result that can indicate a benefit or an adverse effect in response to a new treatment. In epidemiological studies, two tailed tests are used to allow for the fact that exposure to a factor of interest may be adverse or may be beneficial. This conservative approach is usually adopted to prevent missing important effects that occur in the opposite direction to that expected by the researchers.\n\n## A note on P-values displayed by software\n\nYou will often see P-values generated by statistical software presented as 0.000 or 0.0000. As P-values can never be equal to zero, any P-value displayed in this way should be converted to \\<0.001 or \\<0.0001 respectively (i.e. replace the last 0 with a 1, and use the less-than symbol).\n\nR can display P-values in a very cryptic way: $\\text{6.478546e-05}$ for example. This is translated as:\n\n$$\\begin{aligned}\n6.478546e-05 &= 6.478546 \\times 10^{-5} \\\\\n  &= 6.478546 \\times 0.00001 \\\\\n  &= 0.00006478546\n\\end{aligned}$$\n\nSuch a P-value should be presented as P\\<0.0001.\n\n## Decision Tree\n\nIn the following modules in this course, several formal statistical tests will be described to analyse different types of data sets that have been collected to test set null hypotheses. It is important that the correct statistical test is selected to generate P-values and estimate effect size. If an incorrect statistical test is used, the assumptions of the test may be violated, the effect size may be biased and the P value generated may be incorrect.\n\nSelecting the correct test to use in each situation depends on the study design and the nature of the variables collected. Figure 1 in the Appendix shows a decision tree which enables you to decide the type of test to select based on the nature of the data.\n\n## Indigenous data sovereignty and governance: the Australian context\n\nThe issue of data sovereignty was raised in Module 3, and here we will discuss how this concept applies in the Australian context.\n\nIndigenous data encompasses information or knowledge in any format or medium that is about, or may affect, Aboriginal and Torres Strait Islander peoples, either collectively or individually. [@walter_etal21] Indigenous Data Sovereignty specifically refers to the right of Aboriginal and Torres Strait Islander peoples, communities, and organisations to maintain, control, protect, develop, and use data as it relates to them. Data practices must support and enhance Indigenous collective well-being.\n\nIndigenous Data Governance provides the practical mechanisms through which sovereignty is enacted. It consists of formal systems that assert Indigenous data interests regarding how data is accessed and used, ensuring that practices reflect Indigenous priorities, values, culture, and diversity.[@walter_etal21] Importantly, Indigenous Data Sovereignty is practised through Indigenous data governance, making governance the operational expression of sovereignty principles.\n\n### The Problem of Deficit-Based Data Narratives\n\nA major challenge in Australian data collections is that First Nations peoples are often framed as the \"object of study\" rather than as active participants in research. Data frequently focuses on poor outcomes across health, education, and economic participation, creating what has been termed the \"5D data\" narrative: disparity, deprivation, disadvantage, dysfunction, and difference. This approach has been further characterised as BADDR Data: Blaming, Aggregate, Decontextualised, Deficit, and Restricted.[@walter_etal21] Such framings perpetuate harmful stereotypes and fail to capture the strengths, resilience, and diversity of Indigenous communities.\n\n### Key Principles for Indigenous Data Management\n\nIndigenous data management in Australia operates according to several foundational principles. Indigenous data should be reflective of Aboriginal and Torres Strait Islander interests, values, and cultural ways, ensuring cultural appropriateness throughout the data lifecycle. Data must be accessible and appropriate, meeting Indigenous needs rather than serving external agendas. Collection practices must incorporate free, prior, and informed consent, with respect for confidentiality maintained throughout.\n\nSecure storage of Indigenous data is essential, as is the requirement that data be returned to communities in an easily understood and meaningful way. Interpretation of Indigenous data should be conducted by Aboriginal and Torres Strait Islander experts who possess the cultural knowledge necessary for appropriate analysis. Finally, data use must advance self-determination and development, and only proceed in ways that Indigenous peoples agree to.\n\n### FAIR and CARE Principles\n\nThe Australian Open Data infrastructure incorporates FAIR principles (Findable, Accessible, Interoperable, Reusable) for scientific data, which aim to maximise data use and reuse. However, these principles do not mention or address the specific concerns of Indigenous peoples. To address this gap, the CARE Principles for Indigenous Data Governance have been developed to complement FAIR principles.\n\nThe CARE framework consists of four key components:\n\n- Collective Benefit emphasises inclusive development and innovation, improved governance and citizen engagement, and equitable outcomes.\n\n- Authority to Control focuses on recognising Indigenous rights and interests, supporting data for governance, and enabling the governance of data itself.\n\n- Responsibility calls for positive relationships, expanding capability and capacity, and incorporating Indigenous worldviews into data practices.\n\n- Ethics stresses minimising harm and maximising benefit, promoting justice, and careful consideration of future data uses.\n\nThis framework enables the enactment of FAIR principles but with appropriate care and attention to Indigenous rights and interests.[@walter_etal21]\n\n### Protecting Indigenous Data Sovereignty Rights in Research\n\nAboriginal and Torres Strait Islander peoples have the right to decide how Indigenous data is used and stored.[@lowitjainstitute21][@nationalindigenousaustraliansagency24] Formal agreements protecting Indigenous Data Sovereignty should be established at the outset of any research project. Such agreements must cover intellectual property rights, data collection procedures, retention and access arrangements, and management protocols for all data arising from the research. These agreements must also specify actions that Aboriginal and Torres Strait Islander peoples, communities, and organisations can take if commitments are not met. Crucially, these agreements must be clearly understood and formally endorsed by appropriate representatives of the involved Aboriginal and Torres Strait Islander peoples, communities, and organisations.\n\nFirst Nations peoples have the right to lead and participate at all stages of the research process, including planning, data collection, analysis, dissemination of results, return of data, and ongoing access to data. Researchers bear responsibility for providing appropriate information to promote full and effective Indigenous leadership in data collection. They must also provide opportunities for communities to assess data collection, storage, and governance arrangements, including confidentiality protections. Indigenous peoples must have opportunities to engage in the development, design, collection, analysis, and reporting of data, including involvement in the development of appropriate indicators and surveys applicable to local contexts.\n\n{{< pagebreak >}}\n\n# Jamovi notes {.unnumbered}\n\n## One sample t-test\n\nWe will use data from `mod04_blood_pressure.csv` to demonstrate how a one-sample t-test is conducted in Jamovi. To perform the test, go to **Analyses \\> T-Tests \\> One Sample T-Test**.\n\nSelect `dbp` as the **Dependent Variable**. Enter the hypothesised mean as the **Test value** (`71` in this example) as shown below.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](img/mod04/jamovi/mod4-ttest.png){fig-alt='Screenshot of the Jamovi interface showing setup for a one-sample t-test. The variable “dbp” is entered as the dependent variable and the hypothesised mean test value is set to 71. The analysis options panel for conducting a one-sample t-test is displayed.' width=100%}\n:::\n:::\n\n\nThe test statistic (i.e. t and its degrees of freedom) are provided. By default, Jamovi will calculate a P-value for the two-sided test (H~a~: mean $\\neq$ 71), which appropriate for this example.\n\nNote that the one-sample t-test output does not include the mean or the 95% confidence interval of the mean of your variable of interest. This should be obtained using **Exploration \\> Descriptives**:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](img/mod04/jamovi/mod4-ttest-desc.png){fig-alt='Screenshot of Jamovi descriptive statistics output for the variable “dbp”. The table reports the sample size, mean, standard deviation, standard error, and 95% confidence interval for diastolic blood pressure.' width=100%}\n:::\n:::\n\n\n\n{{< pagebreak >}}\n\n# R notes {.unnumbered}\n\n## One sample t-test\n\nWe will use data from `mod04_blood_pressure.csv` to demonstrate how a one-sample t-test is conducted in R. To test whether the mean diastolic blood pressure of the population from which the sample was drawn is equal to 71, we can use the t.test command:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npima <- read.csv(\"data/examples/mod04_blood_pressure.csv\")\nt.test(pima$dbp, mu=71)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  pima$dbp\nt = 3.0725, df = 732, p-value = 0.002202\nalternative hypothesis: true mean is not equal to 71\n95 percent confidence interval:\n 71.50732 73.30305\nsample estimates:\nmean of x \n 72.40518 \n```\n\n\n:::\n:::\n\n\nThe output provides:\n\n- a test statistic (t=3.07);\n- degrees of freedom for the test statistic (df = 732);\n- a P-value from the two-sided test (P=0.002);\n- the mean of the sample (72.4);\n- and the 95% confidence interval of the mean (71.5 to 73.3).\n\n\n\n\n{{< pagebreak >}}\n\n# Activities {.unnumbered}\n\n### Activity 4.1 {-}\n\nIt has been suggested that the average Australian consumes around 8700 kJ per day. A study was conducted to estimate the average dietary consumption of Australian males, aged between 30 and 50. The mean dietary intake was estimated as 9461 kJ, with a 95% confidence interval from 8879 to 10043 kJ. What can you conclude about the dietary consumption of Australian males from this study?\n\n### Activity 4.2 {-}\n\nWomen attending a GP clinic were asked to complete a health survey. Data from 154 responses are saved in `Activity_4.2.csv`. The file contains the following variables:\n\n- id: participant ID number\n- age: age in years\n- height: height in cm\n- weight: weight in kg\n- waist: waist circumference in cm\n\nAustralia’s National Health Survey has estimated the Australian female population has a mean waist circumference of 87.9cm. Analyse the health survey data to compare women attending a GP clinic to the Australian population.\n\n### Activity 4.3 {-}\n\nSetting the significance level at P < 0.10 instead of the more usual P < 0.05 increases the likelihood of:\n\na) a Type I error\nb) a Type II error\nc) rejecting the null hypothesis\nd) not rejecting the null hypothesis \n\n### Activity 4.4 {-}\nFor a fixed sample size setting the significance level at a very extreme cutoff such as P < 0.001 increases the chances of:\n\na) obtaining a significant result\nb) rejecting the null hypothesis\nc) a Type I error\nd) a Type II error\n\n\n",
    "supporting": [
      "04-hypothesis-testing_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}