{
  "hash": "f91f00b3fb690a590b63d2edc7c8e017",
  "result": {
    "engine": "knitr",
    "markdown": "# Categorical data, presentation guidelines and probability distributions\n\n## Learning objectives {.unnumbered}\n\nBy the end of this module you will be able to:\n\n-   Present and report categorical data numerically and graphically\n-   Describe the concept of probability\n-   Describe the characteristics of a binomial distribution\n-   Compute probabilities from a binomial distribution using statistical software\n\n## Optional readings {.unnumbered}\n\n@kirkwood_sterne01; Chapters 3, 14 and 15. [\\[UNSW Library Link\\]](http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728)\n\n@bland15; Chapters 5 and 6. [\\[UNSW Library Link\\]](http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730)\n\nGraphics and statistics for cardiology: designing effective tables for presentation and publication, @boers18 [[UNSW Library Link](https://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=http://dx.doi.org/10.1136/heartjnl-2017-311581)]\n\nGuidelines for Reporting of Figures and Tables for Clinical Research in Urology, @vickers_etal20 [[UNSW Library Link](https://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=http://dx.doi.org/10.1016/j.eururo.2020.04.048)]\n\n## Introduction\n\nIn Module 1, we saw how to summarise continuous data numerically and graphically. In this module, we will show how to summarise categorical data numerically and graphically. We will also introduce the concept of probability which underpins the theoretical basis of statistics, and then introduce the concept of probability distributions. We will present the binomial distribution, which calculates the probability of observing a certain number of events from multiple observations.\n\n## Summarising a single categorical variable numerically\n\nCategorical data are best summarised using a frequency table, where each category is summarised by its frequency: the count of the number of individuals in each category. The **relative frequency** (the frequency expressed as a proportion or percentage of the total frequency) is usually included give further insight.\n\n\n::: {#tbl-1-sex .cell tbl-cap='Sex of participants in PBC study' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_0iwlgxnbvuqhi6vztjr5 = TinyTable.createTableFunctions(\"tinytable_0iwlgxnbvuqhi6vztjr5\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 2 }, { i: '2', j: 3 } ], css_id: 'tinytable_css_8ubnsin0gozvkt13roqs',}, \n          { positions: [ { i: '1', j: 2 }, { i: '1', j: 3 } ], css_id: 'tinytable_css_w1un025ai5viqh7w1a9j',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_op3ak1ssmfry4ahb0tju',}, \n          { positions: [ { i: '2', j: 1 } ], css_id: 'tinytable_css_9tlrd8jh7di19q0zwolm',}, \n          { positions: [ { i: '1', j: 1 } ], css_id: 'tinytable_css_ure9yfi3bk93yetdl4ie',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_8qwxyf0l05qzgxh0mgkh',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_0iwlgxnbvuqhi6vztjr5.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_0iwlgxnbvuqhi6vztjr5 td.tinytable_css_8ubnsin0gozvkt13roqs, #tinytable_0iwlgxnbvuqhi6vztjr5 th.tinytable_css_8ubnsin0gozvkt13roqs {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_0iwlgxnbvuqhi6vztjr5 td.tinytable_css_w1un025ai5viqh7w1a9j, #tinytable_0iwlgxnbvuqhi6vztjr5 th.tinytable_css_w1un025ai5viqh7w1a9j { text-align: center }\n    #tinytable_0iwlgxnbvuqhi6vztjr5 td.tinytable_css_op3ak1ssmfry4ahb0tju, #tinytable_0iwlgxnbvuqhi6vztjr5 th.tinytable_css_op3ak1ssmfry4ahb0tju {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_0iwlgxnbvuqhi6vztjr5 td.tinytable_css_9tlrd8jh7di19q0zwolm, #tinytable_0iwlgxnbvuqhi6vztjr5 th.tinytable_css_9tlrd8jh7di19q0zwolm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_0iwlgxnbvuqhi6vztjr5 td.tinytable_css_ure9yfi3bk93yetdl4ie, #tinytable_0iwlgxnbvuqhi6vztjr5 th.tinytable_css_ure9yfi3bk93yetdl4ie { text-align: left }\n    #tinytable_0iwlgxnbvuqhi6vztjr5 td.tinytable_css_8qwxyf0l05qzgxh0mgkh, #tinytable_0iwlgxnbvuqhi6vztjr5 th.tinytable_css_8qwxyf0l05qzgxh0mgkh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_0iwlgxnbvuqhi6vztjr5\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Sex</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Frequency</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Relative frequency (%)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Male</td>\n                  <td data-row=\"1\" data-col=\"2\">44</td>\n                  <td data-row=\"1\" data-col=\"3\">10.5</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Female</td>\n                  <td data-row=\"2\" data-col=\"2\">374</td>\n                  <td data-row=\"2\" data-col=\"3\">89.5</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nIt is sometimes useful to present the cumulative relative frequency, which shows the relative frequency of individuals in a certain category or below (for example, @tbl-1-stage).\n\n\n::: {#tbl-1-stage .cell tbl-cap='Stage of disease for participants in PBC study' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_puqumirhyl2v9x7n4qhv = TinyTable.createTableFunctions(\"tinytable_puqumirhyl2v9x7n4qhv\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 2 }, { i: '4', j: 3 }, { i: '4', j: 4 } ], css_id: 'tinytable_css_lw4bbp0ynck5k196rl6e',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 } ], css_id: 'tinytable_css_q1tzwvja5pgt9rowlccg',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_10oxtfsv49n977dbzgbp',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_ljk7wutktvvyfu06lf2h',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 } ], css_id: 'tinytable_css_2sz1w3kxna3zy76z90o0',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_qmpstupd5jn6e6mvptka',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_puqumirhyl2v9x7n4qhv.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_puqumirhyl2v9x7n4qhv td.tinytable_css_lw4bbp0ynck5k196rl6e, #tinytable_puqumirhyl2v9x7n4qhv th.tinytable_css_lw4bbp0ynck5k196rl6e {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_puqumirhyl2v9x7n4qhv td.tinytable_css_q1tzwvja5pgt9rowlccg, #tinytable_puqumirhyl2v9x7n4qhv th.tinytable_css_q1tzwvja5pgt9rowlccg { text-align: center }\n    #tinytable_puqumirhyl2v9x7n4qhv td.tinytable_css_10oxtfsv49n977dbzgbp, #tinytable_puqumirhyl2v9x7n4qhv th.tinytable_css_10oxtfsv49n977dbzgbp {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_puqumirhyl2v9x7n4qhv td.tinytable_css_ljk7wutktvvyfu06lf2h, #tinytable_puqumirhyl2v9x7n4qhv th.tinytable_css_ljk7wutktvvyfu06lf2h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_puqumirhyl2v9x7n4qhv td.tinytable_css_2sz1w3kxna3zy76z90o0, #tinytable_puqumirhyl2v9x7n4qhv th.tinytable_css_2sz1w3kxna3zy76z90o0 { text-align: left }\n    #tinytable_puqumirhyl2v9x7n4qhv td.tinytable_css_qmpstupd5jn6e6mvptka, #tinytable_puqumirhyl2v9x7n4qhv th.tinytable_css_qmpstupd5jn6e6mvptka {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_puqumirhyl2v9x7n4qhv\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Stage of disease</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Frequency</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Relative frequency (%)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Cumulative relative frequency (%)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Stage 1</td>\n                  <td data-row=\"1\" data-col=\"2\">21</td>\n                  <td data-row=\"1\" data-col=\"3\">5.1</td>\n                  <td data-row=\"1\" data-col=\"4\">5.1</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Stage 2</td>\n                  <td data-row=\"2\" data-col=\"2\">92</td>\n                  <td data-row=\"2\" data-col=\"3\">22.3</td>\n                  <td data-row=\"2\" data-col=\"4\">27.4</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Stage 3</td>\n                  <td data-row=\"3\" data-col=\"2\">155</td>\n                  <td data-row=\"3\" data-col=\"3\">37.6</td>\n                  <td data-row=\"3\" data-col=\"4\">65.0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">Stage 4</td>\n                  <td data-row=\"4\" data-col=\"2\">144</td>\n                  <td data-row=\"4\" data-col=\"3\">35.0</td>\n                  <td data-row=\"4\" data-col=\"4\">100.0</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nFrom @tbl-1-stage, we can see that 65.0% of participants had Stage 3 disease or lower.\n\n## Summarising a single categorical variable graphically\n\nA categorical variable is best summarised graphically using a **bar chart**. For example, we can present the distribution of Stage of Disease graphically using a bar graph (@fig-bar-1). Bar graphs, which are suitable for plotting discrete or categorical variables, are defined by the fact that the bars do not touch.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Bar graph of stage of disease from PBC study](img/mod01/pbc-bar.png){#fig-bar-1 fig-pos='H' width=75%}\n:::\n:::\n\n\nPie charts can be an alternative way to summarise a categorical variable graphically, however their use is not recommended for the following reasons:\n\n-   Not ideal when there are many categories to compare\n-   The use of percentages is not appropriate when the sample size is small\n-   Can be misleading by using different size pies, different rotations and different colours to draw attention to specific groups\n-   3D and exploding bar charts further distort the effect of perspective and may confuse the reader\n\nPie charts will not be discussed further in this course.\n\n## Exploratory data analysis for categorical data {#sec-eda-cat}\n\nAs with continuous data, it is good practice to undertake exploratory data analysis before formally analysing categorical data. You should take a moment and examine a frequency table for categorical variables, to ensure all recorded values are within scope.\n\n## Summarising two categorical variables numerically\n\nSo far, we have discussed one-way frequency tables, that is, tables that summarise one variable. We can summarise more than two categorical variables in a table – called a cross tabulation, or a two-way (summarising two variables) table.\n\nUsing our PBC data, we can summarise the two categorical variables: sex and stage of disease. The two-way table of frequencies is shown in @tbl-1-sex-stage-freq.\n\n\n::: {#tbl-1-sex-stage-freq .cell tbl-cap='Frequency of participants by sex and stage of disease*' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_tymopbisbu4uduisywkf = TinyTable.createTableFunctions(\"tinytable_tymopbisbu4uduisywkf\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 3 }, { i: '3', j: 4 }, { i: '3', j: 5 }, { i: '3', j: 6 }, { i: '3', j: 7 } ], css_id: 'tinytable_css_zdwukasmt3mcxq9wmv0j',}, \n          { positions: [ { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '1', j: 7 }, { i: '2', j: 7 } ], css_id: 'tinytable_css_zmaw16sqm23nxgmj7r9q',}, \n          { positions: [ { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_jnfzu5jyzk2ussde2sdy',}, \n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 } ], css_id: 'tinytable_css_txxsfw0qbskpe5af4opv',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 } ], css_id: 'tinytable_css_8jbqdtwlelpii6qg4zy4',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_256id5o3a2rmy9zloua8',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_tymopbisbu4uduisywkf.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_tymopbisbu4uduisywkf td.tinytable_css_zdwukasmt3mcxq9wmv0j, #tinytable_tymopbisbu4uduisywkf th.tinytable_css_zdwukasmt3mcxq9wmv0j {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: right }\n    #tinytable_tymopbisbu4uduisywkf td.tinytable_css_zmaw16sqm23nxgmj7r9q, #tinytable_tymopbisbu4uduisywkf th.tinytable_css_zmaw16sqm23nxgmj7r9q { text-align: right }\n    #tinytable_tymopbisbu4uduisywkf td.tinytable_css_jnfzu5jyzk2ussde2sdy, #tinytable_tymopbisbu4uduisywkf th.tinytable_css_jnfzu5jyzk2ussde2sdy {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: right }\n    #tinytable_tymopbisbu4uduisywkf td.tinytable_css_txxsfw0qbskpe5af4opv, #tinytable_tymopbisbu4uduisywkf th.tinytable_css_txxsfw0qbskpe5af4opv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_tymopbisbu4uduisywkf td.tinytable_css_8jbqdtwlelpii6qg4zy4, #tinytable_tymopbisbu4uduisywkf th.tinytable_css_8jbqdtwlelpii6qg4zy4 { text-align: left }\n    #tinytable_tymopbisbu4uduisywkf td.tinytable_css_256id5o3a2rmy9zloua8, #tinytable_tymopbisbu4uduisywkf th.tinytable_css_256id5o3a2rmy9zloua8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_tymopbisbu4uduisywkf\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Sex</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Stage 1</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Stage 2</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Stage 3</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Stage 4</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">All</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='7'>* Stage of disease was missing for 6 participants</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Male</td>\n                  <td data-row=\"1\" data-col=\"2\">Count</td>\n                  <td data-row=\"1\" data-col=\"3\">3</td>\n                  <td data-row=\"1\" data-col=\"4\">8</td>\n                  <td data-row=\"1\" data-col=\"5\">16</td>\n                  <td data-row=\"1\" data-col=\"6\">17</td>\n                  <td data-row=\"1\" data-col=\"7\">44</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Female</td>\n                  <td data-row=\"2\" data-col=\"2\">Count</td>\n                  <td data-row=\"2\" data-col=\"3\">18</td>\n                  <td data-row=\"2\" data-col=\"4\">84</td>\n                  <td data-row=\"2\" data-col=\"5\">139</td>\n                  <td data-row=\"2\" data-col=\"6\">127</td>\n                  <td data-row=\"2\" data-col=\"7\">374</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">All</td>\n                  <td data-row=\"3\" data-col=\"2\">Count</td>\n                  <td data-row=\"3\" data-col=\"3\">21</td>\n                  <td data-row=\"3\" data-col=\"4\">92</td>\n                  <td data-row=\"3\" data-col=\"5\">155</td>\n                  <td data-row=\"3\" data-col=\"6\">144</td>\n                  <td data-row=\"3\" data-col=\"7\">418</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nWe can add percentages to two-way tables as either *column* or *row* percents. Using @tbl-1-sex-stage-freq as an example, column percents represent the relative frequencies of sex within each stage (@tbl-1-sex-stage-col).\n\n\n::: {#tbl-1-sex-stage-col .cell tbl-cap='Frequency of participants by sex and stage of disease*, including column percents' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_ijd71mjaxcfc8d9i72zz = TinyTable.createTableFunctions(\"tinytable_ijd71mjaxcfc8d9i72zz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 1 }, { i: '6', j: 2 }, { i: '6', j: 3 }, { i: '6', j: 4 }, { i: '6', j: 5 }, { i: '6', j: 6 } ], css_id: 'tinytable_css_f9s3ojri85wrv91xehky',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_865mfjbvsx970rx5efyt',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_ijd71mjaxcfc8d9i72zz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_ijd71mjaxcfc8d9i72zz td.tinytable_css_f9s3ojri85wrv91xehky, #tinytable_ijd71mjaxcfc8d9i72zz th.tinytable_css_f9s3ojri85wrv91xehky {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_ijd71mjaxcfc8d9i72zz td.tinytable_css_865mfjbvsx970rx5efyt, #tinytable_ijd71mjaxcfc8d9i72zz th.tinytable_css_865mfjbvsx970rx5efyt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_ijd71mjaxcfc8d9i72zz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Sex</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Stage 1</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Stage 2</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Stage 3</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Stage 4</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='6'>* Stage of disease was missing for 6 participants</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Male</td>\n                  <td data-row=\"1\" data-col=\"2\">Count</td>\n                  <td data-row=\"1\" data-col=\"3\">3</td>\n                  <td data-row=\"1\" data-col=\"4\">8</td>\n                  <td data-row=\"1\" data-col=\"5\">16</td>\n                  <td data-row=\"1\" data-col=\"6\">17</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">Column percent</td>\n                  <td data-row=\"2\" data-col=\"3\">14.3</td>\n                  <td data-row=\"2\" data-col=\"4\">8.7</td>\n                  <td data-row=\"2\" data-col=\"5\">10.3</td>\n                  <td data-row=\"2\" data-col=\"6\">11.8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Female</td>\n                  <td data-row=\"3\" data-col=\"2\">Count</td>\n                  <td data-row=\"3\" data-col=\"3\">18</td>\n                  <td data-row=\"3\" data-col=\"4\">84</td>\n                  <td data-row=\"3\" data-col=\"5\">139</td>\n                  <td data-row=\"3\" data-col=\"6\">127</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">Column percent</td>\n                  <td data-row=\"4\" data-col=\"3\">85.7</td>\n                  <td data-row=\"4\" data-col=\"4\">91.3</td>\n                  <td data-row=\"4\" data-col=\"5\">89.7</td>\n                  <td data-row=\"4\" data-col=\"6\">88.2</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">All</td>\n                  <td data-row=\"5\" data-col=\"2\">Count</td>\n                  <td data-row=\"5\" data-col=\"3\">21</td>\n                  <td data-row=\"5\" data-col=\"4\">92</td>\n                  <td data-row=\"5\" data-col=\"5\">155</td>\n                  <td data-row=\"5\" data-col=\"6\">144</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">Column percent</td>\n                  <td data-row=\"6\" data-col=\"3\">100.0</td>\n                  <td data-row=\"6\" data-col=\"4\">100.0</td>\n                  <td data-row=\"6\" data-col=\"5\">100.0</td>\n                  <td data-row=\"6\" data-col=\"6\">100.0</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nConversely, row percents represent the relative frequencies of stage within each sex (@tbl-1-sex-stage-row).\n\n\n::: {#tbl-1-sex-stage-row .cell tbl-cap='Frequency of participants by sex and stage of disease*, including row percents' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_ejodlniny0texumokjpo = TinyTable.createTableFunctions(\"tinytable_ejodlniny0texumokjpo\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 1 }, { i: '6', j: 2 }, { i: '6', j: 3 }, { i: '6', j: 4 }, { i: '6', j: 5 }, { i: '6', j: 6 }, { i: '6', j: 7 } ], css_id: 'tinytable_css_mjtpmd433htoys4tzbh0',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_71amr90bhsxepcz6l42c',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_ejodlniny0texumokjpo.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_ejodlniny0texumokjpo td.tinytable_css_mjtpmd433htoys4tzbh0, #tinytable_ejodlniny0texumokjpo th.tinytable_css_mjtpmd433htoys4tzbh0 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_ejodlniny0texumokjpo td.tinytable_css_71amr90bhsxepcz6l42c, #tinytable_ejodlniny0texumokjpo th.tinytable_css_71amr90bhsxepcz6l42c {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_ejodlniny0texumokjpo\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Sex</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Stage 1</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Stage 2</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Stage 3</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Stage 4</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">All</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='7'>* Stage of disease was missing for 6 participants</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Male</td>\n                  <td data-row=\"1\" data-col=\"2\">Count</td>\n                  <td data-row=\"1\" data-col=\"3\">3</td>\n                  <td data-row=\"1\" data-col=\"4\">8</td>\n                  <td data-row=\"1\" data-col=\"5\">16</td>\n                  <td data-row=\"1\" data-col=\"6\">17</td>\n                  <td data-row=\"1\" data-col=\"7\">44</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">Row percent</td>\n                  <td data-row=\"2\" data-col=\"3\">6.8</td>\n                  <td data-row=\"2\" data-col=\"4\">18.2</td>\n                  <td data-row=\"2\" data-col=\"5\">36.4</td>\n                  <td data-row=\"2\" data-col=\"6\">38.6</td>\n                  <td data-row=\"2\" data-col=\"7\">100.0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Female</td>\n                  <td data-row=\"3\" data-col=\"2\">Count</td>\n                  <td data-row=\"3\" data-col=\"3\">18</td>\n                  <td data-row=\"3\" data-col=\"4\">84</td>\n                  <td data-row=\"3\" data-col=\"5\">139</td>\n                  <td data-row=\"3\" data-col=\"6\">127</td>\n                  <td data-row=\"3\" data-col=\"7\">374</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">Row percent</td>\n                  <td data-row=\"4\" data-col=\"3\">4.8</td>\n                  <td data-row=\"4\" data-col=\"4\">22.5</td>\n                  <td data-row=\"4\" data-col=\"5\">37.2</td>\n                  <td data-row=\"4\" data-col=\"6\">34.0</td>\n                  <td data-row=\"4\" data-col=\"7\">100.0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">All</td>\n                  <td data-row=\"5\" data-col=\"2\">Count</td>\n                  <td data-row=\"5\" data-col=\"3\">21</td>\n                  <td data-row=\"5\" data-col=\"4\">92</td>\n                  <td data-row=\"5\" data-col=\"5\">155</td>\n                  <td data-row=\"5\" data-col=\"6\">144</td>\n                  <td data-row=\"5\" data-col=\"7\">418</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">Row percent</td>\n                  <td data-row=\"6\" data-col=\"3\">5.0</td>\n                  <td data-row=\"6\" data-col=\"4\">22.0</td>\n                  <td data-row=\"6\" data-col=\"5\">37.1</td>\n                  <td data-row=\"6\" data-col=\"6\">34.4</td>\n                  <td data-row=\"6\" data-col=\"7\">100.0</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\\newpage\n\n### Tables containing more than two variables\n\nIt is possible to construct multi-way tables that summarise more than two categorical variables in a single table. However, tables can become complex when more than two variables are incorporated, and you may need to present the information as two tables or incorporate additional rows and columns.\n\nIn @fig-1-2, characteristics of the sample of prisoners from the NPHDC were presented. This table contains information about sex, age group and Indigenous status from different groups of prisoners; prison entrants, discharges, and prisoners in custody. This type of condensed information is often found in reports and journal articles giving demographic information, by different groups considered in the study.\n\n![](img/mod01/prisoner-health.png){#fig-1-2}\n\nWe might also consider a table containing further pieces of information. The table presented in @fig-prison-education (from the health of Australia’s prisoners 2015 report) compares prison entrants and the general community by three variables: age group, Indigenous status, and highest level of completed education.\n\nCan you see any issues with the presentation of this table?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Highest level of completed education in prison entrants and the general community](img/mod01/prisoner-education.png){#fig-prison-education fig-pos='H' width=66%}\n:::\n:::\n\n\nSource: Australian Institute of Health and Welfare 2015. The health of Australia’s prisoners 2015. Cat. no. PHE 207. Canberra: AIHW.\n\nSome issues in this table:\n\n-   The title of the table does not contain full information about the variables in the table;\n-   It is unclear how the percentages were calculated (which groupings added to 100%);\n-   The ages are not labelled as such, thus without reading the text in report it is unclear that these are age groupings.\n\n## Summarising two categorical variables graphically {#sec-two-catvar-graph}\n\nInformation from more than one variable can be presented as clustered or multiple bar chart (bars side-by-side) (@fig-bar-2). This type of graph is useful when examining changes in the categories separately, but also comparing the grouping variable between the main bar variable. Here we can see that Stage 3 and Stage 4 disease is the most common for both males and females, but there are many more females within each stage of disease.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Bar graph of stage of disease by sex from PBC study](img/mod02/pbc-bar-stage-sex.png){#fig-bar-2 fig-pos='H' width=75%}\n:::\n:::\n\n\nAn alternative bar graph is a stacked or composite bar graph, which retains the overall height for each category, but differentiates the bars by another variable (@fig-bar-3).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Stacked bar graph of stage of disease by sex from PBC study](img/mod02/pbc-bar-stage-sex-stacked.png){#fig-bar-3 fig-pos='H' width=75%}\n:::\n:::\n\n\nFinally, a stacked relative bar chart (@fig-bar-4) displays the proportion of grouping variable for each bar, where each overall bar represents 100%. These graphs allow the reader to compare the proportions between categories. We can easily see from @fig-bar-4 that the distribution of sex is similar across each stage of disease.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relative frequency of sex within stage of disease from PBC study](img/mod02/pbc-bar-stage-sex-stacked-relative.png){#fig-bar-4 fig-pos='H' width=75%}\n:::\n:::\n\n\n## Presentation guidelines\n\n### Guidelines for presenting summary statistics\n\nWhen reporting summary statistics, it is important not to present results with too many decimal places. Doing so implies that your data have a higher level of precision than they do. For example, presenting a mean blood pressure of 100.2487 mmHg implies that blood pressure can be measured accurately to at least three decimal places.\n\nThere are a number of guidelines that have been written to help in the presentation of numerical data. Many of these guidelines are based on the number of decimal places, while others are based on the number of significant figures. Briefly, the number of significant figures are \"the number of digits from the first non-zero digit to the last meaningful digit, irrespective of the position of the decimal point. Thus, 1.002, 10.02, 100200 (if this number is expressed to the nearest 100) all have four significant digits.\" @armitage_etal13\n\nA summary of these guidelines that will be used in this course appear in @tbl-1-pres.\n\n{{< pagebreak >}}\n\n\n::: {#tbl-1-pres .cell tbl-cap='Guidelines for presentation of statistical results'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_s5xj8wn96gnlgmh2zmvo = TinyTable.createTableFunctions(\"tinytable_s5xj8wn96gnlgmh2zmvo\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '15', j: 2 } ], css_id: 'tinytable_css_e5pwicsuwufs5gaeimoh',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 } ], css_id: 'tinytable_css_oyql75cpk6dq6iqgjbnm',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_xjloz3tgemfovyng2adb',}, \n          { positions: [ { i: '15', j: 1 } ], css_id: 'tinytable_css_22kjmsv7s6hfrug27va5',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 } ], css_id: 'tinytable_css_c9pgnzxps5rhte4yliar',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_nn7qaen2hy153zdnej7k',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_s5xj8wn96gnlgmh2zmvo.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_s5xj8wn96gnlgmh2zmvo td.tinytable_css_e5pwicsuwufs5gaeimoh, #tinytable_s5xj8wn96gnlgmh2zmvo th.tinytable_css_e5pwicsuwufs5gaeimoh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; width: 71%; }\n    #tinytable_s5xj8wn96gnlgmh2zmvo td.tinytable_css_oyql75cpk6dq6iqgjbnm, #tinytable_s5xj8wn96gnlgmh2zmvo th.tinytable_css_oyql75cpk6dq6iqgjbnm { width: 71%; }\n    #tinytable_s5xj8wn96gnlgmh2zmvo td.tinytable_css_xjloz3tgemfovyng2adb, #tinytable_s5xj8wn96gnlgmh2zmvo th.tinytable_css_xjloz3tgemfovyng2adb {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; width: 71%; }\n    #tinytable_s5xj8wn96gnlgmh2zmvo td.tinytable_css_22kjmsv7s6hfrug27va5, #tinytable_s5xj8wn96gnlgmh2zmvo th.tinytable_css_22kjmsv7s6hfrug27va5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; width: 29%; }\n    #tinytable_s5xj8wn96gnlgmh2zmvo td.tinytable_css_c9pgnzxps5rhte4yliar, #tinytable_s5xj8wn96gnlgmh2zmvo th.tinytable_css_c9pgnzxps5rhte4yliar { width: 29%; }\n    #tinytable_s5xj8wn96gnlgmh2zmvo td.tinytable_css_nn7qaen2hy153zdnej7k, #tinytable_s5xj8wn96gnlgmh2zmvo th.tinytable_css_nn7qaen2hy153zdnej7k {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; width: 29%; }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_s5xj8wn96gnlgmh2zmvo\" style=\"table-layout: fixed; width: 100%; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Summary statistic</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Guideline (reference)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>Sources: Altman (1990), Cole (2015), Assel et al. (2019)</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Mean</td>\n                  <td data-row=\"1\" data-col=\"2\">It is usually appropriate to quote the mean to one extra decimal place compared with the raw data. (Altman)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Median, Interquartile range, Range</td>\n                  <td data-row=\"2\" data-col=\"2\">As medians, interquartile ranges and ranges are based on individual data points, these values should be presented with the same precision as the original data.</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Percentage</td>\n                  <td data-row=\"3\" data-col=\"2\">Percentages do not need to be given with more than one decimal place at most. When the sample size is less than 100, no decimal places should be given. (Altman)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">Probability</td>\n                  <td data-row=\"4\" data-col=\"2\">It is acceptable to present probabilities to 2 or 3 decimal places. If the probability is presented as a percentage, present the percentage with 0 or 1 decimal place.</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Standard deviation</td>\n                  <td data-row=\"5\" data-col=\"2\">The standard deviation should usually be given to the same accuracy as the mean, or with one extra decimal place. (Altman)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">Standard error</td>\n                  <td data-row=\"6\" data-col=\"2\">As per standard deviation</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Confidence interval</td>\n                  <td data-row=\"7\" data-col=\"2\">Use the same rule as for the corresponding effect size (be it mean, percentage, mean difference, regression coefficient, correlation coefficient or risk ratio) (Cole)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">Test statistic</td>\n                  <td data-row=\"8\" data-col=\"2\">Test statistics should not be presented with more than two decimal places.</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Degrees of freedom</td>\n                  <td data-row=\"9\" data-col=\"2\">Most degrees of freedom are whole numbers, and should be presented as such. If a test statistic has degrees of freedom with decimal places (the Welch t-statistic for example), present only one decimal place.</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">P-value</td>\n                  <td data-row=\"10\" data-col=\"2\">Report P-values to a single significant figure unless the P-value is close to 0.05 (say, 0.01 to 0.2), in which case, report two significant figures. Do not report `not significant` for P-values of 0.05 or higher. Very low P-values can be reported as P < 0.001 or P < 0.0001. A P-value can indeed be 1, although some investigators prefer to report this as >0.9. (Based on Assel)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Difference in means</td>\n                  <td data-row=\"11\" data-col=\"2\">As for the estimated means</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">Difference in proportions</td>\n                  <td data-row=\"12\" data-col=\"2\">As for the estimated proportions</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">Odds ratio / Relative risk</td>\n                  <td data-row=\"13\" data-col=\"2\">Hazard and odds ratios are normally reported to two decimal places, although this can be avoided for high odds ratios (Assel)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\">Correlation coefficient</td>\n                  <td data-row=\"14\" data-col=\"2\">One or two decimal places, or more when very close to ±1   (Cole)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Regression coefficient</td>\n                  <td data-row=\"15\" data-col=\"2\">Use one more significant figure than the underlying data   (adapted from Cole)</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n### Table presentation guidelines\n\nConsider the following guidelines for the appropriate presentation of tables in scientific journals and reports (Woodward, 2013).\n\n1.  Each table (and figure) should be self-explanatory, i.e. the reader should be able to understand it without reference to the text in the body of the report.\n    -   This can be achieved by using complete, meaningful labels for the rows and columns and giving a complete, meaningful title.\n    -   Footnotes can be used to enhance the explanation.\n2.  Units of the variables (and if needed, method of calculation or derivation) should be given and missing records should be noted (e.g. in a footnote).\n3.  A table should be visually uncluttered.\n    -   Avoid use of vertical lines.\n    -   Horizontal lines should not be used in every single row, but they can be used to group parts of the table.\n    -   Sensible use of white space also helps enormously; use equal spacing except where large spaces are left to separate distinct parts of the table.\n    -   Different typefaces (or fonts) may be used to provide discrimination, e.g. use of bold type and/or italics.\n4.  The rows and columns of each table should be arranged in a natural order to help interpretation. For instance, when rows are ordered by the size of the numbers they contain for a nominal variable, it is immediately obvious where relatively big and small contributions come from.\n5.  Tables should have a consistent appearance throughout the report so that the paper is easy to follow (and also for an aesthetic appearance). Conventions for labelling and ordering should be the same (for both tables as well as figures) for ease of comparison of different tables (and figures).\n6.  Consider if there is a particular table orientation that makes a table easier to read.\n\nGiven the different possible formats of tables and their complexity, some further guidelines are given in the following excellent references:\n\n-   Graphics and statistics for cardiology: designing effective tables for presentation and publication, @boers18\n-   Guidelines for Reporting of Figures and Tables for Clinical Research in Urology, @vickers_etal20\n\n### Graphical presentation guidelines\n\nConsider the following guidelines for the appropriate presentation of graphs in scientific journals and reports (Woodward, 2013).\n\n-   Figures should be self-explanatory and have consistent appearance through the report.\n-   A title should give complete information. Note that figure titles are usually placed below the figure, whereas for tables titles are given above the table.\n-   Axes should be labelled appropriately\n-   Units of the variables should be given in the labelling of the axes. Use footnotes to indicate any calculation or derivation of variables and to indicate missing values\n-   If the Y-axis has a natural origin, it should be included, or emphasised if it is not included.\n-   If graphs are being compared, the Y-axis should be the same across the graphs to enable fair comparison\n-   Columns of bar charts should be separated by a space\n-   Three dimensional graphs should be avoided unless the third dimension adds additional information\n\n## Probability\n\nProbability is defined as:\n\n> the chance of an event occurring, where an event is the result of an observation or experiment, or the description of some potential outcome.\n\nProbabilities range from 0 (where the event will never occur) to 1 (where the event will always occur). For example, tossing a coin is an experiment; one event is the coin landing with head up, while the other event is the coin landing tails up. The set of all possible outcomes in an experiment is called the sample space. For example, by tossing a coin you can get either a head or a tail (called mutually exclusive events); and by rolling a die you can get any of the six sides. Thus, for a die the sampling space is: S = {1, 2, 3, 4, 5, 6}\n\nWith a fair (unbiased) die, the probability of each outcome occurring is 1/6 and its probability distribution is simply a probability of 1/6 for each of the six numbers on a die.\n\n### Additive law of probability\n\nHow do we work out the probability that one roll of a die will turn out to be a 3 or a 6? To do that, we first need to work out whether the events (3 or 6 on the roll of a die) are mutually exclusive. Events are mutually exclusive if they are events which cannot occur at the same time. For example, rolling a die once and getting a 3 and 6 are mutually exclusive events (you can roll one or the other but not both in a single roll).\n\nTo obtain the probability of one or the other of two mutually exclusive events occurring, the sum of the probabilities of each is taken. For example, the probability of the roll of a die being a 3 or a 6 is the sum of the probability of the die being 3 (i.e. 1/6) and the probability of the die being 6 (also 1/6). With a fair die:\n\nProbability of a die roll being 3 or 6 = $1/6 + 1/6 = 1/3$\n\nAnother way of putting it is:\n\nP(die roll =3 or die roll =6) = P(die roll=3) + P(die roll=6) = $1/6 + 1/6 = 1/3$\n\n#### Example: Additive law for mutually exclusive events {.unnumbered}\n\nConsider that blood type can be organised into the ABO system (blood types A, B, AB or O) An individual may only have one blood type.\n\nUsing the information from https://www.donateblood.com.au/learn/about-blood let’s consider the ABO blood type system. The frequency distribution (prevalence) of the ABO blood type system in the population represents the probability of each of the outcomes. If we consider all possible blood type outcomes, then the total of the probabilities will sum to 1 (100%).\n\n\n::: {#tbl-2-1 .cell tbl-cap='Frequency of blood types' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_7kxc6c2gpoaeo1q4z40u = TinyTable.createTableFunctions(\"tinytable_7kxc6c2gpoaeo1q4z40u\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '5', j: 1 }, { i: '5', j: 2 }, { i: '5', j: 3 } ], css_id: 'tinytable_css_p42a4tgbo05s6rvvzj6e',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_6gt7jp26uy9j3vp2rjcn',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_7kxc6c2gpoaeo1q4z40u.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_7kxc6c2gpoaeo1q4z40u td.tinytable_css_p42a4tgbo05s6rvvzj6e, #tinytable_7kxc6c2gpoaeo1q4z40u th.tinytable_css_p42a4tgbo05s6rvvzj6e {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_7kxc6c2gpoaeo1q4z40u td.tinytable_css_6gt7jp26uy9j3vp2rjcn, #tinytable_7kxc6c2gpoaeo1q4z40u th.tinytable_css_6gt7jp26uy9j3vp2rjcn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_7kxc6c2gpoaeo1q4z40u\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Blood Type</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">% of population</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Probability</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">A</td>\n                  <td data-row=\"1\" data-col=\"2\">38%</td>\n                  <td data-row=\"1\" data-col=\"3\">0.38</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">B</td>\n                  <td data-row=\"2\" data-col=\"2\">10%</td>\n                  <td data-row=\"2\" data-col=\"3\">0.10</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">AB</td>\n                  <td data-row=\"3\" data-col=\"2\">3%</td>\n                  <td data-row=\"3\" data-col=\"3\">0.03</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">O</td>\n                  <td data-row=\"4\" data-col=\"2\">49%</td>\n                  <td data-row=\"4\" data-col=\"3\">0.49</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Total</td>\n                  <td data-row=\"5\" data-col=\"2\">100%</td>\n                  <td data-row=\"5\" data-col=\"3\">1.00</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nIn this example we consider: What is the probability that an individual will have either blood group O or A?\n\nSince blood type is mutually exclusive, the probability that either one or the other occurs is the sum of the individual probabilities. These are mutually exclusive events so we can say P(O or A) = P(O) + P(A)\n\nThus, the answer is: P(Blood type O) + P(Blood type A) = 0.49 + 0.38 = 0.87\n\n### Multiplicative law of probability\n\nThe additive law of probability lets us consider the probability of different outcomes in a single experiment. The multiplicative law lets us consider the probability of multiple events occurring in a particular order. For example: if I roll a die twice, what is the probability of rolling a 3 and *then* a 6?\n\nThese events are independent: the probability of rolling a 6 on the second roll is not affected by the first roll.\n\nThe multiplicative law of probability states:\n\n> If A and B are independent, then P(A and B) = P(A) $\\times$ P(B).\n\nSo, the probability of rolling a 3 and then a 6 is: P(3 and 6) = $1/6 \\times 1/6 = 1/36$.\n\nNote here that the order matters – we are considering the probability of rolling a 3 and then a 6, not the probability of rolling a 6 and then a 3.\n\n## Probability distributions\n\n> A probability distribution is a table or a function that provides the probabilities of all possible outcomes for a random event.\n\nFor example, the probability distribution for a single coin toss is straightforward: the probability of obtaining a head is 0.5, and the probability of obtaining a tail is 0.5, and this can be summarised in @tbl-coin.\n\n\n::: {#tbl-coin .cell tbl-cap='Probability distribution for a single coin toss' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_trlf00tm22hlras5jlqk = TinyTable.createTableFunctions(\"tinytable_trlf00tm22hlras5jlqk\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 } ], css_id: 'tinytable_css_1mj46bgwhagwr91ms83i',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_dd1y59khh3zy6t9y4f70',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_trlf00tm22hlras5jlqk.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_trlf00tm22hlras5jlqk td.tinytable_css_1mj46bgwhagwr91ms83i, #tinytable_trlf00tm22hlras5jlqk th.tinytable_css_1mj46bgwhagwr91ms83i {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_trlf00tm22hlras5jlqk td.tinytable_css_dd1y59khh3zy6t9y4f70, #tinytable_trlf00tm22hlras5jlqk th.tinytable_css_dd1y59khh3zy6t9y4f70 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_trlf00tm22hlras5jlqk\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Coin face</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Probability</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Heads</td>\n                  <td data-row=\"1\" data-col=\"2\">0.5</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Tails</td>\n                  <td data-row=\"2\" data-col=\"2\">0.5</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nSimilarly, the probability distribution for a single roll of a die is straightforward: each face has a probability of 1/6 (@tbl-die).\n\n\n::: {#tbl-die .cell tbl-cap='Probability distributions for a single roll of a die' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_9jz56xtlqeggkfwegxt1 = TinyTable.createTableFunctions(\"tinytable_9jz56xtlqeggkfwegxt1\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 1 }, { i: '6', j: 2 } ], css_id: 'tinytable_css_z409elx7jbs2wk614tz5',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_zrso9ksyj6udnadpfa2p',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_9jz56xtlqeggkfwegxt1.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_9jz56xtlqeggkfwegxt1 td.tinytable_css_z409elx7jbs2wk614tz5, #tinytable_9jz56xtlqeggkfwegxt1 th.tinytable_css_z409elx7jbs2wk614tz5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_9jz56xtlqeggkfwegxt1 td.tinytable_css_zrso9ksyj6udnadpfa2p, #tinytable_9jz56xtlqeggkfwegxt1 th.tinytable_css_zrso9ksyj6udnadpfa2p {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_9jz56xtlqeggkfwegxt1\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Face of a die</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Probability</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">1</td>\n                  <td data-row=\"1\" data-col=\"2\">1/6</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">2</td>\n                  <td data-row=\"2\" data-col=\"2\">1/6</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">3</td>\n                  <td data-row=\"3\" data-col=\"2\">1/6</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">4</td>\n                  <td data-row=\"4\" data-col=\"2\">1/6</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">5</td>\n                  <td data-row=\"5\" data-col=\"2\">1/6</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">6</td>\n                  <td data-row=\"6\" data-col=\"2\">1/6</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThings become more complicated when we consider multiple coin-tosses, or rolls of a die. These series of events can be summarised by considering the number of times a certain outcome is observed. For example, the probability of obtaining three heads from five coin tosses.\n\nProbability distributions can be used in two main ways:\n\n1.  To calculate the probability of an event occurring. This seems trivial for the coin-toss and die-roll examples above. However, we can consider more complex events, as below.\n2.  To understand the behaviour of a sample statistic. We will see in Modules 3 and 4 that we can assume the mean of a sample follows a probability distribution. We can obtain useful information about the sample mean by using properties of the probability distribution.\n\n## Discrete random variables and their probability distributions\n\nRather than thinking of random events, we often use the term *random variable* to describe a quantity that can have different values determined by chance.\n\nA *discrete random variable* is a random variable that can take on only countable values (that is, non-negative whole numbers). An example of a discrete random variable is the number of heads observed in a series of coin tosses.\n\nA discrete random variable can be summarised by listing all the possible values that the variable can take. As defined earlier, a table, formula or graph that presents these possible values, and their associated probabilities, is called a probability distribution.\n\nExample: let’s consider the number of heads in a series of three coin tosses. We might observe 0 heads, or 1 head, or 2, or 3 heads. If we let X denote the number of heads in a series of three coin tosses, then possible values of X are 0, 1, 2 or 3.\n\nWe write the probability of observing x heads as P(X=x). So P(X=0) is the probability that the three tosses has no heads. Similarly, P(X=1) is the probability of observing one head.\n\nThe possible combinations for three coin tosses are as follows:\n\n\n::: {#tbl-2-3toss .cell tbl-cap='The number of heads from three coin tosses' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_47o8tsm5sm9tjj5tz2xn = TinyTable.createTableFunctions(\"tinytable_47o8tsm5sm9tjj5tz2xn\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '8', j: 1 }, { i: '8', j: 2 } ], css_id: 'tinytable_css_533qi8s1wropdgkhxevh',}, \n          { positions: [ { i: '1', j: 1 }, { i: '4', j: 1 }, { i: '7', j: 1 }, { i: '1', j: 2 }, { i: '4', j: 2 }, { i: '7', j: 2 } ], css_id: 'tinytable_css_l9u0r44tvyp3o9gd8d6a',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_0s7h9rlnozfsyb7uaoi4',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_47o8tsm5sm9tjj5tz2xn.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_47o8tsm5sm9tjj5tz2xn td.tinytable_css_533qi8s1wropdgkhxevh, #tinytable_47o8tsm5sm9tjj5tz2xn th.tinytable_css_533qi8s1wropdgkhxevh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_47o8tsm5sm9tjj5tz2xn td.tinytable_css_l9u0r44tvyp3o9gd8d6a, #tinytable_47o8tsm5sm9tjj5tz2xn th.tinytable_css_l9u0r44tvyp3o9gd8d6a {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_47o8tsm5sm9tjj5tz2xn td.tinytable_css_0s7h9rlnozfsyb7uaoi4, #tinytable_47o8tsm5sm9tjj5tz2xn th.tinytable_css_0s7h9rlnozfsyb7uaoi4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_47o8tsm5sm9tjj5tz2xn\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Pattern</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Number of heads</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Tail, Tail, Tail</td>\n                  <td data-row=\"1\" data-col=\"2\">0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Head, Tail, Tail</td>\n                  <td data-row=\"2\" data-col=\"2\"> </td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Tail, Head, Tail</td>\n                  <td data-row=\"3\" data-col=\"2\">1</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">Tail, Tail, Head</td>\n                  <td data-row=\"4\" data-col=\"2\"> </td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Head, Head, Tail</td>\n                  <td data-row=\"5\" data-col=\"2\"> </td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">Head, Tail, Head</td>\n                  <td data-row=\"6\" data-col=\"2\">2</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Tail, Head, Head</td>\n                  <td data-row=\"7\" data-col=\"2\"> </td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">Head, Head, Head</td>\n                  <td data-row=\"8\" data-col=\"2\">3</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThere are eight possible outcomes from three coin tosses (permutations). If we assume an equal chance of observing a head or a tail, each permutation above is equally likely, and so has a probability of 1/8.\n\nIf we consider the possibility of observing just one head out of the three tosses, this can happen in three ways (HTT, THT, TTH). So the probability of observing one head is calculated using the additive law: P(X=1) = $\\tfrac{1}{8} + \\tfrac{1}{8} + \\tfrac{1}{8} = \\tfrac{3}{8}$.\n\nTherefore, the probability distribution for X, the number of heads from three coin tosses, is as follows:\n\n\n::: {#tbl-2-4 .cell tbl-cap='Probability distribution for the number of heads from three coin tosses' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_b3ep5vaptuyorcx0qnp7 = TinyTable.createTableFunctions(\"tinytable_b3ep5vaptuyorcx0qnp7\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 1 }, { i: '4', j: 2 } ], css_id: 'tinytable_css_h637aatamfk6w8ew9p5o',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_j71nbqkfjk1paqpseyve',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_b3ep5vaptuyorcx0qnp7.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_b3ep5vaptuyorcx0qnp7 td.tinytable_css_h637aatamfk6w8ew9p5o, #tinytable_b3ep5vaptuyorcx0qnp7 th.tinytable_css_h637aatamfk6w8ew9p5o {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_b3ep5vaptuyorcx0qnp7 td.tinytable_css_j71nbqkfjk1paqpseyve, #tinytable_b3ep5vaptuyorcx0qnp7 th.tinytable_css_j71nbqkfjk1paqpseyve {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_b3ep5vaptuyorcx0qnp7\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">x (number of heads observed)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">P(X=x)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0</td>\n                  <td data-row=\"1\" data-col=\"2\">1/8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">1</td>\n                  <td data-row=\"2\" data-col=\"2\">1/8 + 1/8 + 1/8 = 3/8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">2</td>\n                  <td data-row=\"3\" data-col=\"2\">1/8 + 1/8 + 1/8 = 3/8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">3</td>\n                  <td data-row=\"4\" data-col=\"2\">1/8</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nNote that the probabilities sum to 1.\n\nThe above example was based on a coin toss, where flipping a head or a tail is equally likely (both have probabilities of 0.5). Let’s consider a case where the probability of an event is not equal to 0.5: having blood type A.\n\nFrom @tbl-2-1, the probability that a person has Type A blood is 0.38, and therefore, the probability that a person does not have Type A blood is 0.62 (1–0.38). If we considered taking a random sample of three people, the probability that all three would have Type A blood is 0.38 × 0.38 × 0.38 (using the multiplicative rule above) – and there is only one way this could happen.\n\nThe number of ways two people out of three could have Type A blood is 3, and each permutation is listed in @tbl-2-5. The probability of observing each of the three patterns is the same, and can be calculated using the multiplicative rule: 0.38 × 0.38 × 0.62 = 0.0895.\n\n\n::: {#tbl-2-5 .cell tbl-cap='Combinations and probabilities of Type A blood in three people' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_uipti6knjhlp9hcnjkze = TinyTable.createTableFunctions(\"tinytable_uipti6knjhlp9hcnjkze\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '8', j: 1 }, { i: '8', j: 2 }, { i: '8', j: 3 }, { i: '8', j: 4 } ], css_id: 'tinytable_css_hw8rvdnqrll61biztp3e',}, \n          { positions: [ { i: '1', j: 1 }, { i: '4', j: 1 }, { i: '7', j: 1 }, { i: '1', j: 2 }, { i: '4', j: 2 }, { i: '7', j: 2 }, { i: '1', j: 3 }, { i: '4', j: 3 }, { i: '7', j: 3 }, { i: '1', j: 4 }, { i: '4', j: 4 }, { i: '7', j: 4 } ], css_id: 'tinytable_css_u3w6lx7fsze0ot4gpb51',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_sfx0787pg2tn1axdyynv',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_uipti6knjhlp9hcnjkze.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_uipti6knjhlp9hcnjkze td.tinytable_css_hw8rvdnqrll61biztp3e, #tinytable_uipti6knjhlp9hcnjkze th.tinytable_css_hw8rvdnqrll61biztp3e {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_uipti6knjhlp9hcnjkze td.tinytable_css_u3w6lx7fsze0ot4gpb51, #tinytable_uipti6knjhlp9hcnjkze th.tinytable_css_u3w6lx7fsze0ot4gpb51 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_uipti6knjhlp9hcnjkze td.tinytable_css_sfx0787pg2tn1axdyynv, #tinytable_uipti6knjhlp9hcnjkze th.tinytable_css_sfx0787pg2tn1axdyynv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_uipti6knjhlp9hcnjkze\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Person 1</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Person 2</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Person 3</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Probability</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">A</td>\n                  <td data-row=\"1\" data-col=\"2\">A</td>\n                  <td data-row=\"1\" data-col=\"3\">A</td>\n                  <td data-row=\"1\" data-col=\"4\">0.38 × 0.38 × 0.38 = 0.0549</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">A</td>\n                  <td data-row=\"2\" data-col=\"2\">A</td>\n                  <td data-row=\"2\" data-col=\"3\">Not A</td>\n                  <td data-row=\"2\" data-col=\"4\">0.38 × 0.38 × 0.62 = 0.0895</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">A</td>\n                  <td data-row=\"3\" data-col=\"2\">Not A</td>\n                  <td data-row=\"3\" data-col=\"3\">A</td>\n                  <td data-row=\"3\" data-col=\"4\">0.38 × 0.62 × 0.38 = 0.0895</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">Not A</td>\n                  <td data-row=\"4\" data-col=\"2\">A</td>\n                  <td data-row=\"4\" data-col=\"3\">A</td>\n                  <td data-row=\"4\" data-col=\"4\">0.62 × 0.38 × 0.38 = 0.0895</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">A</td>\n                  <td data-row=\"5\" data-col=\"2\">Not A</td>\n                  <td data-row=\"5\" data-col=\"3\">Not A</td>\n                  <td data-row=\"5\" data-col=\"4\">0.38 × 0.62 × 0.62 = 0.1461</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">Not A</td>\n                  <td data-row=\"6\" data-col=\"2\">A</td>\n                  <td data-row=\"6\" data-col=\"3\">Not A</td>\n                  <td data-row=\"6\" data-col=\"4\">0.62 × 0.38 × 0.62 = 0.1461</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Not A</td>\n                  <td data-row=\"7\" data-col=\"2\">Not A</td>\n                  <td data-row=\"7\" data-col=\"3\">A</td>\n                  <td data-row=\"7\" data-col=\"4\">0.62 × 0.62 × 0.38 = 0.1461</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">Not A</td>\n                  <td data-row=\"8\" data-col=\"2\">Not A</td>\n                  <td data-row=\"8\" data-col=\"3\">Not A</td>\n                  <td data-row=\"8\" data-col=\"4\">0.62 × 0.62 × 0.62 = 0.2383</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n@tbl-2-6 gives the probability of each of the blood type combinations we could observe in three people. The probability of observing a certain number of people (say, k) with Type A blood from a sample of three people can be calculated by summing the combinations:\n\n\n::: {#tbl-2-6 .cell tbl-cap='Probabilities of observing numbers of people with Type A blood in a sample of three people' tbl-pos='h'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_8vuwymrvalhqiqjfhbpn = TinyTable.createTableFunctions(\"tinytable_8vuwymrvalhqiqjfhbpn\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 1 }, { i: '4', j: 2 } ], css_id: 'tinytable_css_7i3bbwuo242bdn1d2lig',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_sp3zm8d9i6k1qxou06do',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_8vuwymrvalhqiqjfhbpn.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_8vuwymrvalhqiqjfhbpn td.tinytable_css_7i3bbwuo242bdn1d2lig, #tinytable_8vuwymrvalhqiqjfhbpn th.tinytable_css_7i3bbwuo242bdn1d2lig {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_8vuwymrvalhqiqjfhbpn td.tinytable_css_sp3zm8d9i6k1qxou06do, #tinytable_8vuwymrvalhqiqjfhbpn th.tinytable_css_sp3zm8d9i6k1qxou06do {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_8vuwymrvalhqiqjfhbpn\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Number of people with Type A blood</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Probability of each pattern</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">3</td>\n                  <td data-row=\"1\" data-col=\"2\">0.0549</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">2</td>\n                  <td data-row=\"2\" data-col=\"2\">0.0895 + 0.0895 + 0.0895 = 0.2689</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">1</td>\n                  <td data-row=\"3\" data-col=\"2\">0.1461 + 0.1461 + 0.1461 = 0.4382</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">0</td>\n                  <td data-row=\"4\" data-col=\"2\">0.2383</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n## Binomial distribution\n\nThe above are examples of the binomial distribution. The binomial distribution is used when we have a collection of random events, where each random event is binary (e.g. Heads vs Tails, Type A blood vs Not Type A blood, Infected vs Not infected). The binomial distribution calculates (in general terms):\n\n-   the probability of observing k successes\n-   from a collection of n trials\n-   where the probability of a success in one trial is p.\n\nThe terms used here can be defined as:\n\n-   a success is simply an event of interest from a binary random event. In the coin-toss example, “success” was tossing a Head. In the blood type example, we were only interested in whether someone was Type A or not Type A, so “success” was a blood of Type A. We tend to use the word “success” to mean “an event of interest”, and “failure” as “an event not of interest”.\n-   the number of trials refers to the number of random events observed. In both examples, we observed three events (three coin tosses, three people).\n-   the probability of a success (p) simply refers to the probability of the event of interest. In the coin toss example, this was the probability of tossing a Heads (=0.5); for the blood-type example, this was the probability of having Type A blood (0.38).\n\nPutting all this together, we say that we have a binomial experiment. To satisfy the assumptions of a binomial distribution, our experiment must satisfy the following criteria:\n\n1.  The experiment consists of fixed number (n) of trials.\n2.  The result of each trial falls into only one of two categories – the event occurred (“success”) or the event did not occur (“failure”).\n3.  The probability, p, of the event occurring remains constant for each trial.\n4.  Each trial of the experiment is independent of the other trials.\n\nWe have shown in the examples above how we can calculate the probabilities for small experiments (n=3). Once n becomes large, constructing such probability distribution tables becomes difficult. The general formula for calculating the probability of observing k successes from n trials, where each trial has a probability of success of p is given by:\n\n$$ P(X=k) = \\frac{n!}{k! (n-k)!} \\times p^k \\times (1-p)^{n-k} $$\n\nwhere $n! = n \\times (n-1) \\times (n-2) \\times \\dots \\times 2 \\times 1$.\n\n**Note that this formula is almost never calculated by hand.** Instructions for calculating binomial probabilities are given in the jamovi and R notes at the end of this Module.\n\n#### Worked example {.unnumbered}\n\nA population-based survey conducted by the AIHW (2008) of a random sample of the Australian population estimated that in 2007, 19.8% of the Australian population were current smokers.\n\na)  From a random sample of 6 people from the Australian population in 2007, what is the probability that 3 of them will be smokers?\nb)  What is the probability that among the six persons, at least 4 will be smokers?\nc)  What is the probability that at most, 2 will be smokers?\n\n#### Solution {.unnumbered}\n\na)  Calculating this single binomial probability is best done using software.\n\nWe can use the [applet](https://mabognar.github.io/apps/bin.html){target=\"_blank\"} to calculate this, or use the `dbinom` function in R with x=3, size=6, and prob=0.198. This gives an answer of 0.08.\n\nb)  In common language, getting “at least 4” smokers means getting 4, 5 or 6 smokers. Since these are mutually exclusive events, we can apply the additive law to find the probability of getting at least 4 smokers:\n\n$$ P(X \\ge 4) = P(X=4) + P(X=5) + P(X=6) $$ Using the same binomial probability functions as in the previous question, we could calculate\n\n-   P(X=4) = 0.0148\n-   P(X=5) = 0.00146\n-   P(X=6) = 0.0000603\n\nAnswer: $P(X \\ge 4) = 0.0148 + 0.00146 + 0.0000603 = 0.016$\n\nWe can use the [applet](https://mabognar.github.io/apps/bin.html){target=\"_blank\"} to calculate this, or in R we can use the `pbinom` function with the `lower.tail=FALSE` option.\n\nc)  Observing at most two means observing 0, 1 or 2 smokers. Therefore, the probability of observing at most 2 smokers is:\n\n-   P(X $\\le$ 2) = P(X=0) + P(X=1) + P(X=2)\n-   P(X=0) = 0.266\n-   P(X=1) = 0.394\n-   P(X=2) = 0.243\n\nAnswer: P(X $\\le$ 2) = 0.266+0.394+0.243=0.903\n\nAgain, we can use the [applet](https://mabognar.github.io/apps/bin.html){target=\"_blank\"} to calculate this, or use the `pbinom` function in R.\n\n{{< pagebreak >}}\n\n# jamovi notes {.unnumbered}\n\n## Producing a one-way frequency table\n\nThe simplest way to summarise categorical variables is with a one-way frequency table. These are constructed using **Analyses \\> Exploration**. We will illustrate this by summarising the variable `sex` from the `pbc.rds` data from the previous module.\n\n![](img/mod02/jamovi/mod02-onefreq01.png)\n\njamovi has summarised `sex` here, just as we asked it to, however it has analysed `sex` as if it was a continuous variable. This is incorrect: `sex` is a categorical variable. This can be corrected by defining `sex` to be categorical within **Data \\> Setup**:\n\n1.  Select `sex`, then choose **Nominal** as the Measure type. jamovi now lists the levels of `sex` as 1 and 2. These should be replaced by the categories they represent.\n2.  From the `mod01_pbc_info.txt` file, we see that 1 represents Male, and 2 represents Female. These labels can be added by typing in the appropriate cell. The completed screen should look like this:\n\n![](img/mod02/jamovi/mod02-onefreq02.png)\n\nClicking back to the original summary of sex shows that jamovi is no longer treating `sex` as a continuous variable, but there is little output in the summary:\n\n![](img/mod02/jamovi/mod02-onefreq03.png){width=\"30%\"}\n\nClick **Frequency tables** in the main Descriptives window to request the one-way frequency table:\n\n![](img/mod02/jamovi/mod02-onefreq04.png)\n\n## Producing a two-way frequency table\n\nTwo-way tables are constructed using **Analyses > Frequencies > Contingency Tables > Independent Samples**. Note that **both variables must be defined as Nominal or Ordinal variables**. As an example, to produce a two-way table of disease stage by sex:\n\n![](img/mod02/jamovi/mod02-twofreq01.png)\n\n**Ignore the output labelled χ^2^ tests for now.**\n\nRow or column percents can be requested in the **Cells** section. For example, to calculate the proportion of males within each stage of disease, we would request column percents:\n\n![](img/mod02/jamovi/mod02-twofreq02.png)\n\n## Creating bar charts for one categorical variable\n\nHere we will create the bar chart shown in @fig-bar-1 using the `mod01_pbc.rds` dataset. The x-axis of this graph will be the stage of disease, and the y-axis will show the number of participants in each category.\n\nBar charts are created in the **Exploration** tab. We can summarise `stage`, and request a **Frequency table** in the usual way. To request a bar chart as well, tick **Bar plot** within the **Plots** section:\n\n![](img/mod02/jamovi/mod02-barchart01.png)\n\n## Creating bar charts for two categorical variables\n\n### Option 1: Using Contingency Tables command\n\nCreating a **clustered bar chart** as shown in @fig-bar-2 can be done using **Analyses > Frequencies > Contingency Tables > Independent Samples**. First create the cross-tab of interest, for example, Stage by Sex. Choose **Plots > Bar Plot**, and ensure the Bar Type is selected as **Side by side**. Choose the X-axis as required - here we want to see stage on the x-axis, so we choose the x-axis to be columns (this may need to be adjusted according to how your table has been set up):\n\n![](img/mod02/jamovi/mod02-clustered.png)\nTo create a **stacked bar chart** (as in @fig-bar-3), choose the Bar Type to be **Stacked**:\n\n![](img/mod02/jamovi/mod02-stacked.png)\n\nFinally, to create a **stacked relative bar chart** (as in @fig-bar-4), choose the Y-axis to be **Percentages within column**:\n\n![](img/mod02/jamovi/mod02-stacked-rel.png)\n\n### Option 2: Using Survey Plots command\n\nAn alternative way of producing barcharts is via a Module called **surveymv** that we add to jamovi. To install the module, click the **Analyses** tab, and click the large **+** at the top-right of the window. Choose **jamovi library**:\n\n![](img/mod02/jamovi/act2.1.2.png)\n\nClick **Available** and search for `surveymv`, then click install:\n\n![](img/mod02/jamovi/act2.1.3.png)\n\nThe module has now been installed. To run the module, click the up-arrow to return to the **Analyses** tab, click the large **+** and choose **surveymv > Survey Plots**:\n\n![](img/mod02/jamovi/act2.1.4.png)\n\nWe will demonstrate the module by recreating @fig-bar-4, a figure of the relative frequencies of sex within stage of disease. To open the module options, click the large **+** and choose **surveymv > Survey Plots**:\n\n![](img/mod02/jamovi/surveymv-1.png)\n\nWe choose the variable we want to plot, here `Sex`. We want to plot sex within each stage, so `Stage` is entered as a **Grouping Variable**:\n\n![](img/mod02/jamovi/surveymv-2.png)\n\nThis has plotted a clustered bar chart, we want a stacked bar chart, so select **Stacked bar**. Also, we want to plot percentages, not counts, so choose **Percentages**:\n\n![](img/mod02/jamovi/surveymv-3.png)\n\nOur stacked relative frequency chart has been completed. While this produces a bar chart with horizontal bars, it often performs better with labelling of the groups than the previous method.\n\n## Recoding data {#sec-recoding-data-jmv}\n\nOne task that is common in statistical computing is to recode variables. For example, we might want to group some categories of a categorical variable, or to present a continuous variable in a categorical way.\n\nIn this example, we can use the `pbc` data and recode age into age groups:\n\n-   Less than 30\n-   30 to less than 50\n-   50 to less than 70\n-   70 or older\n\nRecoding can be done using **Data > Transform**.\n\nFirst, click **Data** to view the spreadsheet, then click in an empty column, then click **Setup > NEW TRANSFORMED VARIABLE**. We need to specify three things:\n\n1. The name of the new variable. Here, we will choose `age group`.\n2. The source variable. Here, we want to recode **from** `age`, so choose `age`.\n3. The `transform`, which is where we define the rules of the recode. Choose **Create New Transform**.\n\n![](img/mod02/jamovi/mod02-recode2.png)\n\nThe `transform` is built up by specifying the **recode conditions**. Click **+ Add recode condition** to define the first condition:\n\n![](img/mod02/jamovi/mod02-recode3.png)\n\nHere we want to define all ages less than 30 as \"Less than 30\". Complete the recode condition so it appears as: `if $source < 30 use \"Less than 30\"`. Note that the quotation marks around \"Less than 30\" are required:\n\n![](img/mod02/jamovi/mod02-recode4.png)\n\nAdd another recode condition, which will be applied if the first condition is not satisfied: `if $source < 50 use \"30 to less than 50\"`:\n\n![](img/mod02/jamovi/mod02-recode5.png)\n\nAdd another condition: `if $source < 70 use \"50 to less than 70\"`. There is no need to add a condition for the final condition, simply complete the final line: `else use \"70 or more\"`:\n\n![](img/mod02/jamovi/mod02-recode6.png)\n\nFinally, click the **down** arrow to dismiss the transform builder, and the **up** arrow to dismiss the transform dialog.\n\nWe can examine the new categories by obtaining a frequency table: **Analyses > Exploration > Descriptives**:\n\n![](img/mod02/jamovi/mod02-recode7.png)\n\n## Computing binomial probabilities\n\njamovi does not have a point-and-click method for computing probabilities from a binomial distribution. Here, instructions are provided for using a third-party applet. This Binomial Distribution Applet has been posted at [https://mabognar.github.io/apps/bin.html](https://mabognar.github.io/apps/bin.html){target=\"_blank\"}, and provides a simple and intuitive way to compute probabilities from a binomial distribution. \n\nThe applet requires three pieces of information:\n\n- $n$: the number of binary trials being considered\n- $p$: the probability of \"success\" in each trial\n- $x$: the number of success we are interested in\n\nWe also need to consider whether we are interested in the probability being equal to, greater than, or less than x.\n\nTo do the computation for part (a) in Worked Example 2.1:\n\n-   $x$ is the number of successes, here, the number of smokers (i.e. x=3);\n-   $n$ is the number of trials (i.e. n=6);\n-   and $p$ is probability of drawing a smoker from the population, which is 19.8% (i.e. p=0.198).\n\nReplace each of these with the appropriate number into the applet:\n\n![](img/mod02/jamovi/mod02-bin-01.png)\n\nTo calculate the probability of at least 4 smokers in part (b), we change the drop-down to \"P(X≥x)\", and x to be equal to 4:\n\n![](img/mod02/jamovi/mod02-bin-02.png)\n\nTo calculate the probability of at most 2 smokers part (c), we we change the drop-down to \"P(X≤x)\", and x to be equal to 2:\n\n![](img/mod02/jamovi/mod02-bin-03.png)\n\n\n{{< pagebreak >}}\n\n# R notes {.unnumbered}\n\n\n\n### Producing a one-way frequency table\n\nWe have three categorical variables to summarise in our PBC Table 1: sex, stage and vital status. These variables are best summarised using one-way frequency tables, which can be constructed using the `descriptives` function from the `jmv` package, with the `freq = TRUE` option. Before constructing frequency tables however, we *must define the variables as categorical variables*, by converting them to *factors*.\n\n#### Defining categorical variables as factors {#sec-cat-as-factors}\n\nTo define a categorical variable as such in R, we define it as a **factor** using the factor function:\n\n`factor(variable=, levels=, labels=)`\n\nWe specify:\n\n-   levels: the values the categorical variable can take\n-   labels: the labels corresponding to each of the levels (entered in the same order as the levels)\n\nTo define our variable `sex` as a factor, we use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbc <- readRDS(\"data/activities/mod01_pbc.rds\")\n\npbc$sex <- factor(pbc$sex, levels = c(1, 2), labels = c(\"Male\", \"Female\"))\n```\n:::\n\n\nWe can then produce a frequency table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives(data = pbc, vars = sex, freq = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n DESCRIPTIVES\n\n Descriptives                  \n ───────────────────────────── \n                         sex   \n ───────────────────────────── \n   N                     418   \n   Missing                 0   \n   Mean                        \n   Median                      \n   Standard deviation          \n   Minimum                     \n   Maximum                     \n ───────────────────────────── \n\n\n FREQUENCIES\n\n Frequencies of sex                                 \n ────────────────────────────────────────────────── \n   sex       Counts    % of Total    Cumulative %   \n ────────────────────────────────────────────────── \n   Male          44      10.52632        10.52632   \n   Female       374      89.47368       100.00000   \n ────────────────────────────────────────────────── \n```\n\n\n:::\n:::\n\n\n> Task: define `stage` and `status` (Vital Status) as factors, and produce one-way frequency tables. Refer to the file `pbc_info.txt` to view the labels for each variable. For example, for Stage:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbc$stage <- factor(\n  pbc$stage,\n  levels = c(1, 2, 3, 4),\n  labels = c(\"Stage 1\", \"Stage 2\", \"Stage 3\", \"Stage 4\")\n)\n```\n:::\n\n\n### Producing a two-way frequency table\n\nTo produce tables summarising two categorical variables, we can use the `contTables()` function within the `jmv` package. The minimal inputs to include are `data`: the name of the data frame to be analysed, `rows`: the variable representing the rows of the table, and `cols`: the name of the columns of the table.\n\nFor example, to produce a two-way table showing stage of disease by sex using the pbc data frame, we use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontTables(data = pbc, rows = sex, cols = stage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n CONTINGENCY TABLES\n\n Contingency Tables                                              \n ─────────────────────────────────────────────────────────────── \n   sex       Stage 1    Stage 2    Stage 3    Stage 4    Total   \n ─────────────────────────────────────────────────────────────── \n   Male            3          8         16         17       44   \n   Female         18         84        139        127      368   \n   Total          21         92        155        144      412   \n ─────────────────────────────────────────────────────────────── \n\n\n χ² Tests                               \n ────────────────────────────────────── \n         Value        df    p           \n ────────────────────────────────────── \n   χ²    0.8779873     3    0.8307365   \n   N           412                      \n ────────────────────────────────────── \n```\n\n\n:::\n:::\n\n\n[The bottom part of the output, χ² Tests, can be ignored for now]\n\nYou may notice in the above that the number of observations is now 412. This is because there are missing observations for either sex or stage: which is it, and how would you determine this?\n\nFrom the cross-tabulation, you can see the individual frequencies of participants in each of the categories in each cell. For example, there are 3 male participants who have Stage 1 disease. You can also read the totals for each row and column. For example, there are 44 males, and 144 participants have Stage 4 disease.\n\nYou can also add percentages into your table using `pcCol=TRUE` to include column percents, and `pcRow=TRUE` for row percents. For example, to calculate the relative frequencies (i.e. percentages) of sex within each stage, we would request **column percents** with the option: `pcCol=TRUE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontTables(data = pbc, rows = sex, cols = stage, pcCol = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n CONTINGENCY TABLES\n\n Contingency Tables                                                                             \n ────────────────────────────────────────────────────────────────────────────────────────────── \n   sex                          Stage 1      Stage 2      Stage 3      Stage 4      Total       \n ────────────────────────────────────────────────────────────────────────────────────────────── \n   Male      Observed                   3            8           16           17           44   \n             % within column     14.28571      8.69565     10.32258     11.80556     10.67961   \n                                                                                                \n   Female    Observed                  18           84          139          127          368   \n             % within column     85.71429     91.30435     89.67742     88.19444     89.32039   \n                                                                                                \n   Total     Observed                  21           92          155          144          412   \n             % within column    100.00000    100.00000    100.00000    100.00000    100.00000   \n ────────────────────────────────────────────────────────────────────────────────────────────── \n\n\n χ² Tests                               \n ────────────────────────────────────── \n         Value        df    p           \n ────────────────────────────────────── \n   χ²    0.8779873     3    0.8307365   \n   N           412                      \n ────────────────────────────────────── \n```\n\n\n:::\n:::\n\n\nWe can see that the 3 male participants with Stage 1 disease represent 14% of those with Stage 1 disease.\n\n## Creating bar charts for one categorical variable\n\nThe simplest way to use the `plot()` function is by specifying an object to be plotted. To plot a single variable from a data frame, we must define it using: `dataframe$variable`.\n\nHere we will create the bar chart shown in @fig-bar-1 of the statistics notes using the `mod01_pdc.rds` dataset. The x-axis of this graph will be the stage of disease, and the y-axis will show the number of participants in each category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  pbc$stage,\n  main = \"Bar graph of stage of disease from PBC study\",\n  ylab = \"Number of participants\"\n)\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nNote that stage is a categorical variable, that has been defined as a factor (in @sec-cat-as-factors). You **must define categorical data as factors** to plot them in a bar graph.\n\n## Creating bar charts for two categorical variables\n\n### Option 1: Using the contTables function\n\nCreating a **clustered bar chart** as shown in @fig-bar-2 can be done easily using the `contTables` function in the `jmv` package. First create a cross-tab from the variables to be plotted, for example, Stage by Sex:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontTables(data = pbc, rows = sex, cols = stage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n CONTINGENCY TABLES\n\n Contingency Tables                                              \n ─────────────────────────────────────────────────────────────── \n   sex       Stage 1    Stage 2    Stage 3    Stage 4    Total   \n ─────────────────────────────────────────────────────────────── \n   Male            3          8         16         17       44   \n   Female         18         84        139        127      368   \n   Total          21         92        155        144      412   \n ─────────────────────────────────────────────────────────────── \n\n\n χ² Tests                               \n ────────────────────────────────────── \n         Value        df    p           \n ────────────────────────────────────── \n   χ²    0.8779873     3    0.8307365   \n   N           412                      \n ────────────────────────────────────── \n```\n\n\n:::\n:::\n\n\n\nCreating a **clustered bar chart** as shown in @fig-bar-2 can be done by requesting a bar chart (`barplot=TRUE`), and the x-axis should be constructed from `stage` - that is, the **column** variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontTables(pbc, rows = sex, cols = stage, barplot = TRUE, xaxis = \"xcols\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n CONTINGENCY TABLES\n\n Contingency Tables                                              \n ─────────────────────────────────────────────────────────────── \n   sex       Stage 1    Stage 2    Stage 3    Stage 4    Total   \n ─────────────────────────────────────────────────────────────── \n   Male            3          8         16         17       44   \n   Female         18         84        139        127      368   \n   Total          21         92        155        144      412   \n ─────────────────────────────────────────────────────────────── \n\n\n χ² Tests                               \n ────────────────────────────────────── \n         Value        df    p           \n ────────────────────────────────────── \n   χ²    0.8779873     3    0.8307365   \n   N           412                      \n ────────────────────────────────────── \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nIf you want the x-axis to be constructed from the row variable, you would use `xaxis = \"xrows\"`.\n\nTo create a **stacked bar chart** (as in @fig-bar-3), specify `bartype` to be `stack`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontTables(\n  pbc,\n  rows = sex,\n  cols = stage,\n  barplot = TRUE,\n  xaxis = \"xcols\",\n  bartype = \"stack\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n CONTINGENCY TABLES\n\n Contingency Tables                                              \n ─────────────────────────────────────────────────────────────── \n   sex       Stage 1    Stage 2    Stage 3    Stage 4    Total   \n ─────────────────────────────────────────────────────────────── \n   Male            3          8         16         17       44   \n   Female         18         84        139        127      368   \n   Total          21         92        155        144      412   \n ─────────────────────────────────────────────────────────────── \n\n\n χ² Tests                               \n ────────────────────────────────────── \n         Value        df    p           \n ────────────────────────────────────── \n   χ²    0.8779873     3    0.8307365   \n   N           412                      \n ────────────────────────────────────── \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nFinally, to create a **stacked relative bar chart** (as in @fig-bar-4), specify the y-axis to be a percent (`yaxis=\"ypc\"`), and the percentage be calculated from the columns of the frequency table (`yaxisPc = \"column_pc\"`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontTables(\n  pbc,\n  rows = sex,\n  cols = stage,\n  barplot = TRUE,\n  bartype = \"stack\",\n  xaxis = \"xcols\",\n  yaxis = \"ypc\",\n  yaxisPc = \"column_pc\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n CONTINGENCY TABLES\n\n Contingency Tables                                              \n ─────────────────────────────────────────────────────────────── \n   sex       Stage 1    Stage 2    Stage 3    Stage 4    Total   \n ─────────────────────────────────────────────────────────────── \n   Male            3          8         16         17       44   \n   Female         18         84        139        127      368   \n   Total          21         92        155        144      412   \n ─────────────────────────────────────────────────────────────── \n\n\n χ² Tests                               \n ────────────────────────────────────── \n         Value        df    p           \n ────────────────────────────────────── \n   χ²    0.8779873     3    0.8307365   \n   N           412                      \n ────────────────────────────────────── \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n### Option 2: Using surveyPlot function\n\nAn alternative way of producing barcharts is via a package called `surveymv`. Unfortunately, surveymv is not hosted on the standard package repository, we need to install the package from github.com. This is a straight-forward process, which involves installing a package called `devtools` that allows packages to be installed from alternative locations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"devtools\")\nlibrary(devtools)\ninstall_github(\"raviselker/surveymv\")\n```\n:::\n\n\nThese commands have installed the `surveymv` package. We load the packing using the standard `library()` command:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(surveymv)\n```\n:::\n\n\n`surveymv` has only one function: `surveyPlot`, with the following syntax:\n\n```\nsurveyPlot(\n  data = babies,\n  vars = \"Birth weight\",\n  group = \"Age group\",\n  type = \"stacked\",\n  freq = \"perc\")\n```\n\nWe specify our data (`data=`), and the main variable to be plotted (`vars=`). If we have a grouping variable, we specify a `group=` variable. We define the chart to be either a stacked (`type = \"stacked\"`) or clustered (`type = \"grouped\"`) bar chart, and specify whether to plot frequencies (`freq = \"count\"`) or percentages (`freq = \"perc\"`).\n\nTo demonstrate, we will recreate @fig-bar-4, a figure of the relative frequencies of sex within stage of disease:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(surveymv)\n\nsurveyPlot(\n  data = pbc,\n  vars = \"sex\",\n  group = \"stage\",\n  type = \"stacked\",\n  freq = \"perc\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n SURVEY PLOTS\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nWhile this produces a bar chart with horizontal bars, it often performs better with labelling of the groups than the previous method.\n\n## Importing data into R\n\nWe have described previously how to import data that have been saved as R .rds files. It is quite common to have data saved in other file types, such as Microsoft Excel, or plain text files. In this section, we will demonstrate how to import data from other packages into R.\n\nThere are two useful packages for importing data into R: `haven` (for data that have been saved by jamovi, SAS or SPSS) and `readxl` (for data saved by Microsoft Excel). Additionally, the `labelled` package is useful in working with data that have been labelled in jamovi.\n\n### Importing plain text data into R\n\nA `csv` file, or a \"comma separated variables\" file is commonly used to store data. These files have a very simple structure: they are plain text files, where data are separated by commas. csv files have the advantage that, as they are plain text files, they can be opened by a large number of programs (such as Notepad in Windows, TextEdit in MacOS, Microsoft Excel - even Microsoft Word). While they can be opened by Microsoft Excel, they can be opened by many other programs: the csv file can be thought of as the lingua-franca of data.\n\nIn this demonstration, we will use data on the weight of 1000 people entered in a csv file called `mod02_weight_1000.csv`.\n\nTo confirm that the file is readable by any text editor, here are the first ten lines of the file, opened in Notepad on Microsoft Windows, and TextEdit on MacOS.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](img/mod02/import-01.png){width=66%}\n:::\n:::\n\n\nWe can use the `read.csv` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample <- read.csv(\"data/examples/mod02_weight_1000.csv\")\n```\n:::\n\n\nHere, the `read.csv` function has the default that the first row of the dataset contains the variable names. If your data do not have column names, you can use `header=FALSE` in the function.\n\nNote: there is an alternative function `read_csv` which is part of the `readr` package (a component of the `tidyverse`). Some would argue that the `read_csv` function is more appropriate to use because of an issue known as `strings.as.factors`. The `strings.as.factors` default was removed in R Version 4.0.0, so it is less important which of the two functions you use to import a `.csv` file. More information about this issue can be found [here](https://simplystatistics.org/posts/2015-07-24-stringsasfactors-an-unauthorized-biography) and [here](https://developer.r-project.org/Blog/public/2020/02/16/stringsasfactors/).\n\n## Recoding data {#sec-recoding-data}\n\nOne task that is common in statistical computing is to recode variables. For example, we might want to group some categories of a categorical variable, or to present a continuous variable in a categorical way.\n\nIn this example, we can use the `pbc` data and recode age into age groups:\n\n-   Less than 30\n-   30 to less than 50\n-   50 to less than 70\n-   70 or older\n\nThe quickest way to recode a continuous variable into categories is to use the `cut` command which takes a continuous variable, and \"cuts\" it into groups based on the specified \"cutpoints\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbc$agegroup <- cut(pbc$age, breaks = c(0, 30, 50, 70, 100))\n```\n:::\n\n\nNotice that some numbers need to be defined for the lowest (age=0) and highest (age=100) bounds: both a lower and upper limit must be defined for each group.\n\nIf we examine the new `agegroup` variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pbc$agegroup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (0,30]  (30,50]  (50,70] (70,100] \n       3      192      210       13 \n```\n\n\n:::\n:::\n\n\nwe see that each group has been labelled in the form of (a, b]. This notation is equivalent to: greater than a, and less than or equal to b. The `cut` function excludes the lower limit, but includes the upper limit. Our age groups have been defined to include the lower limit, and exclude the upper limit (for example, greater than or equal to 30 and less than 50).\n\nWe can specify this recoding using the `right=FALSE` option:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbc$agegroup <- cut(pbc$age, breaks = c(0, 30, 50, 70, 100), right = FALSE)\n\nsummary(pbc$agegroup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [0,30)  [30,50)  [50,70) [70,100) \n       3      192      210       13 \n```\n\n\n:::\n:::\n\n\nFinally, we can specify labels for the groups using the `labels` option:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbc$agegroup <- cut(\n  pbc$age,\n  breaks = c(0, 30, 50, 70, 100),\n  right = FALSE,\n  labels = c(\n    \"Less than 30\",\n    \"30 to less than 50\",\n    \"50 to less than 70\",\n    \"70 or more\"\n  )\n)\n\nsummary(pbc$agegroup)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Less than 30 30 to less than 50 50 to less than 70         70 or more \n                 3                192                210                 13 \n```\n\n\n:::\n:::\n\n\n## Computing binomial probabilities using R {#sec-binom-r}\n\nThe Binomial Distribution Applet posted at [https://mabognar.github.io/apps/bin.html](https://mabognar.github.io/apps/bin.html){target=\"_blank\"}, provides a simple and intuitive way to compute probabilities from a binomial distribution. Refer to the jamovi instructions for details.\n\nThere are two R functions that we can use to calculate probabilities based on the binomial distribution: `dbinom` and `pbinom`:\n\n-   `dbinom(x, size, prob)` gives the probability of obtaining `x` successes from `size` trials when the probability of a success on one trial is `prob`;\n-   `pbinom(q, size, prob)` gives the probability of obtaining `q` **or fewer** successes from `size` trials when the probability of a success on one trial is `prob`;\n-   `pbinom(q, size, prob, lower.tail=FALSE)` gives the probability of obtaining **more than** `q`successes from `size` trials when the probability of a success on one trial is `prob`.\n\nTo do the computation for part (a) in Worked Example 2.1, we will use the `dbinom` function with:\n\n-   *x* is the number of successes, here, the number of smokers (i.e. k=3);\n-   *size* is the number of trials (i.e. n=6);\n-   and *prob* is probability of drawing a smoker from the population, which is 19.8% (i.e. p=0.198).\n\nReplace each of these with the appropriate number into the formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 3, size = 6, prob = 0.198)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08008454\n```\n\n\n:::\n:::\n\n\nTo calculate the upper tail of probability in part (b), we use the `pbinom(lower.tail=FALSE)` function. Note that the `pbinom(lower.tail=FALSE)` function **does not include `q`**, so to obtain 4 or more successes, we need to enter `q=3`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(q = 3, size = 6, prob = 0.198, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01635325\n```\n\n\n:::\n:::\n\n\nFor the lower tail for part (c), we use the `pbinom` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(q = 2, size = 6, prob = 0.198)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9035622\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n\n## Note\n\nIn this section, we introduce `ggplot2` which is a very flexible method of plotting data in R. The use of `ggplot2` is **completely optional**. It is perfectly fine to produce graphs using the simpler methods, as long as they are formatted appropriately.\n\n:::\n\n## Introducing `ggplot2`\n\nPlots produced by `plot(dens())` and `boxplot()` are often called `base` graphics: no special packages have been needed to produce these plots. In this section, we will introduce the `ggplot2` [^1] package, which defines plots using a **grammar of graphics**. This can seem like a complex way of constructing a plot, but the framework allows for very complex plots to be constructed in a relatively consistent way.\n\nThe grammar of graphics defines a number of elements of a plot; the key elements that we will use in this course are:\n\n- data: we need to specify the data we are plotting. The data must be stored as a dataframe, where variables are organised in columns, and observations are in rows\n- mapping: the *aesthetic mapping* describes how your data map to visual properties of the plot. For example, we might want to define the x-axis by the `age` variable and the colour of points by `sex`. We can define our mapping using the command `mapping = aes()`, and entering the specific aesthetic components within the `aes()` component.\n- geometries: we can think of *geometries* as defining the actual \"ink\" of the plot, modified by the *aesthetics* defined by the mapping. For example:\n  - `geom_bar()` will plot a bar-chart;\n  - `geom_boxplot()` will plot a boxplot;\n  - `geom_histogram()` will plot a histogram.\n- theme: the *theme* defines the overall look of the plot. Every part of the plot that is not specified by data can be adjusted by changing the theme. For example, fonts, axis ticks, legend position and background colours can all be changed by using a theme. Some useful themes are:\n  - `theme_bw()`: a black-and-white theme\n  - `theme_minimal()`: a clean them with no background annotations\n  - `theme_classic()`: a theme that removes grid-lines and backgrounds, leaving only axis lines.\n\nThese elements can be combined in a single `ggplot` command by using a `+` symbol, usually with each element provided on a new line.\n\n### Using `ggplot2` to construct a bar chart\n\nAs a demonstration, we will produce the simplest bar chart possible: a bar chart of `sex`.\n\nFirst, we will load the `ggplot2` library, and call the `ggplot` function with no function arguments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot()\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nIn this example, all `ggplot` has done is to create a blank canvas. Let's start filling the canvas in by specifying our dataset, and defining sex as our x-axis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, mapping = aes(x = sex))\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nOur blank canvas has been altered: we now have an x-axis, defined by `sex`, with values of `Male` and `Female`.\n\nTo add \"ink\" to our canvas, we now need to add a *geometry*. For a bar chart, we use `geom_bar()` as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, mapping = aes(x = sex)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nWe can change the look of the figure by choosing a different *theme*: let's use `theme_classic()` here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, mapping = aes(x = sex)) +\n  geom_bar() +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nThe final changes we can make are to define the axis labels using `labs()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, mapping = aes(x = sex)) +\n  geom_bar() +\n  theme_classic() +\n  labs(x = \"Participant sex\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nFinally, we can change the colour of the bars by specifying a `fill` colour within the `geom_bar()` command. We can choose one of over 600 (!) colours by name [^2].\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, mapping = aes(x = sex)) +\n  geom_bar(fill = \"steelblue\") +\n  theme_classic() +\n  labs(x = \"Participant sex\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nLet's adapt this code to produce a bar chart for stage of disease:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, mapping = aes(x = stage)) +\n  geom_bar(fill = \"steelblue\") +\n  theme_classic() +\n  labs(x = \"Stage of disease\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nNote that `ggplot` has included a separate bar for the missing values (i.e. the `NA` values). We can instruct R to ignore the missing values in the `ggplot` function by specifying the data to be a `subset` of `pbc`. The command: `subset(pbc, is.na(stage) == FALSE)` essentially creates a temporary subset of the `pbc` dataset where `stage` is not missing. Putting it all together:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = subset(pbc, is.na(stage) == FALSE), mapping = aes(x = stage)) +\n  geom_bar(fill = \"steelblue\") +\n  theme_classic() +\n  labs(x = \"Stage of disease\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n## Introducing the \"pipe\" `|>`\n\nConsider the previous example, which essentially combines two functions: `ggplot()` and `subset()` by using: `ggplot(subset())` - in other words, `subset()` has been nested within `ggplot()`. When R comes across nested functions, it will happily run the inner-most function first, then applies the outer function to the result of the inner function.\n\nWhile this code is understandable by R, one could argue this code is difficult to understand for a person. A more interpretable version of this code for a person would be:\n\n- first run the `subset()` function, **and then**\n- run the `ggplot()` function.\n\nThis can be rewritten using the `|>` symbol:\n\n```\nsubset() |> \n  ggplot()\n```\n\nThis syntax would \"pipe\" the results of the first function into the second function, and produces code that is much easier for a person to read. So our previous bar chart of stage of disease can be rewritten as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(pbc, is.na(stage) == FALSE) |>\n  ggplot(mapping = aes(x = stage)) +\n  geom_bar(fill = \"steelblue\") +\n  theme_classic() +\n  labs(x = \"Stage of disease\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nNotice that when we pipe a dataset from the `subset()` function, we no longer need to specify the name of the dataset in `ggplot()`: the dataset is inferred from the action of the `subset()` function.\n\n::: {.callout-note}\n\n- The `|>` pipe was introduced in R version 4.1.0, May 2021, and for this author (TD), has drastically improved the code that I write (and read!). When reading code that I, or others, have written using the pipe, I replace `|>` by the words **and then**. So the previous code would be read: subset the data **and then** plot the data.\n\n- You may also see `%>%` referred to as a pipe. This version of the pipe was introduced in the early 2010s, most notably in the `magrittr` package. While there are subtle differences between `|>` and `%>%`, the `|>` is the easier to use for this course, as it does not require loading any additional packages. More in-depth history can be found at [this blog post](http://adolfoalvarez.cl/blog/2021-09-16-plumbers-chains-and-famous-painters-the-history-of-the-pipe-operator-in-r/).\n:::\n\n### Using `ggplot2` to construct bar charts for two variables\n\nIn @sec-two-catvar-graph, we saw that clustered or stacked bar charts can be used to summarise two categorical variables. Remember that the *aesthetic mapping* can be used to describe how our data map to visual elements of our plot. So we can map `sex` to the `fill` attribute to summarise Stage of Disease by sex. By default, `ggplot` will produce a stacked bar chart, but we can request a clustered bar chart by specifying `position=\"dodge\"` in the `geom_bar()` statement:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(pbc, is.na(stage) == FALSE) |>\n  ggplot(mapping = aes(x = stage, fill = sex)) +\n  geom_bar(position = \"dodge\") +\n  theme_classic() +\n  labs(x = \"Stage of disease\", y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nNotice that the legend title uses the name of the `fill` variable, in this case `sex` with a lower-case s. We can specify an alternative legend title in the `labs()` statement:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(pbc, is.na(stage) == FALSE) |>\n  ggplot(mapping = aes(x = stage, fill = sex)) +\n  geom_bar(position = \"dodge\") +\n  theme_classic() +\n  labs(x = \"Stage of disease\", y = \"Frequency\", fill = \"Sex\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nA stacked bar chart can be constructed by removing the `position = dodge()` statement:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(pbc, is.na(stage) == FALSE) |>\n  ggplot(mapping = aes(x = stage, fill = sex)) +\n  geom_bar() +\n  theme_classic() +\n  labs(x = \"Stage of disease\", y = \"Frequency\", fill = \"Sex\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nFinally, we can construct a stacked relative bar chart by specifying `position = \"fill\"` in the `geom_bar()` definition:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(pbc, is.na(stage) == FALSE) |>\n  ggplot(mapping = aes(x = stage, fill = sex)) +\n  geom_bar(position = \"fill\") +\n  theme_classic() +\n  labs(x = \"Stage of disease\", y = \"Proportion\", fill = \"Sex\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n## Producing a density plot using ggplot\n\nWe can produce a density plot by specifying the variable of interest as the `x` variable, and requesting a `geom_density()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, aes(x = age)) +\n  geom_density() +\n  theme_classic() +\n  labs(x = \"Age (years)\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n## Producing a boxplot using ggplot\n\nA boxplot is constructed with a single `y` variable, and `geom_boxplot()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, aes(y = age)) +\n  geom_boxplot() +\n  theme_classic() +\n  labs(y = \"Age (years)\")\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nBy default, `ggplot2` includes arbitrary values on the x-axis. As boxplots are usually constructed only for informal data investigation, and are rarely included in formal documents, the x-axis labelling may not be an issue. However, the x-axis labelling can be removed as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pbc, aes(y = age)) +\n  geom_boxplot() +\n  theme_classic() +\n  labs(y = \"Age (years)\") +\n  theme(\n    axis.title.x = element_blank(),\n    axis.text.x = element_blank(),\n    axis.ticks.x = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](02-probability_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n\n[^1]: Note that the package is called `ggplot2` as it is a complete overhaul of the package called `ggplot`. The main function used in the `ggplot2` package is `ggplot()`. This can be confusing, but you will get used to this in time.\n[^2]: A list of available colours that can be used in `ggplot` can be found by entering the command `grDevices::colours()` in R, or by searching the web for `R colour names`.\n\n\n\n\n{{< pagebreak >}}\n\n# Activities {.unnumbered}\n\n### Activity 2.1 {-}\nResearchers at a maternity hospital in the 1970s conducted a study of low birth weight babies. Low birth weight is classified as a weight of 2500g or less at birth. Data were collected on age and smoking status of mothers and the birth weight of their babies. The file `Activity_2.1.rds` contain data on the participants in the study.\n\nCreate a 2 by 2 table to show the proportions of low birth weight babies born to mothers who smoked during pregnancy and those that did not smoke during pregnancy. Answer the following questions:\n\na) What was the total number of mothers who smoked during pregnancy?\nb) What proportion of mothers who smoked gave birth to low birth weight babies? What proportion of non-smoking mothers gave birth to low birth weight babies?\nc) Construct a stacked bar chart of the data to examine if there a difference in the proportion of babies born with a low birth weight in relation to the age group of the mother? Provide appropriate labels for the axes and give the graph an appropriate title. [Hint: plot the data using the `AgeGrp` variable]\nd) Using your answers to the question a) and b), write a brief conclusion about the relationship of low birth weight and mother’s age and smoking status.\n\n### Activity 2.2 {-}\n\nIn a Randomised Controlled Trial, the preference of a new drug was tested against an established drug by giving both drugs to each of 90 people. Assume that the two drugs are equally preferred, that is, the probability that a patient prefers either of the drugs is equal (50%). Use either the web applet, or one of the binomial functions in R to compute the probability that 60 or more patients would prefer the new drug. In completing this question, determine:\n\na)\tThe number of trials (`n` for the web applet, `size` for R)\nb)\tThe number of successes we are interested in (`x` for web applet, `x` or `q` for R)\nc)\tThe probability of success for each trial (`p` for the web applet, `prob` for R)\nd)\tThe form of the binomial function\n    - for the web applet: `P(X=x)`, `P(X≤x)` or `P(X≥x)`;\n    - for R: `dbinom`, `pbinom` or `pbinom(lower.tail=FALSE)`\ne)\tThe final probability.\n\n### Activity 2.3 {-}\n\nA case of Schistosomiasis is identified by the detection of schistosome ova in a faecal sample. In patients with a low level of infection, a field technique of faecal examination has a probability of 0.35 of detecting ova in any one faecal sample. If five samples are routinely examined for each patient, use the web applet or R to compute the probability that a patient with a low level of infection:\n\na)\tWill not be identified?\nb)\tWill be identified in two of the samples?\nc)\tWill be identified in all the samples?\nd)\tWill be identified in at most 3 of the samples?\n\n### Activity 2.4 {-}\n\nA health survey was conducted, and an extract of data has been provided in `Activity_2.4-health-survey.csv`. Categorise height into 20cm intervals, and present the height-groups appropriately.\n\n### Activity 2.5 {-}\n\nThe data in the file `Activity_2.5-LengthOfStay.rds` has information about **birth weight** and **length of stay** collected from 117 babies admitted consecutively to a hospital for surgery. For each variable:\n\na.  Plot the distribution (separately);\n\nb.  Complete the following summary statistics for each variable:\n    - mean and median;\n    - standard deviation and interquartile range.\n\nMake a decision about whether each variable is symmetric or not, and which measure of central tendency and variability should be reported.\n\n\n",
    "supporting": [
      "02-probability_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}