<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; An introduction to hypothesis testing – PHCM9795: Foundations of Biostatistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-comparing-two-means.html" rel="next">
<link href="./03-precision.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-9f93a63bed731ea7c2fe0727957fd65d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-108633c039277fca446d0fb103cb9c0a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner {
        background: #ffdc00;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-hypothesis-testing.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">An introduction to hypothesis testing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">An introduction to hypothesis testing</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PHCM9795: Foundations of Biostatistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to biostatistics and data fundamentals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical data, presentation guidelines and probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-precision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Continuous probability distributions, sampling and precision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-hypothesis-testing.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">An introduction to hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-comparing-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-testing-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing for categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-correlation-and-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-non-parametrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing non-normal data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">An introduction to sample size estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98.1-appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#optional-readings" id="toc-optional-readings" class="nav-link" data-scroll-target="#optional-readings">Optional readings</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">4.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#worked-example" id="toc-worked-example" class="nav-link" data-scroll-target="#worked-example">Worked example</a></li>
  </ul></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions"><span class="header-section-number">4.2</span> Research questions</a></li>
  <li><a href="#using-confidence-intervals-to-assess-research-questions" id="toc-using-confidence-intervals-to-assess-research-questions" class="nav-link" data-scroll-target="#using-confidence-intervals-to-assess-research-questions"><span class="header-section-number">4.3</span> Using confidence intervals to assess research questions</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><span class="header-section-number">4.4</span> Hypothesis testing</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  </ul></li>
  <li><a href="#the-hypothesis-testing-framework" id="toc-the-hypothesis-testing-framework" class="nav-link" data-scroll-target="#the-hypothesis-testing-framework"><span class="header-section-number">4.5</span> The hypothesis testing framework</a></li>
  <li><a href="#the-test-statistic" id="toc-the-test-statistic" class="nav-link" data-scroll-target="#the-test-statistic"><span class="header-section-number">4.6</span> The test statistic</a></li>
  <li><a href="#the-p-value" id="toc-the-p-value" class="nav-link" data-scroll-target="#the-p-value"><span class="header-section-number">4.7</span> The P-value</a></li>
  <li><a href="#effect-size" id="toc-effect-size" class="nav-link" data-scroll-target="#effect-size"><span class="header-section-number">4.8</span> Effect size</a></li>
  <li><a href="#statistical-significance-vs-practical-importance" id="toc-statistical-significance-vs-practical-importance" class="nav-link" data-scroll-target="#statistical-significance-vs-practical-importance"><span class="header-section-number">4.9</span> Statistical significance vs practical importance</a></li>
  <li><a href="#errors-in-significance-testing" id="toc-errors-in-significance-testing" class="nav-link" data-scroll-target="#errors-in-significance-testing"><span class="header-section-number">4.10</span> Errors in significance testing</a></li>
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test"><span class="header-section-number">4.11</span> One-sample t-test</a>
  <ul class="collapse">
  <li><a href="#worked-example-1" id="toc-worked-example-1" class="nav-link" data-scroll-target="#worked-example-1">Worked Example</a></li>
  </ul></li>
  <li><a href="#one-and-two-tailed-tests" id="toc-one-and-two-tailed-tests" class="nav-link" data-scroll-target="#one-and-two-tailed-tests"><span class="header-section-number">4.12</span> One and two tailed tests</a></li>
  <li><a href="#a-note-on-p-values-displayed-by-software" id="toc-a-note-on-p-values-displayed-by-software" class="nav-link" data-scroll-target="#a-note-on-p-values-displayed-by-software"><span class="header-section-number">4.13</span> A note on P-values displayed by software</a></li>
  <li><a href="#decision-tree" id="toc-decision-tree" class="nav-link" data-scroll-target="#decision-tree"><span class="header-section-number">4.14</span> Decision Tree</a></li>
  <li><a href="#indigenous-data-sovereignty-and-governance-the-australian-context" id="toc-indigenous-data-sovereignty-and-governance-the-australian-context" class="nav-link" data-scroll-target="#indigenous-data-sovereignty-and-governance-the-australian-context"><span class="header-section-number">4.15</span> Indigenous data sovereignty and governance: the Australian context</a>
  <ul class="collapse">
  <li><a href="#the-problem-of-deficit-based-data-narratives" id="toc-the-problem-of-deficit-based-data-narratives" class="nav-link" data-scroll-target="#the-problem-of-deficit-based-data-narratives">The Problem of Deficit-Based Data Narratives</a></li>
  <li><a href="#key-principles-for-indigenous-data-management" id="toc-key-principles-for-indigenous-data-management" class="nav-link" data-scroll-target="#key-principles-for-indigenous-data-management">Key Principles for Indigenous Data Management</a></li>
  <li><a href="#fair-and-care-principles" id="toc-fair-and-care-principles" class="nav-link" data-scroll-target="#fair-and-care-principles">FAIR and CARE Principles</a></li>
  <li><a href="#protecting-indigenous-data-sovereignty-rights-in-research" id="toc-protecting-indigenous-data-sovereignty-rights-in-research" class="nav-link" data-scroll-target="#protecting-indigenous-data-sovereignty-rights-in-research">Protecting Indigenous Data Sovereignty Rights in Research</a></li>
  </ul></li>
  <li><a href="#jamovi-notes" id="toc-jamovi-notes" class="nav-link" data-scroll-target="#jamovi-notes">Jamovi notes</a>
  <ul class="collapse">
  <li><a href="#one-sample-t-test-1" id="toc-one-sample-t-test-1" class="nav-link" data-scroll-target="#one-sample-t-test-1"><span class="header-section-number">4.16</span> One sample t-test</a></li>
  </ul></li>
  <li><a href="#r-notes" id="toc-r-notes" class="nav-link" data-scroll-target="#r-notes">R notes</a>
  <ul class="collapse">
  <li><a href="#one-sample-t-test-2" id="toc-one-sample-t-test-2" class="nav-link" data-scroll-target="#one-sample-t-test-2"><span class="header-section-number">4.17</span> One sample t-test</a></li>
  </ul></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a>
  <ul class="collapse">
  <li><a href="#activity-4.1" id="toc-activity-4.1" class="nav-link" data-scroll-target="#activity-4.1">Activity 4.1</a></li>
  <li><a href="#activity-4.2" id="toc-activity-4.2" class="nav-link" data-scroll-target="#activity-4.2">Activity 4.2</a></li>
  <li><a href="#activity-4.3" id="toc-activity-4.3" class="nav-link" data-scroll-target="#activity-4.3">Activity 4.3</a></li>
  <li><a href="#activity-4.4" id="toc-activity-4.4" class="nav-link" data-scroll-target="#activity-4.4">Activity 4.4</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>By the end of this module you will be able to:</p>
<ul>
<li>Formulate a research question and present it as a null and alternative hypothesis;</li>
<li>Understand the role of confidence intervals in assessing research questions;</li>
<li>Explain the general framework of hypothesis testing;</li>
<li>Interpret P-values as measures of evidence;</li>
<li>Distinguish between statistical significance and practical importance;</li>
<li>Perform and interpret a one-sample t-test;</li>
<li>Explain the concepts of one-tailed and two-tailed statistical tests, and determine when each is appropriate;</li>
<li>Report the results of hypothesis tests clearly, accurately, and in plain language.</li>
</ul>
</section>
<section id="optional-readings" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="optional-readings">Optional readings</h2>
<p><span class="citation" data-cites="kirkwood_sterne01">Kirkwood and Sterne (<a href="references.html#ref-kirkwood_sterne01" role="doc-biblioref">2001</a>)</span>; Chapter 8. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728">[UNSW Library Link]</a></p>
<p><span class="citation" data-cites="bland15">Bland (<a href="references.html#ref-bland15" role="doc-biblioref">2015</a>)</span>; Sections 9.1 to 9.7; Sections 10.1 and 10.2. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730">[UNSW Library Link]</a></p>
</section>
<section id="introduction" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">4.1</span> Introduction</h2>
<p>In earlier modules, we examined sampling and how summary statistics can be used to make inferences about a population parameter. For example, we can use the sample mean <span class="math inline">\(\bar{x}\)</span> to make inferences about <span class="math inline">\(\mu\)</span>, the true mean of the population from which a sample is drawn. In this module, we introduce hypothesis testing as the basis of the statistical tests that are important for reporting results from research and surveillance studies, and that you will be learning in the remainder of this course.</p>
<p>We use hypothesis testing to answer questions such as whether two groups have different health outcomes or whether there is an association between a treatment and a health outcome. For example, we may want to know:</p>
<ul>
<li>whether a safety program has been effective in reducing injuries in a factory, i.e.&nbsp;whether the frequency of injuries in the group who attended a safety program is lower than in the group who did not receive the safety program;</li>
<li>whether a new drug is more effective in reducing blood pressure than a conventional drug, i.e.&nbsp;whether the mean blood pressure in the group receiving the new drug is lower than the mean blood pressure in the group receiving the conventional medication;</li>
<li>whether an environmental exposure increases the risk of a disease, i.e.&nbsp;whether the frequency of disease is higher in the group who have been exposed to an environmental factor than in the non-exposed group.</li>
</ul>
<p>We may also want to know something about a single group. For example, whether the mean blood pressure of a sample is the same as the general population.</p>
<p>These questions can be answered by setting up a null hypothesis and an alternative hypothesis, and performing a hypothesis test (also known as a significance test). In this module we focus on testing hypotheses about a single population mean, using confidence intervals and the one-sample t-test.</p>
<section id="worked-example" class="level3">
<h3 class="anchored" data-anchor-id="worked-example">Worked example</h3>
<p>In this module, we will revisit the Pima example from Module 3 (<code>mod03_blood_pressure.csv</code>). A sample of 733 female Pima indigenous Americans was taken, and their diastolic blood pressure was measured (among other measures). We saw in Module 3 that a density plot demonstrates that the data are approximately normally distributed, and the mean diastolic blood pressure was estimated as 72.4 mmHg with a 95% confidence interval from 71.5 to 73.3 mmHg.</p>
</section>
</section>
<section id="research-questions" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="research-questions"><span class="header-section-number">4.2</span> Research questions</h2>
<p>A research question is an open, neutral question that states what we want to find out - often phrased using everyday language. Research questions guide study design and data collection, and do not presuppose an answer. Using our Pima example, a research question could be posed:</p>
<ul>
<li>Do Pima women have the same mean diastolic blood pressure as the general US population?</li>
</ul>
<p>A useful way of structuring research questions in health research is the PECO framework:</p>
<ul>
<li>Population: Who is being studied?</li>
<li>Exposure: What exposure, risk factor, or condition is of interest?</li>
<li>Comparator: What is the exposure being compared against?</li>
<li>Outcome: What outcome is being measured?</li>
</ul>
<p>In the example above:</p>
<ul>
<li>Population: Pima women</li>
<li>Comparator: General US population</li>
<li>Outcome: Diastolic blood pressure</li>
</ul>
<p>Note there as there is only one group here, there is no “exposure”.</p>
</section>
<section id="using-confidence-intervals-to-assess-research-questions" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="using-confidence-intervals-to-assess-research-questions"><span class="header-section-number">4.3</span> Using confidence intervals to assess research questions</h2>
<p>We can use the 95% confidence interval to <strong>informally</strong> assess research questions. For example, we can use a 95% confidence interval for the mean to assess whether the population mean is consistent with a hypothesised value. A confidence interval gives a range of plausible values for the true population mean, based on the sample data, and we can compare the confidence interval with the hypothesised value.</p>
<p>If a hypothesised mean lies:</p>
<ul>
<li><em>outside</em> the confidence interval, there is <em>informal evidence</em> that the population mean differs from the hypothesised mean</li>
<li><em>inside</em> the confidence interval, there is <em>no informal evidence</em> that the population mean differs from the hypothesised mean</li>
</ul>
<p>Note that a confidence interval does not provide a quantitative measure of evidence against a null hypothesis; it supports only an informal comparison. Formal hypothesis testing is required to quantify the level of evidence.</p>
</section>
<section id="hypothesis-testing" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="hypothesis-testing"><span class="header-section-number">4.4</span> Hypothesis testing</h2>
<p>In statistics, a hypothesis is a claim about a population parameter. Hypothesis testing is a formal procedure used to decide between two competing claims about a population parameter. These two claims are known as:</p>
<ul>
<li>the <strong>null hypothesis</strong></li>
<li>the <strong>alternative hypothesis</strong></li>
</ul>
<p>Hypothesis testing is a statistical technique that is used to quantify the evidence against a null hypothesis.</p>
<p>The <strong>null hypothesis</strong>, written H<sub>0</sub>, represents the hypothesis of no difference, no change, no effect. It is often described as the <em>boring</em> or <em>skeptical</em> hypothesis</p>
<p>The <strong>alternative hypothesis</strong>, written H<sub>A</sub>, represents the hypothesis of a difference, change or effect.</p>
<p>Note that hypotheses always refer to a <strong>population</strong>, not a sample.</p>
<section id="example" class="level3">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<p>In our example, our research question is: do Pima women have the same mean diastolic blood pressure as the general US population?</p>
<p>To test this research question, we will need a value for the mean diastolic blood pressure of the general US population. We will use the results from a large-scale population survey, and state that the US population has a mean diastolic blood pressure of 71mmHg.</p>
<p>Our hypotheses then, could be written as:</p>
<ul>
<li>H<sub>0</sub>: <span class="math inline">\(\mu = 71\)</span></li>
<li>H<sub>A</sub>: <span class="math inline">\(\mu \ne 71\)</span></li>
</ul>
<p>where <span class="math inline">\(\mu\)</span> is the true population mean diastolic blood pressure of Pima women.</p>
<p>These hypotheses are very formal, and it may be easier to think of them as:</p>
<ul>
<li>H<sub>0</sub>: The mean diastolic blood pressure of Pima women is 71 mmHg.</li>
<li>H<sub>A</sub>: The mean diastolic blood pressure of Pima women is not 71 mmHg.</li>
</ul>
</section>
</section>
<section id="the-hypothesis-testing-framework" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="the-hypothesis-testing-framework"><span class="header-section-number">4.5</span> The hypothesis testing framework</h2>
<p>The recommended steps in a hypothesis test are as follows:</p>
<ol start="0" type="1">
<li>Exploratory data analysis
<ul>
<li>examine distributions, check for missing and/or unusual data</li>
<li>understand the structure of the data (sample size, groups, variables)</li>
<li>based on above, choose an appropriate statistical test</li>
<li>check the assumptions required for the chosen test</li>
<li>frame the research question using the PECO framework:
<ul>
<li>Population, Exposure, Comparator, Outcome</li>
</ul></li>
</ul></li>
<li>Specify the Null and Alternative Hypotheses</li>
<li>Perform the statistical test, and obtain test statistic, degrees of freedom and P-value</li>
<li>Calculate descriptive statistics</li>
<li>Summarise the results including
<ul>
<li>Summary statistics (overall or by group)</li>
<li>A statement about the evidence</li>
<li>Estimate of effect including:
<ul>
<li>Direction</li>
<li>Point estimate</li>
<li>95% confidence interval</li>
</ul></li>
</ul></li>
<li>Provide a clear and concise conclusion, written in plain English, that summarises the results of the study in terms of the wider population, not just the sample</li>
</ol>
</section>
<section id="the-test-statistic" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="the-test-statistic"><span class="header-section-number">4.6</span> The test statistic</h2>
<p>After setting up our null and alternative hypotheses, we use the data to generate a test statistic. The particular test statistic differs depending on the type of data being analysed (e.g.&nbsp;continuous or categorical), the study design (e.g.&nbsp;paired or independent) and the question being asked.</p>
<p>The test statistic is then compared to a known distribution to calculate the probability of observing a test statistic which is as large or larger than the observed test statistic, if the null hypothesis was true. The probability is known as the P-value.</p>
</section>
<section id="the-p-value" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="the-p-value"><span class="header-section-number">4.7</span> The P-value</h2>
<p>Formally, the P-value is interpreted as the probability of observing data like ours, or more extreme, if the null hypothesis was true.</p>
<p>If the P-value is small, it is unlikely that we would observe data like ours or more extreme if the null hypothesis was true. In other words, our data are not consistent with the null hypothesis, and we conclude that we have evidence against the null hypothesis. If the P-value is not small, the probability of observing data like ours or more extreme is not unlikely. We therefore have little or no evidence against the null hypothesis. In hypothesis testing, the null hypothesis cannot be proven or accepted; we can only find evidence to refute the null hypothesis.</p>
<p>To summarise:</p>
<ul>
<li>a small P-value gives us evidence against the null hypothesis;</li>
<li>a P-value that is not small provides little or no evidence against null hypothesis;</li>
<li>the smaller the P-value, the stronger the evidence against the null hypothesis.</li>
</ul>
<p>Historically, a value of 0.05 has been used as a cut-point for finding evidence against the null hypothesis. A P-value less than 0.05 would be interpreted as “statistically significant”, and would allow us to “reject the null hypothesis”. A P-value greater than 0.05 would be interpreted as “not significant”, and we would “fail to reject the null hypothesis”. This arbitrary dichotomy is overly simplistic, and a more nuanced view is now recommended. Recommended interpretations for P-values are given in <a href="#tbl-4-1" class="quarto-xref">Table&nbsp;<span>4.1</span></a>.</p>
<div class="cell">
<div id="tbl-4-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-4-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.1: Interpretation of P-values
</figcaption>
<div aria-describedby="tbl-4-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_0sjxuiexkaf969ez4v8r = TinyTable.createTableFunctions("tinytable_0sjxuiexkaf969ez4v8r");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '5', j: 1 }, { i: '5', j: 2 } ], css_id: 'tinytable_css_qfmsebwfddsp1o7zyx1l',}, 
          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_qfsap6qrvkxb1u9naiv7',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_0sjxuiexkaf969ez4v8r.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_0sjxuiexkaf969ez4v8r td.tinytable_css_qfmsebwfddsp1o7zyx1l, #tinytable_0sjxuiexkaf969ez4v8r th.tinytable_css_qfmsebwfddsp1o7zyx1l {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }
    #tinytable_0sjxuiexkaf969ez4v8r td.tinytable_css_qfsap6qrvkxb1u9naiv7, #tinytable_0sjxuiexkaf969ez4v8r th.tinytable_css_qfsap6qrvkxb1u9naiv7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_0sjxuiexkaf969ez4v8r" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1">P-value</th>
                <th scope="col" data-row="0" data-col="2">Strength of evidence</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">&lt;0.001</td>
                  <td data-row="1" data-col="2">Very strong evidence</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1">0.001 to &lt;0.01</td>
                  <td data-row="2" data-col="2">Strong evidence</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">0.01 to &lt;0.05</td>
                  <td data-row="3" data-col="2">Evidence</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1">0.05 to &lt;0.1</td>
                  <td data-row="4" data-col="2">Weak evidence</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">≥0.1</td>
                  <td data-row="5" data-col="2">Little or no evidence</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</figure>
</div>
</div>
<p>P-values are most commonly generated using statistical software, however historically, statistical tables were used to determine the P-value from the test-statistic.</p>
</section>
<section id="effect-size" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="effect-size"><span class="header-section-number">4.8</span> Effect size</h2>
<p>In hypothesis testing, P-values convey only part of the information about the hypothesis and need to be accompanied by an estimation of the effect size. The effect size describes how different our sample is from the hypothesised population parameter. The effect size depends on the study design and the type of outcome variable being analysed, and should always be presented with a 95% confidence interval (where possible).</p>
<p>In our blood pressure example, the sample mean and its 95% confidence interval represent the effect size. Alternatively, the difference between the sample mean and the hypothesised mean (and the 95% confidence interval) could be presented.</p>
<p>Reporting the effect size enables others to judge whether a result that has evidence of a difference is also a practically important finding. The effect size provides information to help others decide whether the observed effect is large and important enough to warrant a change in current health care practice, is equivocal and suggests a need for further research, or is small and practically unimportant.</p>
</section>
<section id="statistical-significance-vs-practical-importance" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="statistical-significance-vs-practical-importance"><span class="header-section-number">4.9</span> Statistical significance vs practical importance</h2>
<p>When applying statistical methods in health and medical research, we need to make an informed decision about whether the effect size that led to a statistically significant finding is also practically important (see <a href="#fig-practical-importance" class="quarto-xref">Figure&nbsp;<span>4.1</span></a>). The decision about whether a statistically significant result is also practically important depends on expert knowledge, and is best made by others with experience in the field.</p>
<div class="cell" title="Statistical significance vs. clinical importance (adapted from Armitage P, Berry G, Matthews JNS. (2001))">
<div class="cell-output-display">
<div id="fig-practical-importance" class="quarto-float quarto-figure quarto-figure-center anchored" width="672" alt="Five vertical confidence interval plots illustrate the distinction between statistical significance and practical importance. A solid horizontal line at zero represents the null hypothesis, while a dashed horizontal line above zero marks the threshold for a clinically or practically important effect. Intervals (a) and (b) lie entirely above zero, indicating statistically significant results; however, only (a) is clearly practically important because the entire interval is above the importance threshold, while (b) includes values of uncertain practical importance. Interval (c) is statistically significant because it does not cross zero, but it lies below the practical importance threshold, indicating a statistically significant yet clinically unimportant effect. Interval (d) crosses zero and spans both harmful and beneficial values, representing a statistically non-significant and inconclusive result. Interval (e) also crosses zero but remains below the practical importance threshold, suggesting a true negative result with no clinically important effect.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-practical-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-hypothesis-testing_files/figure-html/fig-practical-importance-1.png" id="fig-practical-importance" class="img-fluid figure-img" alt="Five vertical confidence interval plots illustrate the distinction between statistical significance and practical importance. A solid horizontal line at zero represents the null hypothesis, while a dashed horizontal line above zero marks the threshold for a clinically or practically important effect. Intervals (a) and (b) lie entirely above zero, indicating statistically significant results; however, only (a) is clearly practically important because the entire interval is above the importance threshold, while (b) includes values of uncertain practical importance. Interval (c) is statistically significant because it does not cross zero, but it lies below the practical importance threshold, indicating a statistically significant yet clinically unimportant effect. Interval (d) crosses zero and spans both harmful and beneficial values, representing a statistically non-significant and inconclusive result. Interval (e) also crosses zero but remains below the practical importance threshold, suggesting a true negative result with no clinically important effect." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-practical-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1
</figcaption>
</figure>
</div>
</div>
</div>
<p>It is possible when conducting significance tests, particularly in very large studies, that a small difference provides strong evidence of an effect due to increased precision from large sample sizes. For example, in a large study of over 1000 patients, a new medication may be found to lower blood pressure by an average of 1 mmHg more than a currently accepted drug, providing strong evidence of a difference (P &lt; 0.01). However, such a small reduction in blood pressure would be unlikely to be practically important. The cost and potential side effects of the new medication would need to be weighed against this very small average benefit. In this situation, despite strong statistical evidence, the finding would not be practically important. This is the situation described in scenario (c) of <a href="#fig-practical-importance" class="quarto-xref">Figure&nbsp;<span>4.1</span></a>.</p>
<p>Conversely, it is possible to obtain a large, practically important difference between groups that provides little evidence of a difference.</p>
<p>For example, consider a small study to measure the rate of hospital admissions following presentation to the Emergency Department. We may find that 80% of children who present to the Emergency Department are admitted before the intervention, compared to only 65% of children after the intervention. However, the P value may be calculated as 0.38, providing no evidence of a difference. This may be because only a small number of participants were recruited in each period. Here, the reduction in the admission rate by 15% represents a practically important difference, but not statistically significant. This situation is represented in scenario (d) of <a href="#fig-practical-importance" class="quarto-xref">Figure&nbsp;<span>4.1</span></a>.</p>
<p>The important thing to remember is that statistical significance does not always correspond to practical importance. A statistically significant result may be practically unimportant, and a statistically non-significant results may be practically important.</p>
</section>
<section id="errors-in-significance-testing" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="errors-in-significance-testing"><span class="header-section-number">4.10</span> Errors in significance testing</h2>
<p>There are two conclusions we can draw when conducting a hypothesis test: if the P-value is small, there is strong evidence against the null hypothesis and we reject the null hypothesis. If the P-value is not small, there is little evidence against the null hypothesis and we fail to reject the null hypothesis. As discussed above, the “small” cut-point for the P-value is often taken as 0.05. We refer to this value as <span class="math inline">\(\alpha\)</span> (alpha).</p>
<p>We can conduct a thought experiment and compare our hypothesis test conclusion to reality. In reality, either the null hypothesis is true, or it is false. Of course, if we knew what reality was, we would not need to conduct a hypothesis test. But we can compare our possible hypothesis test conclusions to the true (unobserved) reality.</p>
<p>If the null hypothesis was true in reality, our hypothesis test can fail to reject the null hypothesis – this would be a correct conclusion. However, the hypothesis test could lead us to rejecting the null hypothesis – this would be an incorrect conclusion. We call this scenario a Type I error, and it has a probability of <span class="math inline">\(\alpha\)</span>.</p>
<p>The other situation is where, in reality, the null hypothesis is false. A correct conclusion would be where our hypothesis test rejects the null hypothesis. However, if our hypothesis test fails to reject the null hypothesis, we have made a Type II error. The probability of making a Type II error is denoted <span class="math inline">\(\beta\)</span> (beta). We will see in Module 10 that <span class="math inline">\(\beta\)</span> is determined by the size of the study.</p>
<p>The error in falsely rejecting the null hypothesis when it is true (type I error), or in falsely accepting the null hypothesis when it is not true (type II error) is summarised in <a href="#tbl-mod4-alpha-beta" class="quarto-xref">Table&nbsp;<span>4.2</span></a>. We will return to these concepts in Module 10, when discussing how to determine the appropriate sample size of a study.</p>
<div id="tbl-mod4-alpha-beta" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mod4-alpha-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.2: Comparison of study result with the truth
</figcaption>
<div aria-describedby="tbl-mod4-alpha-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><strong>Effect in reality</strong></th>
<th style="text-align: center;"><strong>No effect in reality</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Evidence was found</strong></td>
<td style="text-align: center;">Correct: Power (<span class="math inline">\(1 - \beta\)</span>)</td>
<td style="text-align: center;">Error: <span class="math inline">\(\alpha\)</span></td>
</tr>
<tr class="even">
<td><strong>No evidence was found</strong></td>
<td style="text-align: center;">Error: <span class="math inline">\(\beta\)</span></td>
<td style="text-align: center;">Correct</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="one-sample-t-test" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="one-sample-t-test"><span class="header-section-number">4.11</span> One-sample t-test</h2>
<p>A one-sample t-test tests whether a sample mean is different to a hypothesised value. The t-distribution and its relation to normal distribution has been discussed in detailed in Module 3.</p>
<p>In a one-sample t-test, a t-value is computed as the sample mean divided by the standard error of the mean. The significance of the t-value is then computed using software, or can be obtained from a statistical table.</p>
<p>The principles of this test can be used for applications such as testing whether the mean of a sample is different from a known population mean, for example testing whether the IQ of a group of children is different from the population mean of 100 IQ points or testing whether the number of average hours worked in an adult sample is different from the population mean of 38 hours.</p>
<section id="worked-example-1" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-1">Worked Example</h3>
<p>The mean diastolic blood pressure (BP) of the general US population is known to be 71 mm Hg. The diastolic blood pressure of 733 female Pima indigenous Americans was measured and a density plot showed that the data were approximately normally distributed. The mean diastolic blood pressure in the sample was 72.4 mm Hg with a standard deviation of 12.38 mm Hg.</p>
<p>We can use jamovi or R to conduct a one sample t-test using the data available (<code>mod04_blood_pressure.csv</code>). The results from this test are summarised below.</p>
<table class="caption-top table">
<caption>Summary of blood pressure from female Pima indigenous Americans</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>n</th>
<th>Mean</th>
<th>Standard deviation</th>
<th>Standard error</th>
<th>95% confidence interval of the mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>733</td>
<td>72.4</td>
<td>12.38</td>
<td>0.46</td>
<td>71.5 to 73.3</td>
</tr>
</tbody>
</table>
<p>The test statistic for the one-sample t-test is calculated as t<sub>732</sub>=3.07, with a P-value of 0.002.</p>
<p>The mean diastolic blood pressure of females from Pima is estimated as 72.4 mmHg (95% CI: 71.5 to 73.3 mmHg), which is higher than that of the general US population. Note that this interval does not contain the mean of the general US population (71 mm Hg), providing some indication that the mean diastolic blood pressure of female Pima people is higher than that of the general US population.</p>
<p>The result from the formal hypothesis test gives strong evidence that the mean diastolic BP of the female Pima people is higher than that of the general US population (t<sub>732</sub>=3.07, P=0.002).</p>
</section>
</section>
<section id="one-and-two-tailed-tests" class="level2" data-number="4.12">
<h2 data-number="4.12" class="anchored" data-anchor-id="one-and-two-tailed-tests"><span class="header-section-number">4.12</span> One and two tailed tests</h2>
<p>Most statistical tests are two tailed tests, that is, we conduct a test that allows for the summary statistic in the group of interest to be either higher or lower than in the comparison group. For a t-test, this requires that we obtain a two-tailed P value which gives us the probability of the t-value being in either one of the two tails of the t-distribution as shown in <a href="#fig-two-tailed-test" class="quarto-xref">Figure&nbsp;<span>4.2</span></a>. The shaded regions show the t values that indicate a P value less than 0.05.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-two-tailed-test" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A symmetric bell-shaped t-distribution centred at zero. Both tails are shaded beyond the critical values, illustrating the rejection regions for a two-tailed hypothesis test with alpha equal to 0.05.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-tailed-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/mod04/two-tailed-test.png" class="img-fluid figure-img" style="width:66.0%" alt="A symmetric bell-shaped t-distribution centred at zero. Both tails are shaded beyond the critical values, illustrating the rejection regions for a two-tailed hypothesis test with alpha equal to 0.05.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-tailed-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: P-value for a 2-tailed test
</figcaption>
</figure>
</div>
</div>
</div>
<p>Occasionally, one tailed tests are conducted in which the summary statistic in the group of interest can only be higher or lower than the comparison group, i.e.&nbsp;a difference is specified to occur in one direction only. In most studies, two tailed tests of significance are used to allow for the possibility that the effect size could occur in either direction. In clinical trials, this would mean allowing for a result that can indicate a benefit or an adverse effect in response to a new treatment. In epidemiological studies, two tailed tests are used to allow for the fact that exposure to a factor of interest may be adverse or may be beneficial. This conservative approach is usually adopted to prevent missing important effects that occur in the opposite direction to that expected by the researchers.</p>
</section>
<section id="a-note-on-p-values-displayed-by-software" class="level2" data-number="4.13">
<h2 data-number="4.13" class="anchored" data-anchor-id="a-note-on-p-values-displayed-by-software"><span class="header-section-number">4.13</span> A note on P-values displayed by software</h2>
<p>You will often see P-values generated by statistical software presented as 0.000 or 0.0000. As P-values can never be equal to zero, any P-value displayed in this way should be converted to &lt;0.001 or &lt;0.0001 respectively (i.e.&nbsp;replace the last 0 with a 1, and use the less-than symbol).</p>
<p>R can display P-values in a very cryptic way: <span class="math inline">\(\text{6.478546e-05}\)</span> for example. This is translated as:</p>
<p><span class="math display">\[\begin{aligned}
6.478546e-05 &amp;= 6.478546 \times 10^{-5} \\
  &amp;= 6.478546 \times 0.00001 \\
  &amp;= 0.00006478546
\end{aligned}\]</span></p>
<p>Such a P-value should be presented as P&lt;0.0001.</p>
</section>
<section id="decision-tree" class="level2" data-number="4.14">
<h2 data-number="4.14" class="anchored" data-anchor-id="decision-tree"><span class="header-section-number">4.14</span> Decision Tree</h2>
<p>In the following modules in this course, several formal statistical tests will be described to analyse different types of data sets that have been collected to test set null hypotheses. It is important that the correct statistical test is selected to generate P-values and estimate effect size. If an incorrect statistical test is used, the assumptions of the test may be violated, the effect size may be biased and the P value generated may be incorrect.</p>
<p>Selecting the correct test to use in each situation depends on the study design and the nature of the variables collected. Figure 1 in the Appendix shows a decision tree which enables you to decide the type of test to select based on the nature of the data.</p>
</section>
<section id="indigenous-data-sovereignty-and-governance-the-australian-context" class="level2" data-number="4.15">
<h2 data-number="4.15" class="anchored" data-anchor-id="indigenous-data-sovereignty-and-governance-the-australian-context"><span class="header-section-number">4.15</span> Indigenous data sovereignty and governance: the Australian context</h2>
<p>The issue of data sovereignty was raised in Module 3, and here we will discuss how this concept applies in the Australian context.</p>
<p>Indigenous data encompasses information or knowledge in any format or medium that is about, or may affect, Aboriginal and Torres Strait Islander peoples, either collectively or individually. <span class="citation" data-cites="walter_etal21">(<a href="references.html#ref-walter_etal21" role="doc-biblioref">Walter et al. 2021</a>)</span> Indigenous Data Sovereignty specifically refers to the right of Aboriginal and Torres Strait Islander peoples, communities, and organisations to maintain, control, protect, develop, and use data as it relates to them. Data practices must support and enhance Indigenous collective well-being.</p>
<p>Indigenous Data Governance provides the practical mechanisms through which sovereignty is enacted. It consists of formal systems that assert Indigenous data interests regarding how data is accessed and used, ensuring that practices reflect Indigenous priorities, values, culture, and diversity.<span class="citation" data-cites="walter_etal21">(<a href="references.html#ref-walter_etal21" role="doc-biblioref">Walter et al. 2021</a>)</span> Importantly, Indigenous Data Sovereignty is practised through Indigenous data governance, making governance the operational expression of sovereignty principles.</p>
<section id="the-problem-of-deficit-based-data-narratives" class="level3">
<h3 class="anchored" data-anchor-id="the-problem-of-deficit-based-data-narratives">The Problem of Deficit-Based Data Narratives</h3>
<p>A major challenge in Australian data collections is that First Nations peoples are often framed as the “object of study” rather than as active participants in research. Data frequently focuses on poor outcomes across health, education, and economic participation, creating what has been termed the “5D data” narrative: disparity, deprivation, disadvantage, dysfunction, and difference. This approach has been further characterised as BADDR Data: Blaming, Aggregate, Decontextualised, Deficit, and Restricted.<span class="citation" data-cites="walter_etal21">(<a href="references.html#ref-walter_etal21" role="doc-biblioref">Walter et al. 2021</a>)</span> Such framings perpetuate harmful stereotypes and fail to capture the strengths, resilience, and diversity of Indigenous communities.</p>
</section>
<section id="key-principles-for-indigenous-data-management" class="level3">
<h3 class="anchored" data-anchor-id="key-principles-for-indigenous-data-management">Key Principles for Indigenous Data Management</h3>
<p>Indigenous data management in Australia operates according to several foundational principles. Indigenous data should be reflective of Aboriginal and Torres Strait Islander interests, values, and cultural ways, ensuring cultural appropriateness throughout the data lifecycle. Data must be accessible and appropriate, meeting Indigenous needs rather than serving external agendas. Collection practices must incorporate free, prior, and informed consent, with respect for confidentiality maintained throughout.</p>
<p>Secure storage of Indigenous data is essential, as is the requirement that data be returned to communities in an easily understood and meaningful way. Interpretation of Indigenous data should be conducted by Aboriginal and Torres Strait Islander experts who possess the cultural knowledge necessary for appropriate analysis. Finally, data use must advance self-determination and development, and only proceed in ways that Indigenous peoples agree to.</p>
</section>
<section id="fair-and-care-principles" class="level3">
<h3 class="anchored" data-anchor-id="fair-and-care-principles">FAIR and CARE Principles</h3>
<p>The Australian Open Data infrastructure incorporates FAIR principles (Findable, Accessible, Interoperable, Reusable) for scientific data, which aim to maximise data use and reuse. However, these principles do not mention or address the specific concerns of Indigenous peoples. To address this gap, the CARE Principles for Indigenous Data Governance have been developed to complement FAIR principles.</p>
<p>The CARE framework consists of four key components:</p>
<ul>
<li><p>Collective Benefit emphasises inclusive development and innovation, improved governance and citizen engagement, and equitable outcomes.</p></li>
<li><p>Authority to Control focuses on recognising Indigenous rights and interests, supporting data for governance, and enabling the governance of data itself.</p></li>
<li><p>Responsibility calls for positive relationships, expanding capability and capacity, and incorporating Indigenous worldviews into data practices.</p></li>
<li><p>Ethics stresses minimising harm and maximising benefit, promoting justice, and careful consideration of future data uses.</p></li>
</ul>
<p>This framework enables the enactment of FAIR principles but with appropriate care and attention to Indigenous rights and interests.<span class="citation" data-cites="walter_etal21">(<a href="references.html#ref-walter_etal21" role="doc-biblioref">Walter et al. 2021</a>)</span></p>
</section>
<section id="protecting-indigenous-data-sovereignty-rights-in-research" class="level3">
<h3 class="anchored" data-anchor-id="protecting-indigenous-data-sovereignty-rights-in-research">Protecting Indigenous Data Sovereignty Rights in Research</h3>
<p>Aboriginal and Torres Strait Islander peoples have the right to decide how Indigenous data is used and stored.[<span class="citation" data-cites="lowitjainstitute21">Lowitja Institute (<a href="references.html#ref-lowitjainstitute21" role="doc-biblioref">2021</a>)</span>]<span class="citation" data-cites="nationalindigenousaustraliansagency24">(<a href="references.html#ref-nationalindigenousaustraliansagency24" role="doc-biblioref">National Indigenous Australians Agency 2024</a>)</span> Formal agreements protecting Indigenous Data Sovereignty should be established at the outset of any research project. Such agreements must cover intellectual property rights, data collection procedures, retention and access arrangements, and management protocols for all data arising from the research. These agreements must also specify actions that Aboriginal and Torres Strait Islander peoples, communities, and organisations can take if commitments are not met. Crucially, these agreements must be clearly understood and formally endorsed by appropriate representatives of the involved Aboriginal and Torres Strait Islander peoples, communities, and organisations.</p>
<p>First Nations peoples have the right to lead and participate at all stages of the research process, including planning, data collection, analysis, dissemination of results, return of data, and ongoing access to data. Researchers bear responsibility for providing appropriate information to promote full and effective Indigenous leadership in data collection. They must also provide opportunities for communities to assess data collection, storage, and governance arrangements, including confidentiality protections. Indigenous peoples must have opportunities to engage in the development, design, collection, analysis, and reporting of data, including involvement in the development of appropriate indicators and surveys applicable to local contexts.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="jamovi-notes" class="level1 unnumbered">
<h1 class="unnumbered">Jamovi notes</h1>
<section id="one-sample-t-test-1" class="level2" data-number="4.16">
<h2 data-number="4.16" class="anchored" data-anchor-id="one-sample-t-test-1"><span class="header-section-number">4.16</span> One sample t-test</h2>
<p>We will use data from <code>mod04_blood_pressure.csv</code> to demonstrate how a one-sample t-test is conducted in Jamovi. To perform the test, go to <strong>Analyses &gt; T-Tests &gt; One Sample T-Test</strong>.</p>
<p>Select <code>dbp</code> as the <strong>Dependent Variable</strong>. Enter the hypothesised mean as the <strong>Test value</strong> (<code>71</code> in this example) as shown below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/mod04/jamovi/mod4-ttest.png" class="img-fluid figure-img" style="width:100.0%" alt="Screenshot of the Jamovi interface showing setup for a one-sample t-test. The variable “dbp” is entered as the dependent variable and the hypothesised mean test value is set to 71. The analysis options panel for conducting a one-sample t-test is displayed."></p>
</figure>
</div>
</div>
</div>
<p>The test statistic (i.e.&nbsp;t and its degrees of freedom) are provided. By default, Jamovi will calculate a P-value for the two-sided test (H<sub>a</sub>: mean <span class="math inline">\(\neq\)</span> 71), which appropriate for this example.</p>
<p>Note that the one-sample t-test output does not include the mean or the 95% confidence interval of the mean of your variable of interest. This should be obtained using <strong>Exploration &gt; Descriptives</strong>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/mod04/jamovi/mod4-ttest-desc.png" class="img-fluid figure-img" style="width:100.0%" alt="Screenshot of Jamovi descriptive statistics output for the variable “dbp”. The table reports the sample size, mean, standard deviation, standard error, and 95% confidence interval for diastolic blood pressure."></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="r-notes" class="level1 unnumbered">
<h1 class="unnumbered">R notes</h1>
<section id="one-sample-t-test-2" class="level2" data-number="4.17">
<h2 data-number="4.17" class="anchored" data-anchor-id="one-sample-t-test-2"><span class="header-section-number">4.17</span> One sample t-test</h2>
<p>We will use data from <code>mod04_blood_pressure.csv</code> to demonstrate how a one-sample t-test is conducted in R. To test whether the mean diastolic blood pressure of the population from which the sample was drawn is equal to 71, we can use the t.test command:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pima <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/examples/mod04_blood_pressure.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pima<span class="sc">$</span>dbp, <span class="at">mu=</span><span class="dv">71</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  pima$dbp
t = 3.0725, df = 732, p-value = 0.002202
alternative hypothesis: true mean is not equal to 71
95 percent confidence interval:
 71.50732 73.30305
sample estimates:
mean of x 
 72.40518 </code></pre>
</div>
</div>
<p>The output provides:</p>
<ul>
<li>a test statistic (t=3.07);</li>
<li>degrees of freedom for the test statistic (df = 732);</li>
<li>a P-value from the two-sided test (P=0.002);</li>
<li>the mean of the sample (72.4);</li>
<li>and the 95% confidence interval of the mean (71.5 to 73.3).</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="activities" class="level1 unnumbered">
<h1 class="unnumbered">Activities</h1>
<section id="activity-4.1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-4.1">Activity 4.1</h3>
<p>It has been suggested that the average Australian consumes around 8700 kJ per day. A study was conducted to estimate the average dietary consumption of Australian males, aged between 30 and 50. The mean dietary intake was estimated as 9461 kJ, with a 95% confidence interval from 8879 to 10043 kJ. What can you conclude about the dietary consumption of Australian males from this study?</p>
</section>
<section id="activity-4.2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-4.2">Activity 4.2</h3>
<p>Women attending a GP clinic were asked to complete a health survey. Data from 154 responses are saved in <code>Activity_4.2.csv</code>. The file contains the following variables:</p>
<ul>
<li>id: participant ID number</li>
<li>age: age in years</li>
<li>height: height in cm</li>
<li>weight: weight in kg</li>
<li>waist: waist circumference in cm</li>
</ul>
<p>Australia’s National Health Survey has estimated the Australian female population has a mean waist circumference of 87.9cm. Analyse the health survey data to compare women attending a GP clinic to the Australian population.</p>
</section>
<section id="activity-4.3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-4.3">Activity 4.3</h3>
<p>Setting the significance level at P &lt; 0.10 instead of the more usual P &lt; 0.05 increases the likelihood of:</p>
<ol type="a">
<li>a Type I error</li>
<li>a Type II error</li>
<li>rejecting the null hypothesis</li>
<li>not rejecting the null hypothesis</li>
</ol>
</section>
<section id="activity-4.4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-4.4">Activity 4.4</h3>
<p>For a fixed sample size setting the significance level at a very extreme cutoff such as P &lt; 0.001 increases the chances of:</p>
<ol type="a">
<li>obtaining a significant result</li>
<li>rejecting the null hypothesis</li>
<li>a Type I error</li>
<li>a Type II error</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bland15" class="csl-entry" role="listitem">
Bland, Martin. 2015. <em>An <span>Introduction</span> to <span>Medical Statistics</span></em>. 4th Edition. Oxford University Press.
</div>
<div id="ref-kirkwood_sterne01" class="csl-entry" role="listitem">
Kirkwood, Betty, and Jonathan Sterne. 2001. <em>Essentials of <span>Medical Statistics</span></em>. 2nd edition. Wiley-Blackwell.
</div>
<div id="ref-lowitjainstitute21" class="csl-entry" role="listitem">
Lowitja Institute. 2021. <em>Indigenous <span>Data Governance</span> and <span>Sovereignty</span></em>. Https://www.lowitja.org.au/wp-content/uploads/2023/10/328550_data-governance-and-sovereignty.pdf.
</div>
<div id="ref-nationalindigenousaustraliansagency24" class="csl-entry" role="listitem">
National Indigenous Australians Agency. 2024. <span>“Framework for <span>Governance</span> of <span>Indigenous Data</span> <span>NIAA</span>.”</span> In <em>Framework for Governance of Indigenous Data</em>. Https://www.niaa.gov.au/resource-centre/framework-governance-indigenous-data.
</div>
<div id="ref-walter_etal21" class="csl-entry" role="listitem">
Walter, Maggie, Raymond Lovett, Bobby Maher, et al. 2021. <span>“Indigenous <span>Data Sovereignty</span> in the <span>Era</span> of <span>Big Data</span> and <span>Open Data</span>.”</span> <em>Australian Journal of Social Issues</em> 56 (2): 143–56. <a href="https://doi.org/10.1002/ajs4.141">https://doi.org/10.1002/ajs4.141</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-precision.html" class="pagination-link" aria-label="Continuous probability distributions, sampling and precision">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Continuous probability distributions, sampling and precision</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-comparing-two-means.html" class="pagination-link" aria-label="Comparing the means of two groups">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>