<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Hypothesis testing for categorical data – PHCM9795: Foundations of Biostatistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-correlation-and-regression.html" rel="next">
<link href="./06-proportions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-9f93a63bed731ea7c2fe0727957fd65d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-108633c039277fca446d0fb103cb9c0a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner {
        background: #ffdc00;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-testing-proportions.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing for categorical data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing for categorical data</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PHCM9795: Foundations of Biostatistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to biostatistics and data fundamentals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical data, presentation guidelines and probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-precision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Continuous probability distributions, sampling and precision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">An introduction to hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-comparing-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-testing-proportions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing for categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-correlation-and-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-non-parametrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing non-normal data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">An introduction to sample size estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98.1-appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#optional-readings" id="toc-optional-readings" class="nav-link" data-scroll-target="#optional-readings">Optional readings</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">7.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#worked-example" id="toc-worked-example" class="nav-link" data-scroll-target="#worked-example">Worked Example</a></li>
  </ul></li>
  <li><a href="#chi-squared-test-for-independent-proportions" id="toc-chi-squared-test-for-independent-proportions" class="nav-link" data-scroll-target="#chi-squared-test-for-independent-proportions"><span class="header-section-number">7.2</span> Chi-squared test for independent proportions</a>
  <ul class="collapse">
  <li><a href="#assumptions-for-using-a-pearsons-chi-squared-test" id="toc-assumptions-for-using-a-pearsons-chi-squared-test" class="nav-link" data-scroll-target="#assumptions-for-using-a-pearsons-chi-squared-test">Assumptions for using a Pearson’s chi-squared test</a></li>
  <li><a href="#worked-example-7.1" id="toc-worked-example-7.1" class="nav-link" data-scroll-target="#worked-example-7.1">Worked Example 7.1</a></li>
  <li><a href="#fishers-exact-test" id="toc-fishers-exact-test" class="nav-link" data-scroll-target="#fishers-exact-test">Fisher’s exact test</a></li>
  </ul></li>
  <li><a href="#chi-squared-tests-for-tables-larger-than-2-by-2" id="toc-chi-squared-tests-for-tables-larger-than-2-by-2" class="nav-link" data-scroll-target="#chi-squared-tests-for-tables-larger-than-2-by-2"><span class="header-section-number">7.3</span> Chi-squared tests for tables larger than 2-by-2</a>
  <ul class="collapse">
  <li><a href="#worked-example-7.2" id="toc-worked-example-7.2" class="nav-link" data-scroll-target="#worked-example-7.2">Worked Example 7.2</a></li>
  </ul></li>
  <li><a href="#mcnemars-test-for-categorical-paired-data" id="toc-mcnemars-test-for-categorical-paired-data" class="nav-link" data-scroll-target="#mcnemars-test-for-categorical-paired-data"><span class="header-section-number">7.4</span> McNemar’s test for categorical paired data</a>
  <ul class="collapse">
  <li><a href="#worked-example-7.3" id="toc-worked-example-7.3" class="nav-link" data-scroll-target="#worked-example-7.3">Worked Example 7.3</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">7.5</span> Summary</a></li>
  <li><a href="#jamovi-notes" id="toc-jamovi-notes" class="nav-link" data-scroll-target="#jamovi-notes">jamovi notes</a>
  <ul class="collapse">
  <li><a href="#pearsons-chi-squared-test-for-individual-level-data" id="toc-pearsons-chi-squared-test-for-individual-level-data" class="nav-link" data-scroll-target="#pearsons-chi-squared-test-for-individual-level-data"><span class="header-section-number">7.6</span> Pearson’s chi-squared test for individual-level data</a></li>
  <li><a href="#pearsons-chi-squared-test-for-summarised-data" id="toc-pearsons-chi-squared-test-for-summarised-data" class="nav-link" data-scroll-target="#pearsons-chi-squared-test-for-summarised-data"><span class="header-section-number">7.7</span> Pearson’s chi-squared test for summarised data</a></li>
  <li><a href="#chi-squared-test-for-tables-larger-than-2-by-2" id="toc-chi-squared-test-for-tables-larger-than-2-by-2" class="nav-link" data-scroll-target="#chi-squared-test-for-tables-larger-than-2-by-2"><span class="header-section-number">7.8</span> Chi-squared test for tables larger than 2-by-2</a></li>
  <li><a href="#mcnemars-test-for-paired-proportions" id="toc-mcnemars-test-for-paired-proportions" class="nav-link" data-scroll-target="#mcnemars-test-for-paired-proportions"><span class="header-section-number">7.9</span> McNemar’s test for paired proportions</a></li>
  </ul></li>
  <li><a href="#r-notes" id="toc-r-notes" class="nav-link" data-scroll-target="#r-notes">R notes</a>
  <ul class="collapse">
  <li><a href="#pearsons-chi-squared-test-for-individual-level-data-1" id="toc-pearsons-chi-squared-test-for-individual-level-data-1" class="nav-link" data-scroll-target="#pearsons-chi-squared-test-for-individual-level-data-1"><span class="header-section-number">7.10</span> Pearson’s chi-squared test for individual-level data</a></li>
  <li><a href="#pearsons-chi-squared-test-for-summarised-data-1" id="toc-pearsons-chi-squared-test-for-summarised-data-1" class="nav-link" data-scroll-target="#pearsons-chi-squared-test-for-summarised-data-1"><span class="header-section-number">7.11</span> Pearson’s chi-squared test for summarised data</a></li>
  <li><a href="#chi-squared-test-for-tables-larger-than-2-by-2-1" id="toc-chi-squared-test-for-tables-larger-than-2-by-2-1" class="nav-link" data-scroll-target="#chi-squared-test-for-tables-larger-than-2-by-2-1"><span class="header-section-number">7.12</span> Chi-squared test for tables larger than 2-by-2</a></li>
  <li><a href="#mcnemars-test-for-paired-proportions-1" id="toc-mcnemars-test-for-paired-proportions-1" class="nav-link" data-scroll-target="#mcnemars-test-for-paired-proportions-1"><span class="header-section-number">7.13</span> McNemar’s test for paired proportions</a></li>
  </ul></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a>
  <ul class="collapse">
  <li><a href="#activity-7.1" id="toc-activity-7.1" class="nav-link" data-scroll-target="#activity-7.1">Activity 7.1</a></li>
  <li><a href="#activity-7.2" id="toc-activity-7.2" class="nav-link" data-scroll-target="#activity-7.2">Activity 7.2</a></li>
  <li><a href="#activity-7.3" id="toc-activity-7.3" class="nav-link" data-scroll-target="#activity-7.3">Activity 7.3</a></li>
  <li><a href="#activity-7.4" id="toc-activity-7.4" class="nav-link" data-scroll-target="#activity-7.4">Activity 7.4</a></li>
  <li><a href="#supplementary-activity-7.5" id="toc-supplementary-activity-7.5" class="nav-link" data-scroll-target="#supplementary-activity-7.5">Supplementary Activity 7.5</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>By the end of this module you will be able to:</p>
<ul>
<li>Use and interpret the appropriate test for testing associations between categorical data;</li>
<li>Conduct and interpret an appropriate test for independent proportions;</li>
<li>Conduct and interpret a test for paired proportions;</li>
</ul>
</section>
<section id="optional-readings" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="optional-readings">Optional readings</h2>
<p><span class="citation" data-cites="kirkwood_sterne01">Kirkwood and Sterne (<a href="references.html#ref-kirkwood_sterne01" role="doc-biblioref">2001</a>)</span>; Chapter 17. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728">[UNSW Library Link]</a></p>
<p><span class="citation" data-cites="bland15">Bland (<a href="references.html#ref-bland15" role="doc-biblioref">2015</a>)</span>; Chapter 13. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730">[UNSW Library Link]</a></p>
</section>
<section id="introduction" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">7.1</span> Introduction</h2>
<p>In Module 6, we estimated the 95% confidence intervals of proportions and measures of association for categorical data and conducted a significance test comparing a sample proportion to a known value.</p>
<p>When both the outcome variable and the exposure variable are categorical, a chi-squared test can be used as a formal statistical test to assess whether the exposure and outcome are related. The P-value obtained from a chi-squared test gives the probability of obtaining the observed association (or more extreme) if there is in fact no association between the exposure and outcome.</p>
<p>In this Module, we also include tests for a difference in proportion for paired data.</p>
<section id="worked-example" class="level3">
<h3 class="anchored" data-anchor-id="worked-example">Worked Example</h3>
<p>We are using the randomised controlled trial as given in Worked Example 6.4 on the nauseating side effect of a drug.</p>
<p>The research question is whether the active drug resulted in a different rate of nausea than the placebo drug. This is equivalent to testing whether there is an association between nausea and type of drug received (active or placebo). Thus, we will test the null hypothesis that the experience of nausea and the treatment are not related to one another. The null hypothesis is:</p>
<ul>
<li>H<sub>0</sub>: The proportion with nausea in the population receiving the active drug is the same as the proportion in the population receiving the placebo.</li>
</ul>
<p>The alternative hypothesis can be stated as:</p>
<ul>
<li>H<sub>A</sub>: The proportion with nausea in the population receiving the active drug is different to the proportion in the population receiving the placebo.</li>
</ul>
</section>
</section>
<section id="chi-squared-test-for-independent-proportions" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="chi-squared-test-for-independent-proportions"><span class="header-section-number">7.2</span> Chi-squared test for independent proportions</h2>
<p>A chi-squared test is used to test the null hypothesis that of no association between two categorical variables. First a contingency table is constructed and then we estimate the counts of each cell (i.e.&nbsp;a, b, c and d) that would be expected if the null hypothesis was true. The row and column totals are used to calculate expected counts in each cell of the contingency table as follows:</p>
<p>Expected count = (Row count × Column count) / Total count</p>
<p>Statistical software will do this for us, as described in the jamovi or R sections in this Module.</p>
<p>A chi-squared value is then calculated to compare the expected counts (E) in each cell with the observed (actual) cell counts (O). The calculation is as follows:</p>
<p><span class="math inline">\(\chi ^ 2 = \sum \frac{(O - E)}{E} ^2\)</span></p>
<p>with [Number of rows <span class="math inline">\(-\)</span> 1] <span class="math inline">\(\times\)</span> [Number of columns <span class="math inline">\(-\)</span> 1] degrees of freedom.</p>
<p>As for many statistics, the deviations between the observed and expected values are squared to prevent the negative and positive values balancing one another out.</p>
<p>If the expected counts are close to the observed counts, the chi-squared statistic will be close to zero, and the P-value will be close to 1. The larger the difference between the observed and expected counts, the larger the chi-squared statistic becomes (and the smaller the P-value). A large chi-squared statistic provides more evidence of an association between the exposure and outcome.</p>
<section id="assumptions-for-using-a-pearsons-chi-squared-test" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-for-using-a-pearsons-chi-squared-test">Assumptions for using a Pearson’s chi-squared test</h3>
<p>The assumptions that must be met when using Pearson’s chi-squared test are that:</p>
<ul>
<li>each observation must be independent;</li>
<li>each participant is represented in the table once only;</li>
<li>at least 80% of the expected cell counts should exceed a value of five;</li>
<li>all expected cell counts should exceed a value of one.</li>
</ul>
<p>The first two assumptions are dictated by the study design. The last two assumptions relate to the numbers in the cells and should be explored when running the test. There should not be too many cells with low expected counts.</p>
</section>
<section id="worked-example-7.1" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-7.1">Worked Example 7.1</h3>
<p>We will revisit Worked Example 6.4, investigating the relationship between nausea and drug exposure:</p>
<div id="tbl-rr-observed" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rr-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.1: Nausea status by drug exposure
</figcaption>
<div aria-describedby="tbl-rr-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Nausea</th>
<th style="text-align: right;">No nausea</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Active</td>
<td style="text-align: right;">15 (30%)</td>
<td style="text-align: right;">35 (70%)</td>
<td style="text-align: right;">50 (100%)</td>
</tr>
<tr class="even">
<td>Placebo</td>
<td style="text-align: right;">4 (8%)</td>
<td style="text-align: right;">46 (92%)</td>
<td style="text-align: right;">50 (100%)</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">19 (19%)</td>
<td style="text-align: right;">81 (81%)</td>
<td style="text-align: right;">100 (100%)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We can see from the row percentages that 8% of patients in the placebo group experienced nausea compared to 30% of patients in the active group. If no association existed, we would expect to find approximately the same percent of patients with nausea in each group. Statistical software can calculate the values we would expect if there was no association between nausea and drug exposure (i.e.&nbsp;the expected counts):</p>
<div id="tbl-rr-exp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rr-exp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.2: Expected counts of nausea status by drug exposure
</figcaption>
<div aria-describedby="tbl-rr-exp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Nausea</th>
<th style="text-align: right;">No nausea</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Active</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">40.5</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td>Placebo</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">40.5</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>For the data being considered from Worked Example 7.1 all cells have an expected count greater than 5 and that the minimum cell count is 9.5. Therefore, it is appropriate to use the Pearson’s Chi-Squared test. Note that the ‘Expected’ counts are higher for the groups with ‘No nausea’ because ‘No nausea’ is more prevalent in the sample than ‘Nausea’.</p>
<p>The chi-squared statistic is calculated as 7.86 with 1 df, giving a P-value of 0.005. Combining these results with the estimated relative risk (from Module 6), we can state:</p>
<p>The proportion with nausea in those who received the active drug is 30%, compared to 8% in those who received the placebo drug. Nausea was more frequent in those who received the active drug (Relative Risk = 3.75, 95% CI: 1.34 to 10.51). There is strong evidence that the proportion with nausea differs between the two groups (<span class="math inline">\(\chi ^2\)</span> = 7.86 with 1 df, P=0.005).</p>
</section>
<section id="fishers-exact-test" class="level3">
<h3 class="anchored" data-anchor-id="fishers-exact-test">Fisher’s exact test</h3>
<p>If small expected cell counts are present, Fisher’s exact test can be used instead. More information on Fisher’s exact test can be found in Chapter 13 of An Introduction to Medical Statistics, <span class="citation" data-cites="bland15">Bland (<a href="references.html#ref-bland15" role="doc-biblioref">2015</a>)</span>, or Section 17.3 of Essential Medical Statistics, <span class="citation" data-cites="kirkwood_sterne01">Kirkwood and Sterne (<a href="references.html#ref-kirkwood_sterne01" role="doc-biblioref">2001</a>)</span>. The computation of Fisher’s exact test is complex, and best conducted by statistical software.</p>
<p>A reasonable question could be posed: why not conduct Fisher’s exact test by default? The answer to this is complex.</p>
<p>Fisher’s exact test has quite a restrictive assumption: we assume that the totals of the rows and columns are fixed before we conduct the study.</p>
<p>From Worked Example 7.1, this would be saying that we knew we would end up with 50 people in the active treatment arm, and 50 people in the placebo. This seems reasonable, we can design our study to randomise equal groups. However, Fisher’s exact test also assumes that we know we will obtain 19 people with nausea and 81 people without nausea. We cannot possibly know this before we do the study.</p>
<p>In the case where we cannot assume that the totals of the rows and columns are fixed before we conduct the study, it can be shown that Fisher’s exact test will be conservative (we will be less likely to reject the null hypothesis when it is false, or in other words, the P-value will be larger than it should be).</p>
<p>While there are other tests that perform better than Fisher’s exact test, most of the time we live with this conservative test when we have to (i.e.&nbsp;for small expected cell counts) because Fisher’s exact test is so widely known.</p>
<p>Pragmatically, we use the standard (Pearson) chi-square when we can, and Fisher’s exact test only when we have small expected cell counts.</p>
</section>
</section>
<section id="chi-squared-tests-for-tables-larger-than-2-by-2" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="chi-squared-tests-for-tables-larger-than-2-by-2"><span class="header-section-number">7.3</span> Chi-squared tests for tables larger than 2-by-2</h2>
<p>Chi-squared tests can also be used for tables larger than a 2-by-2 dimension. When a contingency table larger than 2-by-2 is used, say a 4-by-2 table if there were 4 exposure groups, the Pearson’s chi-squared can still be used.</p>
<section id="worked-example-7.2" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-7.2">Worked Example 7.2</h3>
<p>The file <code>mod07_allergy.rds</code> contain information about the severity of allergic reaction, coded as absent, slight, moderate or severe. We can test the hypothesis that the severity of allergy is not different between males and females. To do this we can use a two-way tabulation to obtain <a href="#tbl-allergy-obs" class="quarto-xref">Table&nbsp;<span>7.3</span></a> which shows the counts and the percent of females and males who fall into each severity group for allergy. The table shows that the percentage of males is higher in each of the categories of severity (slight, moderate, severe) than the percentage of females. <a href="#tbl-allergy-exp" class="quarto-xref">Table&nbsp;<span>7.4</span></a> shows the expected counts.</p>
<div id="tbl-allergy-obs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-allergy-obs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.3: Association between sex and allergy severity - observed counts
</figcaption>
<div aria-describedby="tbl-allergy-obs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Sex</th>
<th style="text-align: right;">Non-allergenic</th>
<th style="text-align: right;">Slight allergy</th>
<th style="text-align: right;">Moderate allergy</th>
<th style="text-align: right;">Severe allergy</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Female</td>
<td style="text-align: right;">150 (62.0%)</td>
<td style="text-align: right;">50 (20.7%)</td>
<td style="text-align: right;">27 (11.2%)</td>
<td style="text-align: right;">15 (6.2%)</td>
<td style="text-align: right;">242 (100%)</td>
</tr>
<tr class="even">
<td>Male</td>
<td style="text-align: right;">137 (53.1%)</td>
<td style="text-align: right;">70 (27.1%)</td>
<td style="text-align: right;">32 (12.4%)</td>
<td style="text-align: right;">19 (7.4%)</td>
<td style="text-align: right;">258 (100%)</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">287 (57.4%)</td>
<td style="text-align: right;">120 (24.0%)</td>
<td style="text-align: right;">59 (11.8%)</td>
<td style="text-align: right;">34 (6.8%)</td>
<td style="text-align: right;">500 (100.0%)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-allergy-exp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-allergy-exp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.4: Association between sex and allergy severity - expected counts
</figcaption>
<div aria-describedby="tbl-allergy-exp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Sex</th>
<th style="text-align: right;">Non-allergenic</th>
<th style="text-align: right;">Slight allergy</th>
<th style="text-align: right;">Moderate allergy</th>
<th style="text-align: right;">Severe allergy</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Female</td>
<td style="text-align: right;">138.9</td>
<td style="text-align: right;">58.1</td>
<td style="text-align: right;">28.6</td>
<td style="text-align: right;">16.5</td>
<td style="text-align: right;">242.0</td>
</tr>
<tr class="even">
<td>Male</td>
<td style="text-align: right;">148.1</td>
<td style="text-align: right;">61.9</td>
<td style="text-align: right;">30.4</td>
<td style="text-align: right;">17.5</td>
<td style="text-align: right;">258.0</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">287.0</td>
<td style="text-align: right;">120.0</td>
<td style="text-align: right;">59.0</td>
<td style="text-align: right;">34.0</td>
<td style="text-align: right;">500.0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The Pearson chi-squared statistic is calculated as 4.31, with 3 degrees of freedom, providing a P-value of 0.23. Therefore, there is little evidence of an association between gender and the severity of allergy.</p>
</section>
</section>
<section id="mcnemars-test-for-categorical-paired-data" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="mcnemars-test-for-categorical-paired-data"><span class="header-section-number">7.4</span> McNemar’s test for categorical paired data</h2>
<p>If a binary categorical outcome is measured in a paired study design, McNemar’s statistic is used. This statistic is a form of chi-square applied to a paired situation. A Pearson’s chi-squared test cannot be used because the measurements are not independent. However, McNemar’s test can be used to assess whether there is a significant change in proportions between two time points or between two conditions, or whether there is a significant difference in proportions between matched cases and controls.</p>
<p>For McNemar’s test, the data are displayed as shown in <a href="#tbl-7-1" class="quarto-xref">Table&nbsp;<span>7.5</span></a>. Cells ‘a’ and ‘d’ called concordant cells because the response was the same at both baseline and follow-up or between matched cases and controls. Cells ‘b’ and ‘c’ are called discordant cells because the responses between the pairs were different. For a follow-up study, the participants in cell ‘c’ had a positive response at baseline and a negative response at follow-up. Conversely, the participants in cell ‘b’ had a negative response at baseline and a positive response at follow-up.</p>
<p>For other types of paired data such as twins or matched cases and controls, the data are similarly displayed with the responses of one of the pairs in the columns and the responses for the other of the pairs in the rows. For paired data, the grand total ‘N’ is always the number of pairs and not the total number of participants.</p>
<div class="cell" data-tbl-pos="h">
<div id="tbl-7-1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="h">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-7-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.5: Table layout for testing matched proportions
</figcaption>
<div aria-describedby="tbl-7-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_iqb5dn0ges97kapl29ga = TinyTable.createTableFunctions("tinytable_iqb5dn0ges97kapl29ga");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '3', j: 3 }, { i: '3', j: 4 } ], css_id: 'tinytable_css_un4o6sgn66mjn8prvs17',}, 
          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_d53thm5pyjy68cdq3gzu',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_iqb5dn0ges97kapl29ga.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_iqb5dn0ges97kapl29ga td.tinytable_css_un4o6sgn66mjn8prvs17, #tinytable_iqb5dn0ges97kapl29ga th.tinytable_css_un4o6sgn66mjn8prvs17 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }
    #tinytable_iqb5dn0ges97kapl29ga td.tinytable_css_d53thm5pyjy68cdq3gzu, #tinytable_iqb5dn0ges97kapl29ga th.tinytable_css_d53thm5pyjy68cdq3gzu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_iqb5dn0ges97kapl29ga" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Negative at follow-up</th>
                <th scope="col" data-row="0" data-col="3">Positive at follow-up</th>
                <th scope="col" data-row="0" data-col="4">Total</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Negative at baseline</td>
                  <td data-row="1" data-col="2">a</td>
                  <td data-row="1" data-col="3">b</td>
                  <td data-row="1" data-col="4">a + b</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1">Positive at baseline</td>
                  <td data-row="2" data-col="2">c</td>
                  <td data-row="2" data-col="3">d</td>
                  <td data-row="2" data-col="4">c + d</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Total</td>
                  <td data-row="3" data-col="2">a + c</td>
                  <td data-row="3" data-col="3">b + d</td>
                  <td data-row="3" data-col="4">N</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</figure>
</div>
</div>
<section id="worked-example-7.3" class="level3">
<h3 class="anchored" data-anchor-id="worked-example-7.3">Worked Example 7.3</h3>
<p>Two drugs labelled A and B have been administered to patients in random order so that each patient acts as their own control. The data have been saved as <code>mod07_drug_response.rds</code>. The null hypothesis is as follows:</p>
<ul>
<li>H<sub>0</sub>: The proportion of patients who do better on drug A is the same as the proportion of patients who do better on drug B</li>
</ul>
<p>Counts and overall percentages are presented in . From the “Total” row in the table, we can see that the number of patients who respond to drug A is 41 (68%) and from the “Total” column the number who respond to drug B is less at 35 (58%), that is there is a difference of 10%.</p>
<table class="caption-top table">
<caption>Worked Example 7.3: Paired data</caption>
<colgroup>
<col style="width: 27%">
<col style="width: 23%">
<col style="width: 27%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Response to Drug B</th>
<th style="text-align: center;">No response to Drug B</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Response to Drug A</td>
<td style="text-align: center;">21 (35%)</td>
<td style="text-align: center;">20 (33%)</td>
<td>41 (68%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">No response to Drug A</td>
<td style="text-align: center;">14 (23%)</td>
<td style="text-align: center;">5 (8%)</td>
<td>19 (32%)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">35 (58%)</td>
<td style="text-align: center;">25 (42%)</td>
<td>60 (100%)</td>
</tr>
</tbody>
</table>
<p>The difference in the paired proportions is calculated using the simple equation:</p>
<p><span class="math display">\[ p_{A} - p_{B} = \frac{(b - c)}{N} \]</span></p>
<p>Here, <span class="math inline">\(p_{A} - p_{B} = \frac{(20 - 14)}{60} = 0.1\)</span></p>
<p>The cell counts show that 20 patients responded to Drug A but not to drug B, and 14 patients responded to Drug B but not to drug A. McNemar’s statistic is computed from these two discordant pairs (labelled as ‘b’ and ‘c’) as follows:</p>
<p><span class="math display">\[ X^2 = \frac{(b-c)^2}{b+c} \]</span></p>
<p>with 1 degree of freedom. Using our worked example, the McNemar’s chi-squared statistic is calculated as 1.06 with 1 degree of freedom, giving a P-value of 0.3.</p>
<p>Note that some packages also calculate an “Exact P-Value”. The standard McNemar’s chi-squared statistic is generally recommended, unless the sum of the discordant cells is small (Kirkwood and Sterne define small as less than 10; Section 21.3, Kirkwood and Sterne 2001)). Here, <span class="math inline">\(b + c = 34\)</span>, so reporting the standard McNemar’s chi-squared statistic is appropriate.</p>
<p>As described above, the difference in proportions can be calculated. A 95% confidence interval for this difference can be obtained using statistical software.</p>
<p>In this study of 60 participants, where each participant received both drugs, 41 (68%) responded to Drug A and 35 (58%) responded to Drug B. The difference in the proportions responding is estimated as 10% (95% CI -11% to 31%). There is no evidence that the response differed between the two drugs (McNemar’s chi-square=1.06 with 1 degree of freedom, P=0.3).</p>
</section>
</section>
<section id="summary" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="summary"><span class="header-section-number">7.5</span> Summary</h2>
<p>In Module 6, we estimated proportions and measures of association for categorical data and conducted a one-sample test of proportions. In this module, we conduct significance tests for two or more independent proportions using the chi-squared test. The chi-squared test can also be used to conduct a significance test when there are more than two categories in both variables. The McNemar’s test is used when we have paired data.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="jamovi-notes" class="level1 unnumbered">
<h1 class="unnumbered">jamovi notes</h1>
<section id="pearsons-chi-squared-test-for-individual-level-data" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="pearsons-chi-squared-test-for-individual-level-data"><span class="header-section-number">7.6</span> Pearson’s chi-squared test for individual-level data</h2>
<p>Conducting a Pearson’s chi-squared test is done automatically when producing a 2-by-2 table in jamovi. All that we need to do is check that the assumptions of the Pearson’s chi-squared test are met, by examining the Expected counts in each cell.</p>
<p>Worked Example 7.1 is completed as in Module 6, but we first examine the Expected counts (remember that we need to change the order of the levels for the exposure and outcome variables):</p>
<p><img src="img/mod07/jamovi/mod07-expected-counts.png" class="img-fluid"></p>
<p>After confirming that there are no cells with small expected frequencies, we can interpret the chi-square test. The last section reports the chi-squared test statistic which has a value of 7.86 with 1 degree of freedom and a P-value of 0.005.</p>
<p>If there are small values of expected frequencies, Fisher’s exact test can be requested in the <strong>Statistics</strong> section:</p>
<p><img src="img/mod07/jamovi/mod07-expected-counts.png" class="img-fluid" style="width:50.0%"></p>
</section>
<section id="pearsons-chi-squared-test-for-summarised-data" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="pearsons-chi-squared-test-for-summarised-data"><span class="header-section-number">7.7</span> Pearson’s chi-squared test for summarised data</h2>
<p>When you only have the summarised date (for example, the cross-tabulated data), you need to enter the summarised data manually as we did in Module 6. After defining the <strong>Count variable</strong>, the Pearson chi-squared test is calculated automatically.</p>
</section>
<section id="chi-squared-test-for-tables-larger-than-2-by-2" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="chi-squared-test-for-tables-larger-than-2-by-2"><span class="header-section-number">7.8</span> Chi-squared test for tables larger than 2-by-2</h2>
<p>Use the data in <code>mod07_allergy.rds</code>. We use similar steps as described above for a 2-by-2 table:</p>
<p><img src="img/mod07/jamovi/mod07-large-table-expected.png" class="img-fluid"></p>
<p><img src="img/mod07/jamovi/mod07-large-table.png" class="img-fluid"></p>
</section>
<section id="mcnemars-test-for-paired-proportions" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="mcnemars-test-for-paired-proportions"><span class="header-section-number">7.9</span> McNemar’s test for paired proportions</h2>
<p>To perform this test in jamovi, we will use the dataset <code>mod07_drug_response.rds</code>. As with all 2-by-2 tables, we should check that the variables are set up with the first level of the variable being the outcome of interest using <strong>Data &gt; Setup</strong>:</p>
<p><img src="img/mod07/jamovi/mod07-paired01.png" class="img-fluid" style="width:50.0%"></p>
<p>Both variables, <code>druga</code> and <code>drugb</code> are set up with “No” being the first level. We need to change the order and define “Yes” as the first level (See Module 6 jamovi notes on how to do this):</p>
<p><img src="img/mod07/jamovi/mod07-paired02.png" class="img-fluid" style="width:50.0%"></p>
<p>The McNemar’s test of paired proportions can be conducted at <strong>Analyses &gt; Frequencies &gt; Contingency Tables &gt; Paired Samples &gt; McNemar test</strong>:</p>
<p><img src="img/mod07/jamovi/mod07-paired03.png" class="img-fluid" style="width:50.0%"></p>
<p>Note that jamovi does not currently provide an estimate of the difference in paired proportions, or a confidence interval for the difference.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="r-notes" class="level1 unnumbered">
<h1 class="unnumbered">R notes</h1>
<section id="pearsons-chi-squared-test-for-individual-level-data-1" class="level2" data-number="7.10">
<h2 data-number="7.10" class="anchored" data-anchor-id="pearsons-chi-squared-test-for-individual-level-data-1"><span class="header-section-number">7.10</span> Pearson’s chi-squared test for individual-level data</h2>
<p>We will demonstrate how to use R to conduct a Pearson chi-squared test using Worked Example 7.1.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>nausea <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/examples/mod06_nausea.rds"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nausea)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    group side_effect
1 Placebo      Nausea
2 Placebo      Nausea
3 Placebo      Nausea
4 Placebo      Nausea
5 Placebo   No nausea
6 Placebo   No nausea</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(nausea<span class="sc">$</span>group)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "Placebo","Active": 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "label")= chr "Group"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(nausea<span class="sc">$</span>side_effect)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "No nausea","Nausea": 2 2 2 2 1 1 1 1 1 1 ...
 - attr(*, "label")= chr "Side effect"</code></pre>
</div>
</div>
<p>The columns <code>group</code> and <code>side_effect</code> have been entered as factors, with “Placebo” and “No nausea” as the first levels. We should use the <code>relevel()</code> command to re-order the factor levels.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nausea <span class="ot">&lt;-</span> <span class="fu">mutate</span>(nausea, <span class="at">group =</span> <span class="fu">relevel</span>(group, <span class="at">ref =</span> <span class="st">"Active"</span>), </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">side_effect =</span> <span class="fu">relevel</span>(side_effect, <span class="at">ref =</span> <span class="st">"Nausea"</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(nausea<span class="sc">$</span>group)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "Active","Placebo": 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(nausea<span class="sc">$</span>side_effect)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "Nausea","No nausea": 1 1 1 1 2 2 2 2 2 2 ...</code></pre>
</div>
</div>
<p>After confirming the factors are appropriately defined, we can construct our 2-by-2 table and view the expected frequencies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contTables</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> nausea,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">rows =</span> group, <span class="at">cols =</span> side_effect,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">exp =</span> <span class="cn">TRUE</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 CONTINGENCY TABLES

 Contingency Tables                                             
 ────────────────────────────────────────────────────────────── 
   group                  Nausea       No nausea    Total       
 ────────────────────────────────────────────────────────────── 
   Active     Observed           15           35           50   
              Expected     9.500000     40.50000     50.00000   
                                                                
   Placebo    Observed            4           46           50   
              Expected     9.500000     40.50000     50.00000   
                                                                
   Total      Observed           19           81          100   
              Expected    19.000000     81.00000    100.00000   
 ────────────────────────────────────────────────────────────── 


 χ² Tests                              
 ───────────────────────────────────── 
         Value       df    p           
 ───────────────────────────────────── 
   χ²    7.862248     1    0.0050478   
   N          100                      
 ───────────────────────────────────── </code></pre>
</div>
</div>
<p>After confirming that there are no cells with small expected frequencies, we can interpret the chi-square test. The last section reports the chi-squared test statistic which has a value of 7.86 with 1 degree of freedom and a P-value of 0.005.</p>
<p>If there are small values of expected frequencies, Fisher’s exact test can be requested using <code>fisher = TRUE</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contTables</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> nausea,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">rows =</span> group, <span class="at">cols =</span> side_effect,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fisher =</span> <span class="cn">TRUE</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 CONTINGENCY TABLES

 Contingency Tables                          
 ─────────────────────────────────────────── 
   group      Nausea    No nausea    Total   
 ─────────────────────────────────────────── 
   Active         15           35       50   
   Placebo         4           46       50   
   Total          19           81      100   
 ─────────────────────────────────────────── 


 χ² Tests                                               
 ────────────────────────────────────────────────────── 
                          Value       df    p           
 ────────────────────────────────────────────────────── 
   χ²                     7.862248     1    0.0050478   
   Fisher's exact test                      0.0094886   
   N                           100                      
 ────────────────────────────────────────────────────── </code></pre>
</div>
</div>
</section>
<section id="pearsons-chi-squared-test-for-summarised-data-1" class="level2" data-number="7.11">
<h2 data-number="7.11" class="anchored" data-anchor-id="pearsons-chi-squared-test-for-summarised-data-1"><span class="header-section-number">7.11</span> Pearson’s chi-squared test for summarised data</h2>
<p>When you only have the summarised date (for example, the cross-tabulated data), you need to enter the summarised data manually. As we did in Module 6, the 2-by-2 table can be entered as four lines of data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>drug_aggregated <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> <span class="fu">c</span>(<span class="st">"Active"</span>, <span class="st">"Active"</span>, <span class="st">"Placebo"</span>, <span class="st">"Placebo"</span>),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">side_effect =</span> <span class="fu">c</span>(<span class="st">"Nausea"</span>, <span class="st">"No nausea"</span>, <span class="st">"Nausea"</span>, <span class="st">"No nausea"</span>),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">35</span>, <span class="dv">4</span>, <span class="dv">46</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>contTables()</code> function is used in the usual way, specifying <code>count=n</code>.</p>
</section>
<section id="chi-squared-test-for-tables-larger-than-2-by-2-1" class="level2" data-number="7.12">
<h2 data-number="7.12" class="anchored" data-anchor-id="chi-squared-test-for-tables-larger-than-2-by-2-1"><span class="header-section-number">7.12</span> Chi-squared test for tables larger than 2-by-2</h2>
<p>Use the data in <code>mod07_allergy.rds</code>. We use similar steps as described above for a 2-by-2 table.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>allergy <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/examples/mod07_allergy.rds"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(allergy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id asthma hdmallergy catallergy infection    sex maternalasthma
1  1     No        Yes         No       Yes Female             No
2  2    Yes         No         No        No Female             No
3  3    Yes         No         No        No Female             No
4  4     No         No         No        No   Male             No
5  4    Yes        Yes        Yes        No Female             No
6  5    Yes        Yes        Yes        No Female             No
  allergy_severity
1 Moderate allergy
2     Non-allergic
3     Non-allergic
4     Non-allergic
5 Moderate allergy
6 Moderate allergy</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contTables</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> allergy,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">rows =</span> allergy_severity, <span class="at">cols =</span> sex,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">pcCol =</span> <span class="cn">TRUE</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 CONTINGENCY TABLES

 Contingency Tables                                                             
 ────────────────────────────────────────────────────────────────────────────── 
   allergy_severity                       Female       Male         Total       
 ────────────────────────────────────────────────────────────────────────────── 
   Non-allergic        Observed                 150          137          287   
                       % within column     61.98347     53.10078     57.40000   
                                                                                
   Slight allergy      Observed                  50           70          120   
                       % within column     20.66116     27.13178     24.00000   
                                                                                
   Moderate allergy    Observed                  27           32           59   
                       % within column     11.15702     12.40310     11.80000   
                                                                                
   Severe allergy      Observed                  15           19           34   
                       % within column      6.19835      7.36434      6.80000   
                                                                                
   Total               Observed                 242          258          500   
                       % within column    100.00000    100.00000    100.00000   
 ────────────────────────────────────────────────────────────────────────────── 


 χ² Tests                              
 ───────────────────────────────────── 
         Value       df    p           
 ───────────────────────────────────── 
   χ²    4.308913     3    0.2299813   
   N          500                      
 ───────────────────────────────────── </code></pre>
</div>
</div>
</section>
<section id="mcnemars-test-for-paired-proportions-1" class="level2" data-number="7.13">
<h2 data-number="7.13" class="anchored" data-anchor-id="mcnemars-test-for-paired-proportions-1"><span class="header-section-number">7.13</span> McNemar’s test for paired proportions</h2>
<p>To perform this test in R, we will use the dataset <code>mod07_drug_response.rds</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>drug <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/examples/mod07_drug_response.rds"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(drug)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  druga drugb
1   Yes   Yes
2   Yes   Yes
3   Yes   Yes
4   Yes   Yes
5   Yes   Yes
6   Yes   Yes</code></pre>
</div>
</div>
<p>As usual, we should check that the variables being tabulated are factors, with the first level of the factor being the outcome of interest.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(drug<span class="sc">$</span>druga)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 - attr(*, "label")= chr "Response to Drug A"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(drug<span class="sc">$</span>drugb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 - attr(*, "label")= chr "Response to Drug B"</code></pre>
</div>
</div>
<p>Here we see that the first level of the factor is “No” - we need to use the <code>relevel()</code> function to re-order the levels so “Yes” is the first level:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>drug <span class="ot">&lt;-</span> <span class="fu">mutate</span>(drug, <span class="at">druga =</span> <span class="fu">relevel</span>(druga, <span class="at">ref =</span> <span class="st">"Yes"</span>),</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">drugb =</span> <span class="fu">relevel</span>(drugb, <span class="at">ref =</span> <span class="st">"Yes"</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(drug<span class="sc">$</span>druga)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "Yes","No": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(drug<span class="sc">$</span>drugb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "Yes","No": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>We can use the <code>contTablesPaired()</code> function within the <code>jmv</code> library to conduct McNemar’s test of paired proportions:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contTablesPaired</span>(<span class="at">data =</span> drug, <span class="at">rows =</span> druga, <span class="at">cols =</span> drugb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 PAIRED SAMPLES CONTINGENCY TABLES

 Contingency Tables              
 ─────────────────────────────── 
   druga    Yes    No    Total   
 ─────────────────────────────── 
   Yes       21    20       41   
   No        14     5       19   
   Total     35    25       60   
 ─────────────────────────────── 


 McNemar Test                          
 ───────────────────────────────────── 
         Value       df    p           
 ───────────────────────────────────── 
   χ²    1.058824     1    0.3034837   
   N           60                      
 ───────────────────────────────────── </code></pre>
</div>
</div>
<p>Note that <code>contTablesPaired()</code> does not calculate an exact P-value.</p>
<p>To estimate the proportion in each of the paired samples, its difference, and the 95% confidence interval of the difference, we can use the <code>mcNemarDiff()</code> function which can be downloaded <a href="https://gist.githubusercontent.com/timothydobbins/525d25271b04b2ea72aae70c4aac8b01/raw/6b69f5b229d50daeac4c2f4cf4331e88b0c65717/mcNemarDiff.R">here</a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Copied from gist.githubusercontent.com</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>mcNemarDiff <span class="ot">&lt;-</span> <span class="cf">function</span>(data, var1, var2, <span class="at">digits =</span> <span class="dv">3</span>) {</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"epibasix"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">stop</span>(<span class="st">"This function requires epibasix to be installed"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    tab <span class="ot">&lt;-</span> <span class="fu">table</span>(data[[var1]], data[[var2]])</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    p1 <span class="ot">&lt;-</span> (tab[<span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">+</span> tab[<span class="dv">1</span>, <span class="dv">2</span>]) <span class="sc">/</span> <span class="fu">sum</span>(tab)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    p2 <span class="ot">&lt;-</span> (tab[<span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">+</span> tab[<span class="dv">2</span>, <span class="dv">1</span>]) <span class="sc">/</span> <span class="fu">sum</span>(tab)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    pd <span class="ot">&lt;-</span> epibasix<span class="sc">::</span><span class="fu">mcNemar</span>(tab)<span class="sc">$</span>rd</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    pd.cil <span class="ot">&lt;-</span> epibasix<span class="sc">::</span><span class="fu">mcNemar</span>(tab)<span class="sc">$</span>rd.CIL</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    pd.ciu <span class="ot">&lt;-</span> epibasix<span class="sc">::</span><span class="fu">mcNemar</span>(tab)<span class="sc">$</span>rd.CIU</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste0</span>(</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Proportion 1: "</span>,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>        <span class="fu">format</span>(<span class="fu">round</span>(p1, <span class="at">digits =</span> digits), <span class="at">nsmall =</span> digits),</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"; Proportion 2: "</span>, <span class="fu">format</span>(<span class="fu">round</span>(p2, <span class="at">digits =</span> digits), <span class="at">nsmall =</span> digits)</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste0</span>(</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Difference in paired proportions: "</span>,</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>        <span class="fu">format</span>(<span class="fu">round</span>(pd, <span class="at">digits =</span> digits), <span class="at">nsmall =</span> digits),</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>        <span class="st">"; 95% CI: "</span>, <span class="fu">format</span>(<span class="fu">round</span>(pd.cil, <span class="at">digits =</span> digits), <span class="at">nsmall =</span> digits),</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>        <span class="st">" to "</span>, <span class="fu">format</span>(<span class="fu">round</span>(pd.ciu, <span class="at">digits =</span> digits), <span class="at">nsmall =</span> digits)</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="do">### End copy</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a><span class="fu">mcNemarDiff</span>(<span class="at">data =</span> drug, <span class="at">var1 =</span> <span class="st">"druga"</span>, <span class="at">var2 =</span> <span class="st">"drugb"</span>, <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Proportion 1: 0.68; Proportion 2: 0.58"
[1] "Difference in paired proportions: 0.10; 95% CI: -0.11 to 0.31"</code></pre>
</div>
</div>
<p>In this study of 60 participants, where each participant received both drugs, 41 (68%) responded to Drug A and 35 (58%) responded to Drug B. The difference in the proportions responding is estimated as 10% (95% CI -11% to 31%). There is no evidence that the response differed between the two drugs (McNemar’s chi-squared = 1.06 with 1df, P=0.30).</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="activities" class="level1 unnumbered">
<h1 class="unnumbered">Activities</h1>
<section id="activity-7.1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-7.1">Activity 7.1</h3>
<p>This activity continues from Activity 6.2, where a survey was conducted of a random sample of 514 upper primary school children to measure the prevalence of asthma. Use the dataset <code>Activity_6.2.rds</code> to investigate whether there is a gender difference in the prevalence of asthma.</p>
</section>
<section id="activity-7.2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-7.2">Activity 7.2</h3>
<p>This activity continues from Activity 6.5, a study to determine the cause of mortality where 89 people were followed up for 5 years. The file <code>Activity_7.2.rds</code> summarise 5-year mortality (the outcome) for 89 people who did or did not have a heart attack (the exposure). The data are entered as:</p>
<ul>
<li>heart_attack: Heart attack status: 1=No, 2=Yes</li>
<li>mortality: 5-year mortality; 1=No, 2=Yes</li>
</ul>
<p>Analyse these data to assess whether 5-year mortality differs between those who have a heart attack and those who do not.</p>
</section>
<section id="activity-7.3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-7.3">Activity 7.3</h3>
<p>Hand hygiene is crucial for retail food workers to prevent the spread of germs and pathogens from their hands to food, which can cause foodborne illnesses. By properly washing their hands, workers can protect customers from contamination and maintain a safe food environment.</p>
<p>A study was conducted by the Sunrise public health unit to assess whether a health promotion campaign could increase the rate of adequate hand hygiene. 107 retail food workers, working in Sunrise, were enrolled in the study, and their hand-washing techniques were observed before and after the health promotion campaign. Handwashing was classified as either inadequate or adequate.</p>
<p>The file <code>Activity_7.3.csv</code> contains the following variables:</p>
<ul>
<li>age</li>
<li>sex</li>
<li>handwash_baseline: handwashing technique before the campaign:</li>
<li>0=inadequate technique, 1=adequate technique</li>
<li>handwash_followup: handwashing technique after the campaign:</li>
<li>0=inadequate technique, 1=adequate technique</li>
</ul>
<p>Analyse these data to assess the impact of the health promotion campaign.</p>
</section>
<section id="activity-7.4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-7.4">Activity 7.4</h3>
<p>A study was conducted to assess whether the rate of premature births differed by region. We examined a survey of 200 live births in an urban region in which 2 babies were born prematurely. We also surveyed 80 live births in a rural region and found that 5 babies were born prematurely.</p>
<p>Analyse these data to answer the research question. Write a brief report summarising your results and state your conclusion.</p>
</section>
<section id="supplementary-activity-7.5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="supplementary-activity-7.5">Supplementary Activity 7.5</h3>
<p>The betel nut, the seed of the areca palm, is grown in the tropical Pacific and Asia and is a commonly use psycho-active substance. Betel nut is often chewed, wrapped inside betel leaves or in combination with tobacco. Chewing betel nut has been linked with a range of health issues.</p>
<p>A case-control study was conducted to assess the association between chewing betel nut and obstructive coronary artery disease. 293 men with obstructive coronary artery disease were recruited, and 88 reported having chewed betel nut. Of the 720 healthy control men recruited, 57 reported having chewed betel nut.</p>
<p>Analyse these data to answer the research question. Write a brief report summarising your results and state your conclusion.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bland15" class="csl-entry" role="listitem">
Bland, Martin. 2015. <em>An <span>Introduction</span> to <span>Medical Statistics</span></em>. 4th Edition. Oxford University Press.
</div>
<div id="ref-kirkwood_sterne01" class="csl-entry" role="listitem">
Kirkwood, Betty, and Jonathan Sterne. 2001. <em>Essentials of <span>Medical Statistics</span></em>. 2nd edition. Wiley-Blackwell.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-proportions.html" class="pagination-link" aria-label="Summary statistics for binary data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-correlation-and-regression.html" class="pagination-link" aria-label="Correlation and simple linear regression">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>